//! Integration tests for the OPT-IN association (Privacy-Pools-style) layer.
//!
//! These load the COMPILED SBF program into mollusk's in-process SVM and drive
//! real instructions, so run `cargo build-sbf` first.
//!
//! Coverage:
//!  - INIT_ASSOCIATION registers a curator's set; re-registration fails; a set
//!    over a non-pool account is rejected; a body byte is rejected.
//!  - UPDATE_ASSOCIATION_ROOT publishes into the ring, only for the registered
//!    curator; the all-zero root is refused; the ring wraps and evicts the oldest.
//!  - SETTLE_ZK_ASSOCIATED ACCEPTS the committed association fixture proof and
//!    executes the escrow transfer.
//!  - SETTLE_ZK_ASSOCIATED REJECTS a proof whose association root the curator
//!    never published (AssociationRootNotKnown), one whose root has AGED OUT of
//!    the ring (the "stale root" case), one against a set belonging to a
//!    DIFFERENT pool, one against a forged (non-PDA / non-program-owned) set
//!    account, and one where the on-chain root is known but the PROOF commits to
//!    a different association root (ProofVerificationFailed).
//!  - The two settle paths share ONE spent-set: settling with an association
//!    proof burns the nullifier for the plain path too.
//!  - A membership (4-input) proof cannot satisfy the association instruction.

use std::collections::{HashMap, HashSet};

use mollusk_svm::{
    program::keyed_account_for_system_program,
    result::{Check, InstructionResult},
    Mollusk,
};
use solana_account::Account;
use solana_instruction::{AccountMeta, Instruction};
use solana_program_error::ProgramError;
use solana_pubkey::Pubkey;

use mirror_pool::{
    pda::{ASSOCIATION_SEED, NULLIFIER_SEED, POOL_SEED},
    state::{association, nullifier, pool},
    wire::tag,
    MirrorPoolError,
};

const SOL: u64 = 1_000_000_000;

/// The committed, known-good ASSOCIATION proof + public inputs (generated by
/// `circuits/build_association.sh`). PUBLIC_INPUTS is
/// `[root, nullifierHash, actionHash, epoch, associationRoot]`.
mod fixture {
    include!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../circuits/artifacts/association_proof_fixture.rs"
    ));
}

/// The committed MEMBERSHIP fixture, used only to show a 4-input membership proof
/// cannot satisfy the 5-input association instruction. Only its PROOF_* bytes are
/// needed here (the public inputs come from the association fixture, so the two
/// settle paths are driven at the same nullifier), hence the `dead_code` allow on
/// the generated constants.
#[allow(dead_code)]
mod membership_fixture {
    include!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../circuits/artifacts/proof_fixture.rs"
    ));
}

/// The fixture's epoch (public signal [3] = 11; see gen_association_fixture.js).
const ZK_EPOCH: u64 = 11;
/// The escrow amount bound into the fixture's actionHash (0.75 SOL).
const ZK_AMOUNT: u64 = 750_000_000;

/// The fresh recipient bound into the fixture's actionHash: bytes 0x21..0x40.
fn zk_recipient() -> Pubkey {
    let mut b = [0u8; 32];
    for (i, x) in b.iter_mut().enumerate() {
        *x = (i + 0x21) as u8;
    }
    Pubkey::new_from_array(b)
}

/// Map a program error code to the `ProgramError` mollusk compares against.
fn custom(e: MirrorPoolError) -> ProgramError {
    ProgramError::Custom(e as u32)
}

/// The circuit's empty-tree root, recomputed on the host with `light-poseidon`
/// (the same Poseidon the `sol_poseidon` syscall is built on).
fn circuit_empty_root() -> [u8; 32] {
    use ark_bn254::Fr;
    use ark_ff::{BigInteger, PrimeField};
    use light_poseidon::{Poseidon, PoseidonHasher};

    let mut z = Fr::from(0u64);
    for _ in 0..mirror_pool::state::merkle::DEPTH {
        let mut h = Poseidon::<Fr>::new_circom(2).unwrap();
        z = h.hash(&[z, z]).unwrap();
    }
    let be = z.into_bigint().to_bytes_be();
    let mut out = [0u8; 32];
    out[32 - be.len()..].copy_from_slice(&be);
    out
}

/// A tiny stateful harness (the same shape `integration.rs` uses).
struct Env {
    mollusk: Mollusk,
    program_id: Pubkey,
    system_id: Pubkey,
    clock_id: Pubkey,
    accounts: HashMap<Pubkey, Account>,
}

impl Env {
    fn new() -> Self {
        std::env::set_var(
            "SBF_OUT_DIR",
            concat!(env!("CARGO_MANIFEST_DIR"), "/target/deploy"),
        );
        let program_id = Pubkey::new_unique();
        let mollusk = Mollusk::new(&program_id, "mirror_pool");
        let system_id = keyed_account_for_system_program().0;
        let clock_id = mollusk.sysvars.keyed_account_for_clock_sysvar().0;
        Env {
            mollusk,
            program_id,
            system_id,
            clock_id,
            accounts: HashMap::new(),
        }
    }

    fn fund(&mut self, key: Pubkey, lamports: u64) {
        self.accounts
            .insert(key, Account::new(lamports, 0, &self.system_id));
    }

    fn get(&self, key: &Pubkey) -> Account {
        self.accounts.get(key).cloned().unwrap_or_default()
    }

    fn warp(&mut self, slot: u64) {
        self.mollusk.warp_to_slot(slot);
    }

    fn accounts_for(&self, ix: &Instruction) -> Vec<(Pubkey, Account)> {
        let mut seen = HashSet::new();
        let mut out = Vec::new();
        for meta in &ix.accounts {
            if !seen.insert(meta.pubkey) {
                continue;
            }
            let account = if meta.pubkey == self.system_id {
                keyed_account_for_system_program().1
            } else if meta.pubkey == self.clock_id {
                self.mollusk.sysvars.keyed_account_for_clock_sysvar().1
            } else {
                self.get(&meta.pubkey)
            };
            out.push((meta.pubkey, account));
        }
        out
    }

    fn process(&mut self, ix: &Instruction, checks: &[Check]) -> InstructionResult {
        let accts = self.accounts_for(ix);
        let result = self
            .mollusk
            .process_and_validate_instruction(ix, &accts, checks);
        for (key, account) in &result.resulting_accounts {
            if *key != self.system_id && *key != self.clock_id {
                self.accounts.insert(*key, account.clone());
            }
        }
        result
    }

    fn pool_pda(&self, authority: &Pubkey) -> Pubkey {
        Pubkey::find_program_address(&[POOL_SEED, authority.as_ref()], &self.program_id).0
    }

    fn assoc_pda(&self, pool: &Pubkey, curator: &Pubkey) -> Pubkey {
        Pubkey::find_program_address(
            &[ASSOCIATION_SEED, pool.as_ref(), curator.as_ref()],
            &self.program_id,
        )
        .0
    }

    fn nf_pda(&self, pool: &Pubkey, epoch_id: u64, nf: &[u8; 32]) -> Pubkey {
        Pubkey::find_program_address(
            &[NULLIFIER_SEED, pool.as_ref(), &epoch_id.to_le_bytes(), nf],
            &self.program_id,
        )
        .0
    }

    fn init_assoc_ix(
        &self,
        assoc: &Pubkey,
        pool: &Pubkey,
        curator: &Pubkey,
        payer: &Pubkey,
    ) -> Instruction {
        Instruction {
            program_id: self.program_id,
            accounts: vec![
                AccountMeta::new(*assoc, false),
                AccountMeta::new_readonly(*pool, false),
                AccountMeta::new_readonly(*curator, true),
                AccountMeta::new(*payer, true),
                AccountMeta::new_readonly(self.system_id, false),
            ],
            data: vec![tag::INIT_ASSOCIATION],
        }
    }

    fn update_root_ix(&self, assoc: &Pubkey, curator: &Pubkey, root: &[u8; 32]) -> Instruction {
        let mut data = Vec::with_capacity(mirror_pool::wire::UPDATE_ASSOCIATION_ROOT_LEN);
        data.push(tag::UPDATE_ASSOCIATION_ROOT);
        data.extend_from_slice(root);
        Instruction {
            program_id: self.program_id,
            accounts: vec![
                AccountMeta::new(*assoc, false),
                AccountMeta::new_readonly(*curator, true),
            ],
            data,
        }
    }

    /// Build a `SettleZkAssociated` instruction from explicit proof bytes, so a
    /// test can substitute a membership proof to show it is rejected.
    #[allow(clippy::too_many_arguments)]
    fn settle_assoc_ix_with_proof(
        &self,
        pool: &Pubkey,
        authority: &Pubkey,
        nf_pda: &Pubkey,
        recipient: &Pubkey,
        assoc: &Pubkey,
        epoch_id: u64,
        amount: u64,
        proof_a: &[u8; 64],
        proof_b: &[u8; 128],
        proof_c: &[u8; 64],
        public_inputs: &[[u8; 32]; 5],
    ) -> Instruction {
        let mut data = Vec::with_capacity(mirror_pool::wire::SETTLE_ZK_ASSOCIATED_LEN);
        data.push(tag::SETTLE_ZK_ASSOCIATED);
        data.extend_from_slice(&epoch_id.to_le_bytes());
        data.extend_from_slice(&amount.to_le_bytes());
        data.extend_from_slice(proof_a);
        data.extend_from_slice(proof_b);
        data.extend_from_slice(proof_c);
        for pi in public_inputs {
            data.extend_from_slice(pi);
        }
        Instruction {
            program_id: self.program_id,
            accounts: vec![
                AccountMeta::new(*pool, false),
                AccountMeta::new(*authority, true),
                AccountMeta::new(*nf_pda, false),
                AccountMeta::new(*recipient, false),
                AccountMeta::new_readonly(self.system_id, false),
                AccountMeta::new_readonly(self.clock_id, false),
                AccountMeta::new_readonly(*assoc, false),
            ],
            data,
        }
    }

    #[allow(clippy::too_many_arguments)]
    fn settle_assoc_ix(
        &self,
        pool: &Pubkey,
        authority: &Pubkey,
        nf_pda: &Pubkey,
        recipient: &Pubkey,
        assoc: &Pubkey,
        epoch_id: u64,
        amount: u64,
        public_inputs: &[[u8; 32]; 5],
    ) -> Instruction {
        self.settle_assoc_ix_with_proof(
            pool,
            authority,
            nf_pda,
            recipient,
            assoc,
            epoch_id,
            amount,
            &fixture::PROOF_A,
            &fixture::PROOF_B,
            &fixture::PROOF_C,
            public_inputs,
        )
    }

    /// The plain `SettleZk` instruction, used only to show the two paths share a
    /// spent-set.
    #[allow(clippy::too_many_arguments)]
    fn settle_zk_ix(
        &self,
        pool: &Pubkey,
        authority: &Pubkey,
        nf_pda: &Pubkey,
        recipient: &Pubkey,
        epoch_id: u64,
        amount: u64,
        public_inputs: &[[u8; 32]; 4],
    ) -> Instruction {
        let mut data = Vec::with_capacity(mirror_pool::wire::SETTLE_ZK_LEN);
        data.push(tag::SETTLE_ZK);
        data.extend_from_slice(&epoch_id.to_le_bytes());
        data.extend_from_slice(&amount.to_le_bytes());
        data.extend_from_slice(&membership_fixture::PROOF_A);
        data.extend_from_slice(&membership_fixture::PROOF_B);
        data.extend_from_slice(&membership_fixture::PROOF_C);
        for pi in public_inputs {
            data.extend_from_slice(pi);
        }
        Instruction {
            program_id: self.program_id,
            accounts: vec![
                AccountMeta::new(*pool, false),
                AccountMeta::new(*authority, true),
                AccountMeta::new(*nf_pda, false),
                AccountMeta::new(*recipient, false),
                AccountMeta::new_readonly(self.system_id, false),
                AccountMeta::new_readonly(self.clock_id, false),
            ],
            data,
        }
    }
}

/// Hand-build an initialized Pool whose recent-root ring already contains the
/// committed association fixture's POOL root (public signal [0]), and fund it.
/// A real deposit sequence cannot reproduce the fixture's exact tree, so the test
/// injects the snapshot - the same technique `integration.rs` uses for SettleZk.
fn build_zk_pool(env: &mut Env, authority: &Pubkey, epoch_slots: u64, lamports: u64) -> Pubkey {
    let pool = env.pool_pda(authority);
    let (_, bump) = Pubkey::find_program_address(&[POOL_SEED, authority.as_ref()], &env.program_id);
    let mut data = vec![0u8; pool::LEN];
    pool::init(
        &mut data,
        epoch_slots,
        2,
        0,
        0,
        &authority.to_bytes(),
        bump,
        &circuit_empty_root(),
    )
    .unwrap();
    pool::record_root_history(&mut data, &fixture::PUBLIC_INPUTS[0]).unwrap();
    assert!(pool::is_known_root(&data, &fixture::PUBLIC_INPUTS[0]).unwrap());
    let mut account = Account::new(lamports, pool::LEN, &env.program_id);
    account.data = data;
    env.accounts.insert(pool, account);
    pool
}

/// Register a curator's association set for `pool` through the real instruction.
fn register_curator(env: &mut Env, pool: &Pubkey, curator: &Pubkey, payer: &Pubkey) -> Pubkey {
    let assoc = env.assoc_pda(pool, curator);
    let ix = env.init_assoc_ix(&assoc, pool, curator, payer);
    env.process(&ix, &[Check::success()]);
    assoc
}

/// A full happy-path setup: pool with the fixture root, a registered curator that
/// has published the fixture's association root, and a funded recipient.
fn setup_associated(env: &mut Env) -> (Pubkey, Pubkey, Pubkey, Pubkey) {
    let authority = Pubkey::new_unique();
    env.fund(authority, SOL); // pays the nullifier PDA rent
    let payer = Pubkey::new_unique();
    env.fund(payer, 10 * SOL);
    let pool = build_zk_pool(env, &authority, 10, 5 * SOL + ZK_AMOUNT);

    let curator = Pubkey::new_unique();
    env.fund(curator, SOL);
    let assoc = register_curator(env, &pool, &curator, &payer);

    // The curator publishes the fixture's association root (public signal [4]).
    let ix = env.update_root_ix(&assoc, &curator, &fixture::PUBLIC_INPUTS[4]);
    env.process(&ix, &[Check::success()]);

    let recipient = zk_recipient();
    env.fund(recipient, 0);
    (authority, pool, curator, assoc)
}

// ---------------------------------------------------------------------------
// INIT_ASSOCIATION
// ---------------------------------------------------------------------------

#[test]
fn init_association_registers_and_reinit_fails() {
    let mut env = Env::new();
    let authority = Pubkey::new_unique();
    env.fund(authority, SOL);
    let payer = Pubkey::new_unique();
    env.fund(payer, 10 * SOL);
    let pool = build_zk_pool(&mut env, &authority, 10, 5 * SOL);

    let curator = Pubkey::new_unique();
    env.fund(curator, SOL);
    let assoc = register_curator(&mut env, &pool, &curator, &payer);

    let data = env.get(&assoc).data;
    assert_eq!(env.get(&assoc).owner, env.program_id);
    assert_eq!(data.len(), association::LEN);
    assert_eq!(
        association::version(&data).unwrap(),
        association::VERSION_V1
    );
    assert_eq!(association::pool(&data).unwrap(), pool.to_bytes());
    assert_eq!(association::curator(&data).unwrap(), curator.to_bytes());
    assert_eq!(association::update_count(&data).unwrap(), 0);
    // A set with no published root vouches for nothing: every slot is the
    // sentinel and is_known_root rejects it.
    for i in 0..association::ROOT_HISTORY_SIZE {
        assert_eq!(
            association::root_history_entry(&data, i).unwrap(),
            association::EMPTY_SLOT
        );
    }
    assert!(!association::is_known_root(&data, &association::EMPTY_SLOT).unwrap());

    // Re-registering the same (pool, curator) fails closed.
    let ix = env.init_assoc_ix(&assoc, &pool, &curator, &payer);
    env.process(
        &ix,
        &[Check::err(custom(
            MirrorPoolError::AssociationAlreadyInitialized,
        ))],
    );
}

#[test]
fn init_association_is_permissionless_across_curators() {
    // Two independent curators register competing sets over the SAME pool. This
    // is the anti-censorship property: no single curator owns the compliance
    // story for a pool.
    let mut env = Env::new();
    let authority = Pubkey::new_unique();
    env.fund(authority, SOL);
    let payer = Pubkey::new_unique();
    env.fund(payer, 10 * SOL);
    let pool = build_zk_pool(&mut env, &authority, 10, 5 * SOL);

    let curator_a = Pubkey::new_unique();
    let curator_b = Pubkey::new_unique();
    env.fund(curator_a, SOL);
    env.fund(curator_b, SOL);
    let assoc_a = register_curator(&mut env, &pool, &curator_a, &payer);
    let assoc_b = register_curator(&mut env, &pool, &curator_b, &payer);

    assert_ne!(assoc_a, assoc_b, "each curator gets its own set account");
    assert_eq!(
        association::curator(&env.get(&assoc_a).data).unwrap(),
        curator_a.to_bytes()
    );
    assert_eq!(
        association::curator(&env.get(&assoc_b).data).unwrap(),
        curator_b.to_bytes()
    );
}

#[test]
fn init_association_over_a_non_pool_account_fails() {
    let mut env = Env::new();
    let payer = Pubkey::new_unique();
    env.fund(payer, 10 * SOL);
    let curator = Pubkey::new_unique();
    env.fund(curator, SOL);

    // A system-owned account that is not a pool at all.
    let fake_pool = Pubkey::new_unique();
    env.fund(fake_pool, SOL);
    let assoc = env.assoc_pda(&fake_pool, &curator);
    let ix = env.init_assoc_ix(&assoc, &fake_pool, &curator, &payer);
    env.process(
        &ix,
        &[Check::err(custom(MirrorPoolError::PoolNotInitialized))],
    );
}

#[test]
fn init_association_rejects_a_trailing_body_byte() {
    let mut env = Env::new();
    let authority = Pubkey::new_unique();
    env.fund(authority, SOL);
    let payer = Pubkey::new_unique();
    env.fund(payer, 10 * SOL);
    let pool = build_zk_pool(&mut env, &authority, 10, 5 * SOL);
    let curator = Pubkey::new_unique();
    env.fund(curator, SOL);
    let assoc = env.assoc_pda(&pool, &curator);

    let mut ix = env.init_assoc_ix(&assoc, &pool, &curator, &payer);
    ix.data.push(0); // one byte too many: fail closed, never ignore
    env.process(
        &ix,
        &[Check::err(custom(MirrorPoolError::MalformedInstruction))],
    );
}

// ---------------------------------------------------------------------------
// UPDATE_ASSOCIATION_ROOT
// ---------------------------------------------------------------------------

#[test]
fn update_association_root_publishes_and_only_curator_may() {
    let mut env = Env::new();
    let authority = Pubkey::new_unique();
    env.fund(authority, SOL);
    let payer = Pubkey::new_unique();
    env.fund(payer, 10 * SOL);
    let pool = build_zk_pool(&mut env, &authority, 10, 5 * SOL);
    let curator = Pubkey::new_unique();
    env.fund(curator, SOL);
    let assoc = register_curator(&mut env, &pool, &curator, &payer);

    let root = [9u8; 32];
    let ix = env.update_root_ix(&assoc, &curator, &root);
    env.process(&ix, &[Check::success()]);

    let data = env.get(&assoc).data;
    assert_eq!(association::update_count(&data).unwrap(), 1);
    assert!(association::is_known_root(&data, &root).unwrap());
    assert_eq!(association::root_head(&data).unwrap(), 1);

    // An imposter cannot publish, even though the account is program-owned.
    let imposter = Pubkey::new_unique();
    env.fund(imposter, SOL);
    let ix = env.update_root_ix(&assoc, &imposter, &[8u8; 32]);
    env.process(&ix, &[Check::err(custom(MirrorPoolError::Unauthorized))]);
    assert_eq!(
        association::update_count(&env.get(&assoc).data).unwrap(),
        1,
        "a rejected publish must not bump the counter"
    );
}

#[test]
fn update_association_root_refuses_the_zero_sentinel() {
    let mut env = Env::new();
    let authority = Pubkey::new_unique();
    env.fund(authority, SOL);
    let payer = Pubkey::new_unique();
    env.fund(payer, 10 * SOL);
    let pool = build_zk_pool(&mut env, &authority, 10, 5 * SOL);
    let curator = Pubkey::new_unique();
    env.fund(curator, SOL);
    let assoc = register_curator(&mut env, &pool, &curator, &payer);

    // Publishing all-zero would collide with the "unwritten slot" sentinel.
    let ix = env.update_root_ix(&assoc, &curator, &[0u8; 32]);
    env.process(
        &ix,
        &[Check::err(custom(MirrorPoolError::MalformedInstruction))],
    );
}

#[test]
fn update_association_root_on_unregistered_set_fails() {
    let mut env = Env::new();
    let authority = Pubkey::new_unique();
    env.fund(authority, SOL);
    let pool = build_zk_pool(&mut env, &authority, 10, 5 * SOL);
    let curator = Pubkey::new_unique();
    env.fund(curator, SOL);
    // Never registered: the PDA exists as an address but holds no account.
    let assoc = env.assoc_pda(&pool, &curator);

    let ix = env.update_root_ix(&assoc, &curator, &[7u8; 32]);
    env.process(
        &ix,
        &[Check::err(custom(
            MirrorPoolError::AssociationNotInitialized,
        ))],
    );
}

#[test]
fn association_root_ring_wraps_and_evicts_oldest() {
    let mut env = Env::new();
    let authority = Pubkey::new_unique();
    env.fund(authority, SOL);
    let payer = Pubkey::new_unique();
    env.fund(payer, 10 * SOL);
    let pool = build_zk_pool(&mut env, &authority, 10, 5 * SOL);
    let curator = Pubkey::new_unique();
    env.fund(curator, SOL);
    let assoc = register_curator(&mut env, &pool, &curator, &payer);

    let ring = association::ROOT_HISTORY_SIZE;
    let root_at = |i: usize| -> [u8; 32] {
        let mut r = [0u8; 32];
        r[0] = 0xA0;
        r[31] = (i + 1) as u8;
        r
    };

    // Fill the ring exactly.
    for i in 0..ring {
        let ix = env.update_root_ix(&assoc, &curator, &root_at(i));
        env.process(&ix, &[Check::success()]);
    }
    let data = env.get(&assoc).data;
    for i in 0..ring {
        assert!(
            association::is_known_root(&data, &root_at(i)).unwrap(),
            "root {i} must still be accepted while the ring is exactly full"
        );
    }
    assert_eq!(association::update_count(&data).unwrap(), ring as u64);

    // One more publication evicts the OLDEST, not an arbitrary slot.
    let ix = env.update_root_ix(&assoc, &curator, &root_at(ring));
    env.process(&ix, &[Check::success()]);
    let data = env.get(&assoc).data;
    assert!(
        !association::is_known_root(&data, &root_at(0)).unwrap(),
        "the oldest root must be evicted"
    );
    for i in 1..=ring {
        assert!(
            association::is_known_root(&data, &root_at(i)).unwrap(),
            "root {i} must survive the wrap"
        );
    }
}

// ---------------------------------------------------------------------------
// SETTLE_ZK_ASSOCIATED
// ---------------------------------------------------------------------------

#[test]
fn settle_zk_associated_accepts_fixture_and_transfers_escrow() {
    let mut env = Env::new();
    let (authority, pool, _curator, assoc) = setup_associated(&mut env);
    let recipient = zk_recipient();
    let pool_start = env.get(&pool).lamports;

    // Window for epoch 11 closes at settle_slot(11) = 12 * 10 = 120.
    env.warp(120);

    let nf = fixture::PUBLIC_INPUTS[1];
    let nf_pda = env.nf_pda(&pool, ZK_EPOCH, &nf);
    let ix = env.settle_assoc_ix(
        &pool,
        &authority,
        &nf_pda,
        &recipient,
        &assoc,
        ZK_EPOCH,
        ZK_AMOUNT,
        &fixture::PUBLIC_INPUTS,
    );
    env.process(&ix, &[Check::success()]);

    assert_eq!(
        env.get(&recipient).lamports,
        ZK_AMOUNT,
        "escrow must be transferred to the fresh recipient"
    );
    assert_eq!(env.get(&pool).lamports, pool_start - ZK_AMOUNT);
    let nf_acct = env.get(&nf_pda);
    assert_eq!(nf_acct.owner, env.program_id);
    assert_eq!(nf_acct.data.len(), nullifier::LEN);
    assert_eq!(nf_acct.data[0], nullifier::SPENT);
}

#[test]
fn settle_zk_associated_rejects_unpublished_association_root() {
    // The curator registered but never published the fixture's root. The proof is
    // perfectly valid; the settlement must still be refused because no curator
    // has vouched for it.
    let mut env = Env::new();
    let authority = Pubkey::new_unique();
    env.fund(authority, SOL);
    let payer = Pubkey::new_unique();
    env.fund(payer, 10 * SOL);
    let pool_start = 5 * SOL + ZK_AMOUNT;
    let pool = build_zk_pool(&mut env, &authority, 10, pool_start);
    let curator = Pubkey::new_unique();
    env.fund(curator, SOL);
    let assoc = register_curator(&mut env, &pool, &curator, &payer);
    // Publish a DIFFERENT root, so the ring is non-empty but lacks ours.
    let ix = env.update_root_ix(&assoc, &curator, &[3u8; 32]);
    env.process(&ix, &[Check::success()]);

    let recipient = zk_recipient();
    env.fund(recipient, 0);
    env.warp(120);

    let nf = fixture::PUBLIC_INPUTS[1];
    let nf_pda = env.nf_pda(&pool, ZK_EPOCH, &nf);
    let ix = env.settle_assoc_ix(
        &pool,
        &authority,
        &nf_pda,
        &recipient,
        &assoc,
        ZK_EPOCH,
        ZK_AMOUNT,
        &fixture::PUBLIC_INPUTS,
    );
    env.process(
        &ix,
        &[Check::err(custom(MirrorPoolError::AssociationRootNotKnown))],
    );

    // Fail closed: nothing moved, no nullifier created.
    assert_eq!(env.get(&recipient).lamports, 0);
    assert_eq!(env.get(&pool).lamports, pool_start);
    assert_eq!(env.get(&nf_pda).owner, Pubkey::default());
}

#[test]
fn settle_zk_associated_rejects_stale_aged_out_association_root() {
    // The curator DID publish the fixture's root, then republished enough times
    // to push it out of the ring. A proof against the aged-out root must fail.
    // This is the deliberate cost of the history window, pinned by a test.
    let mut env = Env::new();
    let (authority, pool, curator, assoc) = setup_associated(&mut env);
    let recipient = zk_recipient();
    let pool_start = env.get(&pool).lamports;

    for i in 0..association::ROOT_HISTORY_SIZE {
        let mut r = [0u8; 32];
        r[0] = 0xB0;
        r[31] = (i + 1) as u8;
        let ix = env.update_root_ix(&assoc, &curator, &r);
        env.process(&ix, &[Check::success()]);
    }
    assert!(
        !association::is_known_root(&env.get(&assoc).data, &fixture::PUBLIC_INPUTS[4]).unwrap(),
        "the fixture root must have aged out of the ring"
    );

    env.warp(120);
    let nf = fixture::PUBLIC_INPUTS[1];
    let nf_pda = env.nf_pda(&pool, ZK_EPOCH, &nf);
    let ix = env.settle_assoc_ix(
        &pool,
        &authority,
        &nf_pda,
        &recipient,
        &assoc,
        ZK_EPOCH,
        ZK_AMOUNT,
        &fixture::PUBLIC_INPUTS,
    );
    env.process(
        &ix,
        &[Check::err(custom(MirrorPoolError::AssociationRootNotKnown))],
    );
    assert_eq!(env.get(&pool).lamports, pool_start);
    assert_eq!(env.get(&recipient).lamports, 0);
}

#[test]
fn settle_zk_associated_rejects_known_root_that_the_proof_does_not_commit_to() {
    // The submitted associationRoot IS in the curator's ring, so the cheap ring
    // check passes - but the PROOF commits to a different association root, so
    // Groth16 must reject. Without this, the ring check alone would be theatre.
    let mut env = Env::new();
    let (authority, pool, curator, assoc) = setup_associated(&mut env);
    let recipient = zk_recipient();
    let pool_start = env.get(&pool).lamports;

    let other_root = [0x5Au8; 32];
    let ix = env.update_root_ix(&assoc, &curator, &other_root);
    env.process(&ix, &[Check::success()]);
    assert!(association::is_known_root(&env.get(&assoc).data, &other_root).unwrap());

    env.warp(120);
    let mut public = fixture::PUBLIC_INPUTS;
    public[4] = other_root; // known on-chain, but not what the proof proves

    let nf = public[1];
    let nf_pda = env.nf_pda(&pool, ZK_EPOCH, &nf);
    let ix = env.settle_assoc_ix(
        &pool, &authority, &nf_pda, &recipient, &assoc, ZK_EPOCH, ZK_AMOUNT, &public,
    );
    env.process(
        &ix,
        &[Check::err(custom(MirrorPoolError::ProofVerificationFailed))],
    );
    assert_eq!(env.get(&pool).lamports, pool_start);
    assert_eq!(env.get(&recipient).lamports, 0);
    assert_eq!(env.get(&nf_pda).owner, Pubkey::default());
}

#[test]
fn settle_zk_associated_rejects_a_set_from_a_different_pool() {
    // A curator's attestation is scoped to the pool it registered against. Passing
    // another pool's set must not launder an attestation across pools.
    let mut env = Env::new();
    let (authority, pool, _curator, _assoc) = setup_associated(&mut env);
    let recipient = zk_recipient();
    let pool_start = env.get(&pool).lamports;

    // A second pool with its own curator, whose set publishes the SAME root.
    let other_authority = Pubkey::new_unique();
    env.fund(other_authority, SOL);
    let payer = Pubkey::new_unique();
    env.fund(payer, 10 * SOL);
    let other_pool = build_zk_pool(&mut env, &other_authority, 10, 5 * SOL);
    let other_curator = Pubkey::new_unique();
    env.fund(other_curator, SOL);
    let other_assoc = register_curator(&mut env, &other_pool, &other_curator, &payer);
    let ix = env.update_root_ix(&other_assoc, &other_curator, &fixture::PUBLIC_INPUTS[4]);
    env.process(&ix, &[Check::success()]);

    env.warp(120);
    let nf = fixture::PUBLIC_INPUTS[1];
    let nf_pda = env.nf_pda(&pool, ZK_EPOCH, &nf);
    let ix = env.settle_assoc_ix(
        &pool,
        &authority,
        &nf_pda,
        &recipient,
        &other_assoc, // set for a DIFFERENT pool
        ZK_EPOCH,
        ZK_AMOUNT,
        &fixture::PUBLIC_INPUTS,
    );
    env.process(
        &ix,
        &[Check::err(custom(MirrorPoolError::AssociationPoolMismatch))],
    );
    assert_eq!(env.get(&pool).lamports, pool_start);
}

#[test]
fn settle_zk_associated_rejects_a_forged_association_account() {
    // A caller hand-builds a program-owned account that parses as an association
    // set naming this pool and containing the root they want, but which is NOT at
    // the derived PDA. The PDA re-derivation must catch it; otherwise anyone
    // could self-attest.
    let mut env = Env::new();
    let (authority, pool, _curator, _assoc) = setup_associated(&mut env);
    let recipient = zk_recipient();
    let pool_start = env.get(&pool).lamports;

    let forged_key = Pubkey::new_unique();
    let fake_curator = Pubkey::new_unique();
    let mut data = vec![0u8; association::LEN];
    association::init(&mut data, &pool.to_bytes(), &fake_curator.to_bytes(), 255).unwrap();
    association::publish_root(&mut data, &fixture::PUBLIC_INPUTS[4]).unwrap();
    let mut account = Account::new(SOL, association::LEN, &env.program_id);
    account.data = data;
    env.accounts.insert(forged_key, account);

    env.warp(120);
    let nf = fixture::PUBLIC_INPUTS[1];
    let nf_pda = env.nf_pda(&pool, ZK_EPOCH, &nf);
    let ix = env.settle_assoc_ix(
        &pool,
        &authority,
        &nf_pda,
        &recipient,
        &forged_key,
        ZK_EPOCH,
        ZK_AMOUNT,
        &fixture::PUBLIC_INPUTS,
    );
    env.process(&ix, &[Check::err(custom(MirrorPoolError::InvalidPda))]);
    assert_eq!(env.get(&pool).lamports, pool_start);
    assert_eq!(env.get(&recipient).lamports, 0);
}

#[test]
fn settle_zk_associated_rejects_a_system_owned_association_account() {
    let mut env = Env::new();
    let (authority, pool, curator, _assoc) = setup_associated(&mut env);
    let recipient = zk_recipient();

    // The right PDA address, but an account this program does not own.
    let assoc_addr = env.assoc_pda(&pool, &curator);
    env.fund(assoc_addr, SOL); // system-owned, zero data

    env.warp(120);
    let nf = fixture::PUBLIC_INPUTS[1];
    let nf_pda = env.nf_pda(&pool, ZK_EPOCH, &nf);
    let ix = env.settle_assoc_ix(
        &pool,
        &authority,
        &nf_pda,
        &recipient,
        &assoc_addr,
        ZK_EPOCH,
        ZK_AMOUNT,
        &fixture::PUBLIC_INPUTS,
    );
    env.process(
        &ix,
        &[Check::err(custom(
            MirrorPoolError::AssociationNotInitialized,
        ))],
    );
}

#[test]
fn settle_zk_associated_rejects_a_membership_proof() {
    // The association instruction verifies against a DIFFERENT verifying key, so
    // a valid 4-input membership proof (padded with the association root as the
    // 5th input) can never satisfy it. If it could, "association required" would
    // be trivially bypassable.
    let mut env = Env::new();
    let (authority, pool, _curator, assoc) = setup_associated(&mut env);
    let recipient = zk_recipient();
    let pool_start = env.get(&pool).lamports;

    env.warp(120);
    let public: [[u8; 32]; 5] = [
        fixture::PUBLIC_INPUTS[0],
        fixture::PUBLIC_INPUTS[1],
        fixture::PUBLIC_INPUTS[2],
        fixture::PUBLIC_INPUTS[3],
        fixture::PUBLIC_INPUTS[4],
    ];
    let nf_pda = env.nf_pda(&pool, ZK_EPOCH, &public[1]);
    let ix = env.settle_assoc_ix_with_proof(
        &pool,
        &authority,
        &nf_pda,
        &recipient,
        &assoc,
        ZK_EPOCH,
        ZK_AMOUNT,
        &membership_fixture::PROOF_A,
        &membership_fixture::PROOF_B,
        &membership_fixture::PROOF_C,
        &public,
    );
    env.process(
        &ix,
        &[Check::err(custom(MirrorPoolError::ProofVerificationFailed))],
    );
    assert_eq!(env.get(&pool).lamports, pool_start);
}

#[test]
fn settle_zk_associated_replay_fails_nullifier_spent() {
    let mut env = Env::new();
    let (authority, pool, _curator, assoc) = setup_associated(&mut env);
    let recipient = zk_recipient();
    env.warp(120);

    let nf = fixture::PUBLIC_INPUTS[1];
    let nf_pda = env.nf_pda(&pool, ZK_EPOCH, &nf);
    let ix = env.settle_assoc_ix(
        &pool,
        &authority,
        &nf_pda,
        &recipient,
        &assoc,
        ZK_EPOCH,
        ZK_AMOUNT,
        &fixture::PUBLIC_INPUTS,
    );
    env.process(&ix, &[Check::success()]);
    let ix2 = env.settle_assoc_ix(
        &pool,
        &authority,
        &nf_pda,
        &recipient,
        &assoc,
        ZK_EPOCH,
        ZK_AMOUNT,
        &fixture::PUBLIC_INPUTS,
    );
    env.process(&ix2, &[Check::err(custom(MirrorPoolError::NullifierSpent))]);
}

#[test]
fn association_and_plain_settle_share_one_spent_set() {
    // Settling WITH an attestation must burn the nullifier for the plain path
    // too. Otherwise a user could take the escrow twice: once "compliantly" and
    // once not. Both paths derive the nullifier PDA from the same seeds, and this
    // pins it.
    let mut env = Env::new();
    let (authority, pool, _curator, assoc) = setup_associated(&mut env);
    let recipient = zk_recipient();
    env.warp(120);

    let nf = fixture::PUBLIC_INPUTS[1];
    let nf_pda = env.nf_pda(&pool, ZK_EPOCH, &nf);
    let ix = env.settle_assoc_ix(
        &pool,
        &authority,
        &nf_pda,
        &recipient,
        &assoc,
        ZK_EPOCH,
        ZK_AMOUNT,
        &fixture::PUBLIC_INPUTS,
    );
    env.process(&ix, &[Check::success()]);

    // The PLAIN SettleZk path, same epoch + nullifier, must now be blocked. It is
    // stopped at the nullifier check, BEFORE any proof verification, which is the
    // ordering that makes the shared spent-set load-bearing.
    let plain_public: [[u8; 32]; 4] = [
        fixture::PUBLIC_INPUTS[0],
        fixture::PUBLIC_INPUTS[1],
        fixture::PUBLIC_INPUTS[2],
        fixture::PUBLIC_INPUTS[3],
    ];
    let ix = env.settle_zk_ix(
        &pool,
        &authority,
        &nf_pda,
        &recipient,
        ZK_EPOCH,
        ZK_AMOUNT,
        &plain_public,
    );
    env.process(&ix, &[Check::err(custom(MirrorPoolError::NullifierSpent))]);
}

#[test]
fn settle_zk_associated_before_window_closes_fails() {
    let mut env = Env::new();
    let (authority, pool, _curator, assoc) = setup_associated(&mut env);
    let recipient = zk_recipient();
    // settle_slot(11) = 120; still inside the window at slot 90.
    env.warp(90);

    let nf = fixture::PUBLIC_INPUTS[1];
    let nf_pda = env.nf_pda(&pool, ZK_EPOCH, &nf);
    let ix = env.settle_assoc_ix(
        &pool,
        &authority,
        &nf_pda,
        &recipient,
        &assoc,
        ZK_EPOCH,
        ZK_AMOUNT,
        &fixture::PUBLIC_INPUTS,
    );
    env.process(&ix, &[Check::err(custom(MirrorPoolError::EpochNotClosed))]);
}

#[test]
fn settle_zk_associated_by_non_authority_fails() {
    let mut env = Env::new();
    let (_authority, pool, _curator, assoc) = setup_associated(&mut env);
    let recipient = zk_recipient();
    env.warp(120);

    let imposter = Pubkey::new_unique();
    env.fund(imposter, SOL);
    let nf = fixture::PUBLIC_INPUTS[1];
    let nf_pda = env.nf_pda(&pool, ZK_EPOCH, &nf);
    let ix = env.settle_assoc_ix(
        &pool,
        &imposter,
        &nf_pda,
        &recipient,
        &assoc,
        ZK_EPOCH,
        ZK_AMOUNT,
        &fixture::PUBLIC_INPUTS,
    );
    env.process(&ix, &[Check::err(custom(MirrorPoolError::Unauthorized))]);
}

#[test]
fn settle_zk_associated_wrong_recipient_action_hash_mismatch() {
    let mut env = Env::new();
    let (authority, pool, _curator, assoc) = setup_associated(&mut env);
    let pool_start = env.get(&pool).lamports;
    let wrong_recipient = Pubkey::new_unique();
    env.fund(wrong_recipient, 0);
    env.warp(120);

    let nf = fixture::PUBLIC_INPUTS[1];
    let nf_pda = env.nf_pda(&pool, ZK_EPOCH, &nf);
    let ix = env.settle_assoc_ix(
        &pool,
        &authority,
        &nf_pda,
        &wrong_recipient,
        &assoc,
        ZK_EPOCH,
        ZK_AMOUNT,
        &fixture::PUBLIC_INPUTS,
    );
    env.process(
        &ix,
        &[Check::err(custom(MirrorPoolError::ActionHashMismatch))],
    );
    assert_eq!(env.get(&wrong_recipient).lamports, 0, "no redirect");
    assert_eq!(env.get(&pool).lamports, pool_start);
}

#[test]
fn settle_zk_associated_rejects_a_short_body() {
    let mut env = Env::new();
    let (authority, pool, _curator, assoc) = setup_associated(&mut env);
    let recipient = zk_recipient();
    env.warp(120);

    let nf = fixture::PUBLIC_INPUTS[1];
    let nf_pda = env.nf_pda(&pool, ZK_EPOCH, &nf);
    let mut ix = env.settle_assoc_ix(
        &pool,
        &authority,
        &nf_pda,
        &recipient,
        &assoc,
        ZK_EPOCH,
        ZK_AMOUNT,
        &fixture::PUBLIC_INPUTS,
    );
    // Drop the trailing association root: a SettleZk-shaped body must not be
    // silently accepted by the association handler.
    assert_eq!(ix.data.len(), mirror_pool::wire::SETTLE_ZK_ASSOCIATED_LEN);
    ix.data.truncate(mirror_pool::wire::SETTLE_ZK_LEN);
    env.process(
        &ix,
        &[Check::err(custom(MirrorPoolError::MalformedInstruction))],
    );
}

#[test]
fn settle_zk_associated_unknown_pool_root_fails() {
    // The association half can be perfect and the POOL half still has to hold.
    let mut env = Env::new();
    let authority = Pubkey::new_unique();
    env.fund(authority, SOL);
    let payer = Pubkey::new_unique();
    env.fund(payer, 10 * SOL);
    let pool_start = 5 * SOL + ZK_AMOUNT;

    // A pool whose ring does NOT contain the fixture's pool root.
    let pool = env.pool_pda(&authority);
    let (_, bump) = Pubkey::find_program_address(&[POOL_SEED, authority.as_ref()], &env.program_id);
    let mut data = vec![0u8; pool::LEN];
    pool::init(
        &mut data,
        10,
        2,
        0,
        0,
        &authority.to_bytes(),
        bump,
        &circuit_empty_root(),
    )
    .unwrap();
    let mut account = Account::new(pool_start, pool::LEN, &env.program_id);
    account.data = data;
    env.accounts.insert(pool, account);

    let curator = Pubkey::new_unique();
    env.fund(curator, SOL);
    let assoc = register_curator(&mut env, &pool, &curator, &payer);
    let ix = env.update_root_ix(&assoc, &curator, &fixture::PUBLIC_INPUTS[4]);
    env.process(&ix, &[Check::success()]);

    let recipient = zk_recipient();
    env.fund(recipient, 0);
    env.warp(120);

    let nf = fixture::PUBLIC_INPUTS[1];
    let nf_pda = env.nf_pda(&pool, ZK_EPOCH, &nf);
    let ix = env.settle_assoc_ix(
        &pool,
        &authority,
        &nf_pda,
        &recipient,
        &assoc,
        ZK_EPOCH,
        ZK_AMOUNT,
        &fixture::PUBLIC_INPUTS,
    );
    env.process(&ix, &[Check::err(custom(MirrorPoolError::RootNotKnown))]);
}
