//! Integration tests for the mirror-pool on-chain program.
//!
//! These load the COMPILED SBF program into mollusk's in-process SVM and drive
//! real instructions, so run `cargo build-sbf` first (the DoD build step). The
//! `.so` is located via `SBF_OUT_DIR`, which each test sets to this crate's
//! `target/deploy` so the tests are runnable regardless of the working
//! directory.
//!
//! Coverage:
//!  - INIT_POOL creates a v1 pool; re-init fails (PoolAlreadyInitialized).
//!  - COMMIT bumps the epoch commit count, the pool commitment count, and the
//!    accumulator root; the entry fee lands in the pool.
//!  - COMMIT of varied, non-trivial leaves (1, `r - 1`, a zero leaf at a
//!    non-zero index, fixed pseudo-random vectors) reproduces a host-recomputed
//!    frontier root and every frontier sibling, step by step.
//!  - The recent-root ring wraps after `ROOT_HISTORY_SIZE` commits and evicts
//!    the oldest root, not an arbitrary one.
//!  - SETTLE_EPOCH fails closed before the window closes (EpochNotClosed), below
//!    the k-floor (BelowKFloor), and for a non-authority signer (Unauthorized).
//!  - Happy path: window closed + count >= k_floor settles, creates the
//!    nullifier PDAs, and marks the epoch settled; a second settle fails
//!    (EpochAlreadySettled) and a duplicate nullifier fails (NullifierSpent).

use std::collections::{HashMap, HashSet};

use mollusk_svm::{
    program::keyed_account_for_system_program,
    result::{Check, InstructionResult},
    Mollusk,
};
use solana_account::Account;
use solana_instruction::{AccountMeta, Instruction};
use solana_program_error::ProgramError;
use solana_pubkey::Pubkey;

use mirror_pool::{
    pda::{DWELL_SEED, EPOCH_SEED, NULLIFIER_SEED, POOL_SEED},
    state::{epoch, nullifier, participant, pool},
    wire::tag,
    MirrorPoolError,
};

const SOL: u64 = 1_000_000_000;

/// The committed, known-good membership proof + public inputs (generated by
/// `circuits/build.sh`, validated against groth16-solana 0.2.0). PUBLIC_INPUTS is
/// `[root, nullifierHash, actionHash, epoch]`. Included directly so the ZK tests
/// drive the exact bytes the on-chain verifier consumes.
mod fixture {
    include!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../circuits/artifacts/proof_fixture.rs"
    ));
}

/// Host-side reference frontier accumulator (`poseidon2` + `HostFrontier`), used
/// to recompute the root the on-chain accumulator must produce. Read the header
/// of the included file for what this equivalence does and does not prove.
mod host {
    include!("fixtures/host_frontier.rs");
}

/// The fixture's epoch (public signal [3] = 7).
const ZK_EPOCH: u64 = 7;
/// The escrow amount bound into the fixture's actionHash (see gen_fixture.js).
const ZK_AMOUNT: u64 = 250_000_000;

/// The fresh recipient bound into the fixture's actionHash: bytes 0x01..0x20.
/// `transfer_action_hash(recipient, amount)` over these equals the fixture's
/// actionHash (public signal [2]), which the on-chain SETTLE_ZK recomputes.
fn zk_recipient() -> Pubkey {
    let mut b = [0u8; 32];
    for (i, x) in b.iter_mut().enumerate() {
        *x = (i + 1) as u8;
    }
    Pubkey::new_from_array(b)
}

/// Map a program error code to the `ProgramError` mollusk compares against.
fn custom(e: MirrorPoolError) -> ProgramError {
    ProgramError::Custom(e as u32)
}

/// Shared helpers for the write-once, digest-pinned verifying-key registry (see
/// `fixtures/vk_install.rs`). Every settle path now reads its verifying key from
/// a registry account, so every environment installs one first.
#[allow(dead_code)]
mod vk_fixture {
    include!("fixtures/vk_install.rs");
}

/// A tiny stateful harness: owns the Mollusk instance, a persistent account
/// map, and the slot clock. Resulting accounts are written back after every
/// successful instruction so flows (init -> commit -> settle) compose.
struct Env {
    mollusk: Mollusk,
    program_id: Pubkey,
    system_id: Pubkey,
    clock_id: Pubkey,
    accounts: HashMap<Pubkey, Account>,
}

impl Env {
    fn new() -> Self {
        // Point mollusk at the compiled program regardless of cwd.
        std::env::set_var(
            "SBF_OUT_DIR",
            concat!(env!("CARGO_MANIFEST_DIR"), "/target/deploy"),
        );
        let program_id = Pubkey::new_unique();
        let mollusk = Mollusk::new(&program_id, "mirror_pool");
        let system_id = keyed_account_for_system_program().0;
        let clock_id = mollusk.sysvars.keyed_account_for_clock_sysvar().0;
        let mut env = Env {
            mollusk,
            program_id,
            system_id,
            clock_id,
            accounts: HashMap::new(),
        };
        // Every verifying instruction reads its key from a registry account, so
        // every environment installs the pinned key(s) it needs up front.
        env.install_vk(mirror_pool::wire::CIRCUIT_MEMBERSHIP);
        env
    }

    fn fund(&mut self, key: Pubkey, lamports: u64) {
        self.accounts
            .insert(key, Account::new(lamports, 0, &self.system_id));
    }

    /// Canonical PDA of a circuit's write-once verifying-key registry.
    fn vk_registry_pda(&self, circuit_id: u8) -> Pubkey {
        vk_fixture::vk_registry_pda(&self.program_id, circuit_id)
    }

    /// Install a circuit's pinned verifying key through the REAL `INIT_VK`
    /// instruction, so every settle test also exercises the install path.
    fn install_vk(&mut self, circuit_id: u8) -> Pubkey {
        let payer = Pubkey::new_unique();
        self.fund(payer, SOL);
        let vk = vk_fixture::canonical_vk(circuit_id);
        let ix = vk_fixture::init_vk_ix(&self.program_id, &self.system_id, &payer, circuit_id, &vk);
        self.process(&ix, &[Check::success()]);
        self.vk_registry_pda(circuit_id)
    }

    fn get(&self, key: &Pubkey) -> Account {
        self.accounts.get(key).cloned().unwrap_or_default()
    }

    fn warp(&mut self, slot: u64) {
        self.mollusk.warp_to_slot(slot);
    }

    /// Build the deduplicated `(pubkey, account)` list an instruction needs,
    /// sourcing sysvar/builtin accounts fresh and everything else from the map.
    fn accounts_for(&self, ix: &Instruction) -> Vec<(Pubkey, Account)> {
        let mut seen = HashSet::new();
        let mut out = Vec::new();
        for meta in &ix.accounts {
            if !seen.insert(meta.pubkey) {
                continue;
            }
            let account = if meta.pubkey == self.system_id {
                keyed_account_for_system_program().1
            } else if meta.pubkey == self.clock_id {
                self.mollusk.sysvars.keyed_account_for_clock_sysvar().1
            } else {
                self.get(&meta.pubkey)
            };
            out.push((meta.pubkey, account));
        }
        out
    }

    fn process(&mut self, ix: &Instruction, checks: &[Check]) -> InstructionResult {
        let accts = self.accounts_for(ix);
        let result = self
            .mollusk
            .process_and_validate_instruction(ix, &accts, checks);
        for (key, account) in &result.resulting_accounts {
            if *key != self.system_id && *key != self.clock_id {
                self.accounts.insert(*key, account.clone());
            }
        }
        result
    }

    fn pool_pda(&self, authority: &Pubkey) -> Pubkey {
        Pubkey::find_program_address(&[POOL_SEED, authority.as_ref()], &self.program_id).0
    }

    fn epoch_pda(&self, pool: &Pubkey, epoch_id: u64) -> Pubkey {
        Pubkey::find_program_address(
            &[EPOCH_SEED, pool.as_ref(), &epoch_id.to_le_bytes()],
            &self.program_id,
        )
        .0
    }

    fn nf_pda(&self, pool: &Pubkey, epoch_id: u64, nf: &[u8; 32]) -> Pubkey {
        Pubkey::find_program_address(
            &[NULLIFIER_SEED, pool.as_ref(), &epoch_id.to_le_bytes(), nf],
            &self.program_id,
        )
        .0
    }

    fn dwell_pda(&self, pool: &Pubkey, participant: &Pubkey) -> Pubkey {
        Pubkey::find_program_address(
            &[DWELL_SEED, pool.as_ref(), participant.as_ref()],
            &self.program_id,
        )
        .0
    }

    #[allow(clippy::too_many_arguments)]
    fn init_ix(
        &self,
        pool: &Pubkey,
        authority: &Pubkey,
        payer: &Pubkey,
        epoch_slots: u64,
        k_floor: u32,
        entry_fee: u64,
        reward_bps: u16,
        zk_denomination: u64,
    ) -> Instruction {
        let mut data = Vec::with_capacity(mirror_pool::wire::INIT_POOL_LEN);
        data.push(tag::INIT_POOL);
        data.extend_from_slice(&epoch_slots.to_le_bytes());
        data.extend_from_slice(&k_floor.to_le_bytes());
        data.extend_from_slice(&entry_fee.to_le_bytes());
        data.extend_from_slice(&reward_bps.to_le_bytes());
        data.extend_from_slice(&zk_denomination.to_le_bytes());
        Instruction {
            program_id: self.program_id,
            accounts: vec![
                AccountMeta::new(*pool, false),
                AccountMeta::new_readonly(*authority, true),
                AccountMeta::new(*payer, true),
                AccountMeta::new_readonly(self.system_id, false),
            ],
            data,
        }
    }

    fn commit_ix(
        &self,
        pool: &Pubkey,
        epoch_acct: &Pubkey,
        participant: &Pubkey,
        commitment: &[u8; 32],
    ) -> Instruction {
        let mut data = Vec::with_capacity(mirror_pool::wire::COMMIT_LEN);
        data.push(tag::COMMIT);
        data.extend_from_slice(commitment);
        Instruction {
            program_id: self.program_id,
            accounts: vec![
                AccountMeta::new(*pool, false),
                AccountMeta::new(*epoch_acct, false),
                AccountMeta::new(*participant, true),
                AccountMeta::new_readonly(self.system_id, false),
                AccountMeta::new_readonly(self.clock_id, false),
            ],
            data,
        }
    }

    fn commit_deposit_ix(
        &self,
        pool: &Pubkey,
        epoch_acct: &Pubkey,
        depositor: &Pubkey,
        commitment: &[u8; 32],
        amount: u64,
    ) -> Instruction {
        let mut data = Vec::with_capacity(mirror_pool::wire::COMMIT_DEPOSIT_LEN);
        data.push(tag::COMMIT_DEPOSIT);
        data.extend_from_slice(commitment);
        data.extend_from_slice(&amount.to_le_bytes());
        Instruction {
            program_id: self.program_id,
            accounts: vec![
                AccountMeta::new(*pool, false),
                AccountMeta::new(*epoch_acct, false),
                AccountMeta::new(*depositor, true),
                AccountMeta::new_readonly(self.system_id, false),
                AccountMeta::new_readonly(self.clock_id, false),
            ],
            data,
        }
    }

    /// COMMIT with the optional Dwell PDA appended (crowd-path incentive).
    fn commit_with_dwell_ix(
        &self,
        pool: &Pubkey,
        epoch_acct: &Pubkey,
        participant: &Pubkey,
        dwell: &Pubkey,
        commitment: &[u8; 32],
    ) -> Instruction {
        let mut data = Vec::with_capacity(mirror_pool::wire::COMMIT_LEN);
        data.push(tag::COMMIT);
        data.extend_from_slice(commitment);
        Instruction {
            program_id: self.program_id,
            accounts: vec![
                AccountMeta::new(*pool, false),
                AccountMeta::new(*epoch_acct, false),
                AccountMeta::new(*participant, true),
                AccountMeta::new_readonly(self.system_id, false),
                AccountMeta::new_readonly(self.clock_id, false),
                AccountMeta::new(*dwell, false),
            ],
            data,
        }
    }

    fn claim_reward_ix(&self, pool: &Pubkey, participant: &Pubkey, dwell: &Pubkey) -> Instruction {
        Instruction {
            program_id: self.program_id,
            accounts: vec![
                AccountMeta::new(*pool, false),
                AccountMeta::new(*participant, true),
                AccountMeta::new(*dwell, false),
            ],
            data: vec![tag::CLAIM_REWARD],
        }
    }

    #[allow(clippy::too_many_arguments)]
    fn settle_zk_ix(
        &self,
        pool: &Pubkey,
        authority: &Pubkey,
        nf_pda: &Pubkey,
        recipient: &Pubkey,
        epoch_id: u64,
        amount: u64,
        public_inputs: &[[u8; 32]; 4],
    ) -> Instruction {
        let mut data = Vec::with_capacity(mirror_pool::wire::SETTLE_ZK_LEN);
        data.push(tag::SETTLE_ZK);
        data.extend_from_slice(&epoch_id.to_le_bytes());
        data.extend_from_slice(&amount.to_le_bytes());
        data.extend_from_slice(&fixture::PROOF_A);
        data.extend_from_slice(&fixture::PROOF_B);
        data.extend_from_slice(&fixture::PROOF_C);
        for pi in public_inputs {
            data.extend_from_slice(pi);
        }
        Instruction {
            program_id: self.program_id,
            accounts: vec![
                AccountMeta::new(*pool, false),
                AccountMeta::new(*authority, true),
                AccountMeta::new(*nf_pda, false),
                AccountMeta::new(*recipient, false),
                AccountMeta::new_readonly(self.system_id, false),
                AccountMeta::new_readonly(self.clock_id, false),
                // The write-once, digest-pinned MEMBERSHIP verifying key.
                AccountMeta::new_readonly(
                    self.vk_registry_pda(mirror_pool::wire::CIRCUIT_MEMBERSHIP),
                    false,
                ),
            ],
            data,
        }
    }

    #[allow(clippy::too_many_arguments)]
    fn settle_ix(
        &self,
        pool: &Pubkey,
        epoch_acct: &Pubkey,
        authority: &Pubkey,
        nf_pdas: &[Pubkey],
        nullifiers: &[[u8; 32]],
        payer: &Pubkey,
        epoch_id: u64,
    ) -> Instruction {
        let mut data =
            Vec::with_capacity(mirror_pool::wire::SETTLE_HEADER_LEN + nullifiers.len() * 32);
        data.push(tag::SETTLE_EPOCH);
        data.extend_from_slice(&epoch_id.to_le_bytes());
        data.extend_from_slice(&(nullifiers.len() as u32).to_le_bytes());
        for nf in nullifiers {
            data.extend_from_slice(nf);
        }
        let mut accounts = vec![
            AccountMeta::new(*pool, false),
            AccountMeta::new(*epoch_acct, false),
            AccountMeta::new_readonly(*authority, true),
        ];
        for nf in nf_pdas {
            accounts.push(AccountMeta::new(*nf, false));
        }
        accounts.push(AccountMeta::new(*payer, true));
        accounts.push(AccountMeta::new_readonly(self.system_id, false));
        accounts.push(AccountMeta::new_readonly(self.clock_id, false));
        Instruction {
            program_id: self.program_id,
            accounts,
            data,
        }
    }
}

/// Init a pool and return (authority, payer, pool_pda). `payer` is well funded.
/// Defaults `reward_bps` to 0 (reward pool disabled) so the pre-incentive tests
/// are unchanged.
fn init_pool(
    env: &mut Env,
    epoch_slots: u64,
    k_floor: u32,
    entry_fee: u64,
) -> (Pubkey, Pubkey, Pubkey) {
    init_pool_with_reward(env, epoch_slots, k_floor, entry_fee, 0)
}

/// Init a pool with an explicit `reward_bps` entry-fee split. `zk_denomination`
/// defaults to [`ZK_AMOUNT`], the size the committed ZK fixture binds, so the
/// ZK tests can deposit and settle without restating it.
fn init_pool_with_reward(
    env: &mut Env,
    epoch_slots: u64,
    k_floor: u32,
    entry_fee: u64,
    reward_bps: u16,
) -> (Pubkey, Pubkey, Pubkey) {
    init_pool_full(env, epoch_slots, k_floor, entry_fee, reward_bps, ZK_AMOUNT)
}

/// Init a pool with every parameter spelled out, including the fixed ZK escrow
/// denomination.
fn init_pool_full(
    env: &mut Env,
    epoch_slots: u64,
    k_floor: u32,
    entry_fee: u64,
    reward_bps: u16,
    zk_denomination: u64,
) -> (Pubkey, Pubkey, Pubkey) {
    let authority = Pubkey::new_unique();
    let payer = Pubkey::new_unique();
    env.fund(payer, 100 * SOL);
    // The authority is only a signer here; give it a home account.
    env.fund(authority, SOL);
    let pool = env.pool_pda(&authority);

    let ix = env.init_ix(
        &pool,
        &authority,
        &payer,
        epoch_slots,
        k_floor,
        entry_fee,
        reward_bps,
        zk_denomination,
    );
    env.process(&ix, &[Check::success()]);
    (authority, payer, pool)
}

#[test]
fn init_pool_creates_v1_and_reinit_fails() {
    let mut env = Env::new();
    let (authority, payer, pool) = init_pool(&mut env, 10, 3, 5_000);

    let acct = env.get(&pool);
    assert_eq!(acct.owner, env.program_id, "pool must be program-owned");
    assert_eq!(acct.data.len(), pool::LEN, "pool must be exactly pool::LEN");
    assert_eq!(pool::version(&acct.data).unwrap(), pool::VERSION_V1);
    assert_eq!(pool::epoch_slots(&acct.data).unwrap(), 10);
    assert_eq!(pool::k_floor(&acct.data).unwrap(), 3);
    assert_eq!(pool::entry_fee(&acct.data).unwrap(), 5_000);
    assert_eq!(pool::reward_bps(&acct.data).unwrap(), 0);
    assert_eq!(pool::reward_pool_lamports(&acct.data).unwrap(), 0);
    assert_eq!(pool::total_unclaimed_dwell(&acct.data).unwrap(), 0);
    assert_eq!(pool::commitment_count(&acct.data).unwrap(), 0);
    assert_eq!(&pool::authority(&acct.data).unwrap(), authority.as_ref());
    assert_ne!(
        pool::current_root(&acct.data).unwrap(),
        [0u8; 32],
        "empty-tree root is a non-zero Poseidon zero-ladder"
    );

    // Re-initializing the same pool must fail closed.
    let ix = env.init_ix(&pool, &authority, &payer, 10, 3, 5_000, 0, ZK_AMOUNT);
    env.process(
        &ix,
        &[Check::err(custom(MirrorPoolError::PoolAlreadyInitialized))],
    );
}

/// A pool must name the ONE escrow size its ZK opt-in path accepts, and it may
/// not be zero.
///
/// The denomination is half of the escrow-soundness argument (the other half is
/// the crowd/ZK leaf-domain split): nothing on-chain can read the amount a leaf's
/// `actionHash` bound, so admitting exactly one size at `COMMIT_DEPOSIT` and
/// paying exactly one size at settle is what keeps a settle from drawing more
/// than its leaf put in. A zero would mean "any amount", which is the hole
/// itself, so there is deliberately no "disabled" value.
#[test]
fn init_pool_rejects_a_zero_zk_denomination() {
    let mut env = Env::new();
    let authority = Pubkey::new_unique();
    let payer = Pubkey::new_unique();
    env.fund(payer, 100 * SOL);
    env.fund(authority, SOL);
    let pool = env.pool_pda(&authority);

    let ix = env.init_ix(&pool, &authority, &payer, 10, 3, 5_000, 0, 0);
    env.process(&ix, &[Check::err(ProgramError::InvalidArgument)]);

    // A non-zero denomination is stored verbatim and read back.
    let ix = env.init_ix(&pool, &authority, &payer, 10, 3, 5_000, 0, 7_777);
    env.process(&ix, &[Check::success()]);
    assert_eq!(
        pool::zk_denomination(&env.get(&pool).data).unwrap(),
        7_777,
        "the denomination must be fixed at init and readable"
    );
}

/// The circuit's canonical empty-tree root: `zeros[DEPTH]` where `zeros[0] = 0`
/// and `zeros[i] = Poseidon(zeros[i-1], zeros[i-1])`, computed on the host with
/// `light-poseidon` (the same Poseidon implementation the on-chain
/// `sol_poseidon` syscall is built on) in canonical big-endian bytes.
fn circuit_empty_root() -> [u8; 32] {
    use ark_bn254::Fr;
    use ark_ff::{BigInteger, PrimeField};
    use light_poseidon::{Poseidon, PoseidonHasher};

    let mut z = Fr::from(0u64);
    for _ in 0..mirror_pool::state::merkle::DEPTH {
        let mut h = Poseidon::<Fr>::new_circom(2).unwrap();
        z = h.hash(&[z, z]).unwrap();
    }
    let be = z.into_bigint().to_bytes_be();
    let mut out = [0u8; 32];
    out[32 - be.len()..].copy_from_slice(&be);
    out
}

/// DECISIVE on-chain <-> circuit check: the empty-tree root the program writes
/// at init (via the `sol_poseidon` accumulator) must equal the circuit's
/// `zeros[DEPTH]` reference computed independently with `light-poseidon`. If
/// this passes, the on-chain Merkle hashing is byte-identical to the circuit.
#[test]
fn empty_root_matches_circuit_zero_ladder() {
    let mut env = Env::new();
    let (_authority, _payer, pool) = init_pool(&mut env, 10, 3, 5_000);

    let on_chain = pool::current_root(&env.get(&pool).data).unwrap();
    assert_eq!(
        on_chain,
        circuit_empty_root(),
        "on-chain empty root must equal the circuit's Poseidon zero ladder"
    );
}

/// The cross-check vector shared with the ARKWORKS-NATIVE circuit in
/// `crates/mirror-circuits`. Its test
/// `gadget_produces_the_syscall_cross_check_vector` recomputes this leaf and
/// climbs this depth-20 path IN CIRCUIT (the constraint system is satisfied only
/// if the in-circuit Poseidon gadget produces exactly these bytes) and asserts
/// the same two constants.
///
/// Neither side trusts the other: both recompute and compare against the shared
/// vector. Read `docs/ARKWORKS.md` section 3 for what the agreement does and does
/// not prove - the syscall is built on `light-poseidon`, whose parameter table
/// the gadget also uses, so this pins the parameter / layout / byte-order wiring
/// rather than two independent Poseidon implementations.
const ARKWORKS_GADGET_LEAF_HEX: &str =
    "17f05ec0329a0f4379a258bdb21ea7bcf77d18f8b29e938de4107000cbe29e47";
const ARKWORKS_GADGET_ROOT_HEX: &str =
    "17eb8b099a02413857616f6707ae037e92f08aa788d501f49da9a78a67b6a7c2";

/// GADGET <-> SYSCALL: append the arkworks circuit's commitment leaf through the
/// real `COMMIT_DEPOSIT` instruction and require the accumulator root - twenty
/// nested `sol_poseidon` syscall calls inside the SBF VM - to equal the root the
/// in-circuit Merkle climb produced.
///
/// `empty_root_matches_circuit_zero_ladder` only covers the all-zeros tree, where
/// the leaf value never enters. Here the leaf is a real
/// `Poseidon(secret, actionHash, epoch)` commitment, so every level mixes a
/// non-trivial value with a zero-ladder sibling.
///
/// The deposit path is the one that appends a commitment VERBATIM, and it is the
/// only path whose leaves a membership proof can be made for, so it is also the
/// only path this equivalence is about. A crowd `COMMIT` of the same bytes lands
/// in a different leaf domain (`merkle::crowd_leaf`) and would produce a
/// different root by design - see
/// `crowd_commit_leaf_is_domain_separated_from_the_zk_deposit_leaf`.
#[test]
fn on_chain_accumulator_matches_the_arkworks_gadget_vector() {
    let mut env = Env::new();
    let (_authority, payer, pool_key) = init_pool(&mut env, 1_000, 2, 0);
    env.warp(3);
    let epoch_acct = env.epoch_pda(&pool_key, 0);

    let leaf = hex32(ARKWORKS_GADGET_LEAF_HEX);
    let ix = env.commit_deposit_ix(&pool_key, &epoch_acct, &payer, &leaf, ZK_AMOUNT);
    env.process(&ix, &[Check::success()]);

    assert_eq!(
        pool::current_root(&env.get(&pool_key).data).unwrap(),
        hex32(ARKWORKS_GADGET_ROOT_HEX),
        "the syscall accumulator must reproduce the arkworks gadget's depth-20 root"
    );
}

/// Parse a 64-character big-endian hex string into 32 bytes.
fn hex32(s: &str) -> [u8; 32] {
    let bytes = s.as_bytes();
    assert_eq!(bytes.len(), 64, "expected 64 hex characters");
    let mut out = [0u8; 32];
    for (i, byte) in out.iter_mut().enumerate() {
        let hi = (bytes[2 * i] as char).to_digit(16).expect("hex digit");
        let lo = (bytes[2 * i + 1] as char).to_digit(16).expect("hex digit");
        *byte = (hi * 16 + lo) as u8;
    }
    out
}

/// Leaves picked to stress the accumulator rather than its happy path. Every
/// value is a canonical BN254 scalar (each is smaller than the field modulus
/// `r = 0x30644e...f0000001`, so the Poseidon syscall accepts it):
///
/// - the field element 1, the smallest non-zero leaf;
/// - `r - 1`, the largest canonical scalar there is;
/// - a zero leaf at a NON-zero index, which must not be confused with an empty
///   subtree (the frontier's zero ladder is positional, not value-based);
/// - four fixed pseudo-random vectors.
///
/// Seven leaves put indices 0..6 through both the even (left child, record the
/// sibling) and odd (right child, pair with the recorded sibling) branches at
/// levels 0, 1 and 2.
fn varied_leaves() -> [[u8; 32]; 7] {
    [
        hex32("0000000000000000000000000000000000000000000000000000000000000001"),
        // r - 1, the largest canonical BN254 scalar.
        hex32("30644e72e131a029b85045b68181585d2833e84879b9709143e1f593f0000000"),
        hex32("0f1e2d3c4b5a69788796a5b4c3d2e1f00123456789abcdef0fedcba987654321"),
        // A zero leaf, appended at index 3.
        [0u8; 32],
        hex32("1a2b3c4d5e6f708192a3b4c5d6e7f8091a2b3c4d5e6f708192a3b4c5d6e7f809"),
        hex32("2bd6f1c0a95e8347d2c1b0a9f8e7d6c5b4a39281706f5e4d3c2b1a0918273645"),
        hex32("07ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"),
    ]
}

/// A distinct canonical leaf per index, for the ring-buffer test. The leading
/// `0x01` byte keeps the value far below the BN254 modulus.
fn ring_leaf(i: usize) -> [u8; 32] {
    let mut leaf = [0u8; 32];
    leaf[0] = 0x01;
    leaf[30] = (i / 256) as u8;
    leaf[31] = (i % 256) as u8;
    leaf
}

/// The equivalence check the zero-ladder test above does NOT cover: append
/// arbitrary, varied leaves through the real COMMIT instruction and compare the
/// on-chain accumulator against a host recomputation at every step.
///
/// `empty_root_matches_circuit_zero_ladder` only pins the all-zeros case, where
/// both children of every node are equal and the leaf values never enter; before
/// this test the loaded-tree case was only exercised end-to-end by the live
/// soaks. Here the root, the leaf count and every frontier sibling must match
/// after each of seven appends.
///
/// Read `tests/fixtures/host_frontier.rs` for what this equivalence proves: the
/// host and the syscall are not independent Poseidon implementations, so the
/// check pins the parameter/endianness/argument-order wiring and the frontier
/// insert, not the hash function itself.
#[test]
fn commit_root_matches_host_frontier_for_varied_leaves() {
    let mut env = Env::new();
    let (_authority, payer, pool_key) = init_pool(&mut env, 1_000, 2, 0);
    env.warp(3);
    let epoch_acct = env.epoch_pda(&pool_key, 0);

    let mut host = host::HostFrontier::new();
    assert_eq!(
        pool::current_root(&env.get(&pool_key).data).unwrap(),
        host.root(),
        "empty accumulators must agree before any append"
    );

    for (i, commitment) in varied_leaves().iter().enumerate() {
        let ix = env.commit_ix(&pool_key, &epoch_acct, &payer, commitment);
        env.process(&ix, &[Check::success()]);

        // What COMMIT appends is the DOMAIN-WRAPPED leaf, not the posted
        // commitment, so the host reference wraps it too. Using the mirror-core
        // implementation here also cross-checks the two copies of the domain
        // constant against the syscall the program actually ran.
        let expected = host.append(&mirror_core::crowd_leaf(commitment));
        let data = env.get(&pool_key).data;
        assert_eq!(
            pool::current_root(&data).unwrap(),
            expected,
            "on-chain root must equal the host frontier root after leaf {i}"
        );
        assert_eq!(pool::commitment_count(&data).unwrap(), (i + 1) as u64);
        for level in 0..mirror_pool::state::merkle::DEPTH {
            assert_eq!(
                pool::filled_subtree(&data, level).unwrap(),
                host.filled_subtree(level),
                "frontier sibling at level {level} must match after leaf {i}"
            );
        }
        assert!(
            pool::is_known_root(&data, &expected).unwrap(),
            "each new root must enter the recent-root ring"
        );
    }
}

/// The recent-root ring is what lets a proof made against a snapshot still
/// settle after later appends, so its wrap-around matters: `INIT_POOL` seeds all
/// `ROOT_HISTORY_SIZE` slots with the empty root, exactly that many commits must
/// evict every one of them, and the next commit must drop the oldest real root.
#[test]
fn root_history_ring_wraps_and_evicts_oldest() {
    let mut env = Env::new();
    let (_authority, payer, pool_key) = init_pool(&mut env, 100_000, 2, 0);
    env.warp(3);
    let epoch_acct = env.epoch_pda(&pool_key, 0);

    let empty = circuit_empty_root();
    assert!(
        pool::is_known_root(&env.get(&pool_key).data, &empty).unwrap(),
        "init seeds every ring slot with the empty root"
    );

    let mut host = host::HostFrontier::new();
    let mut roots = Vec::with_capacity(pool::ROOT_HISTORY_SIZE);
    for i in 0..pool::ROOT_HISTORY_SIZE {
        let leaf = ring_leaf(i);
        let ix = env.commit_ix(&pool_key, &epoch_acct, &payer, &leaf);
        env.process(&ix, &[Check::success()]);
        let expected = host.append(&mirror_core::crowd_leaf(&leaf));
        assert_eq!(
            pool::current_root(&env.get(&pool_key).data).unwrap(),
            expected,
            "on-chain root must equal the host frontier root at append {i}"
        );
        roots.push(expected);
    }

    let data = env.get(&pool_key).data;
    assert_eq!(
        pool::root_head(&data).unwrap(),
        0,
        "the head must have wrapped exactly once"
    );
    for (i, root) in roots.iter().enumerate() {
        assert!(
            pool::is_known_root(&data, root).unwrap(),
            "root {i} must still be in the ring"
        );
    }
    assert!(
        !pool::is_known_root(&data, &empty).unwrap(),
        "the seeded empty root must be fully evicted after a full ring of commits"
    );

    // One more commit evicts the oldest recorded root and nothing else.
    let leaf = ring_leaf(pool::ROOT_HISTORY_SIZE);
    let ix = env.commit_ix(&pool_key, &epoch_acct, &payer, &leaf);
    env.process(&ix, &[Check::success()]);
    let data = env.get(&pool_key).data;
    assert!(
        !pool::is_known_root(&data, &roots[0]).unwrap(),
        "the oldest root must be evicted"
    );
    assert!(
        pool::is_known_root(&data, &roots[1]).unwrap(),
        "the second-oldest root must survive one more commit"
    );
}

#[test]
fn commit_bumps_counts_root_and_collects_fee() {
    let mut env = Env::new();
    let entry_fee = 7_000u64;
    let (_authority, payer, pool) = init_pool(&mut env, 10, 2, entry_fee);

    let pool_lamports_after_init = env.get(&pool).lamports;
    let root0 = pool::current_root(&env.get(&pool).data).unwrap();

    // Commit at slot 3 -> epoch 0.
    env.warp(3);
    let epoch_id = 0u64;
    let epoch_acct = env.epoch_pda(&pool, epoch_id);

    let c1 = [11u8; 32];
    let ix = env.commit_ix(&pool, &epoch_acct, &payer, &c1);
    env.process(&ix, &[Check::success()]);

    let pool_acct = env.get(&pool);
    assert_eq!(pool::commitment_count(&pool_acct.data).unwrap(), 1);
    let root1 = pool::current_root(&pool_acct.data).unwrap();
    assert_ne!(root1, root0, "root must change after the first append");

    let epoch_acct_data = env.get(&epoch_acct);
    assert_eq!(epoch_acct_data.owner, env.program_id);
    assert_eq!(epoch::epoch_id(&epoch_acct_data.data).unwrap(), epoch_id);
    assert_eq!(epoch::commit_count(&epoch_acct_data.data).unwrap(), 1);

    // Second, distinct commit in the same epoch.
    let c2 = [22u8; 32];
    let ix = env.commit_ix(&pool, &epoch_acct, &payer, &c2);
    env.process(&ix, &[Check::success()]);

    let pool_acct = env.get(&pool);
    assert_eq!(pool::commitment_count(&pool_acct.data).unwrap(), 2);
    let root2 = pool::current_root(&pool_acct.data).unwrap();
    assert_ne!(root2, root1, "root must change after the second append");
    assert_eq!(epoch::commit_count(&env.get(&epoch_acct).data).unwrap(), 2);

    // Both entry fees landed in the pool.
    assert_eq!(
        env.get(&pool).lamports,
        pool_lamports_after_init + 2 * entry_fee,
        "entry fees must accumulate in the pool"
    );
}

#[test]
fn settle_before_window_closes_fails() {
    let mut env = Env::new();
    let (authority, payer, pool) = init_pool(&mut env, 10, 2, 0);
    let epoch_id = 0u64;
    let epoch_acct = env.epoch_pda(&pool, epoch_id);

    env.warp(3);
    for c in [[1u8; 32], [2u8; 32]] {
        let ix = env.commit_ix(&pool, &epoch_acct, &payer, &c);
        env.process(&ix, &[Check::success()]);
    }

    // Still inside the window: settle_slot(0) = 10, current slot 5 < 10.
    env.warp(5);
    let nf = [9u8; 32];
    let nf_pda = env.nf_pda(&pool, epoch_id, &nf);
    let ix = env.settle_ix(
        &pool,
        &epoch_acct,
        &authority,
        &[nf_pda],
        &[nf],
        &payer,
        epoch_id,
    );
    env.process(&ix, &[Check::err(custom(MirrorPoolError::EpochNotClosed))]);
}

#[test]
fn settle_below_k_floor_fails() {
    let mut env = Env::new();
    let (authority, payer, pool) = init_pool(&mut env, 10, 3, 0);
    let epoch_id = 0u64;
    let epoch_acct = env.epoch_pda(&pool, epoch_id);

    // Only 2 commits, but k_floor = 3.
    env.warp(3);
    for c in [[1u8; 32], [2u8; 32]] {
        let ix = env.commit_ix(&pool, &epoch_acct, &payer, &c);
        env.process(&ix, &[Check::success()]);
    }

    env.warp(10);
    let nfs = [[9u8; 32], [8u8; 32]];
    let nf_pdas: Vec<Pubkey> = nfs
        .iter()
        .map(|nf| env.nf_pda(&pool, epoch_id, nf))
        .collect();
    let ix = env.settle_ix(
        &pool,
        &epoch_acct,
        &authority,
        &nf_pdas,
        &nfs,
        &payer,
        epoch_id,
    );
    env.process(&ix, &[Check::err(custom(MirrorPoolError::BelowKFloor))]);
}

#[test]
fn settle_by_non_authority_fails() {
    let mut env = Env::new();
    let (_authority, payer, pool) = init_pool(&mut env, 10, 2, 0);
    let epoch_id = 0u64;
    let epoch_acct = env.epoch_pda(&pool, epoch_id);

    env.warp(3);
    for c in [[1u8; 32], [2u8; 32]] {
        let ix = env.commit_ix(&pool, &epoch_acct, &payer, &c);
        env.process(&ix, &[Check::success()]);
    }

    env.warp(10);
    let imposter = Pubkey::new_unique();
    env.fund(imposter, SOL);
    let nf = [9u8; 32];
    let nf_pda = env.nf_pda(&pool, epoch_id, &nf);
    // A different (but validly signing) key must not be able to settle.
    let ix = env.settle_ix(
        &pool,
        &epoch_acct,
        &imposter,
        &[nf_pda],
        &[nf],
        &payer,
        epoch_id,
    );
    env.process(&ix, &[Check::err(custom(MirrorPoolError::Unauthorized))]);
}

#[test]
fn settle_happy_path_then_double_settle_fails() {
    let mut env = Env::new();
    let (authority, payer, pool) = init_pool(&mut env, 10, 2, 0);
    let epoch_id = 0u64;
    let epoch_acct = env.epoch_pda(&pool, epoch_id);

    env.warp(3);
    for c in [[1u8; 32], [2u8; 32]] {
        let ix = env.commit_ix(&pool, &epoch_acct, &payer, &c);
        env.process(&ix, &[Check::success()]);
    }

    // Window closed (>= settle_slot(0) = 10), count (2) >= k_floor (2).
    env.warp(12);
    let nfs = [[9u8; 32], [8u8; 32]];
    let nf_pdas: Vec<Pubkey> = nfs
        .iter()
        .map(|nf| env.nf_pda(&pool, epoch_id, nf))
        .collect();
    let ix = env.settle_ix(
        &pool,
        &epoch_acct,
        &authority,
        &nf_pdas,
        &nfs,
        &payer,
        epoch_id,
    );
    env.process(&ix, &[Check::success()]);

    // Epoch is marked settled and each nullifier PDA now exists (spent).
    assert!(epoch::is_settled(&env.get(&epoch_acct).data).unwrap());
    for nf_pda in &nf_pdas {
        let acct = env.get(nf_pda);
        assert_eq!(acct.owner, env.program_id, "nullifier PDA must be created");
        assert_eq!(acct.data.len(), nullifier::LEN);
        assert_eq!(acct.data[0], nullifier::SPENT);
    }

    // Settling the same epoch again must fail closed.
    let ix = env.settle_ix(
        &pool,
        &epoch_acct,
        &authority,
        &nf_pdas,
        &nfs,
        &payer,
        epoch_id,
    );
    env.process(
        &ix,
        &[Check::err(custom(MirrorPoolError::EpochAlreadySettled))],
    );
}

/// Build a program-owned, initialized Pool account directly (bypassing the
/// frontier build-up) whose recent-root ring already contains the committed
/// fixture's root, and fund it with `lamports`. This is the "set the pool's root
/// history to include the fixture's root" step: a real deposit sequence cannot
/// reproduce the fixture's single-leaf tree, so the test injects the snapshot.
fn build_zk_pool(
    env: &mut Env,
    authority: &Pubkey,
    epoch_slots: u64,
    k_floor: u32,
    lamports: u64,
) -> Pubkey {
    let pool = env.pool_pda(authority);
    let (_, bump) = Pubkey::find_program_address(&[POOL_SEED, authority.as_ref()], &env.program_id);
    let empty_root = circuit_empty_root();
    let mut data = vec![0u8; pool::LEN];
    pool::init(
        &mut data,
        epoch_slots,
        k_floor,
        0,
        0,
        // The fixed ZK denomination IS the amount the committed fixture binds,
        // so a fixture settle is an in-denomination settle.
        ZK_AMOUNT,
        &authority.to_bytes(),
        bump,
        &empty_root,
    )
    .unwrap();
    // Inject the fixture's root snapshot (public signal [0]) into the ring.
    pool::record_root_history(&mut data, &fixture::PUBLIC_INPUTS[0]).unwrap();
    assert!(
        pool::is_known_root(&data, &fixture::PUBLIC_INPUTS[0]).unwrap(),
        "fixture root must be a known recent root"
    );
    let mut account = Account::new(lamports, pool::LEN, &env.program_id);
    account.data = data;
    env.accounts.insert(pool, account);
    pool
}

#[test]
fn commit_deposit_escrows_and_appends() {
    let mut env = Env::new();
    // The escrow size is the pool's, not the caller's: init the pool with the
    // denomination this test deposits.
    let amount = 400_000_000u64;
    let (_authority, payer, pool) = init_pool_full(&mut env, 10, 2, 0, 0, amount);
    let pool_after_init = env.get(&pool).lamports;
    let root0 = pool::current_root(&env.get(&pool).data).unwrap();

    env.warp(3);
    let epoch_id = 0u64;
    let epoch_acct = env.epoch_pda(&pool, epoch_id);
    let commitment = [7u8; 32];
    let ix = env.commit_deposit_ix(&pool, &epoch_acct, &payer, &commitment, amount);
    env.process(&ix, &[Check::success()]);

    let pool_acct = env.get(&pool);
    assert_eq!(pool::commitment_count(&pool_acct.data).unwrap(), 1);
    let root1 = pool::current_root(&pool_acct.data).unwrap();
    assert_ne!(root1, root0, "root must change after a deposit-commit");
    assert!(
        pool::is_known_root(&pool_acct.data, &root1).unwrap(),
        "the new root must be recorded in the recent-root ring"
    );
    assert_eq!(
        pool_acct.lamports,
        pool_after_init + amount,
        "the escrow must land in the pool"
    );
    assert_eq!(epoch::commit_count(&env.get(&epoch_acct).data).unwrap(), 1);
}

#[test]
fn commit_deposit_zero_amount_fails() {
    let mut env = Env::new();
    let (_authority, payer, pool) = init_pool(&mut env, 10, 2, 0);
    env.warp(3);
    let epoch_acct = env.epoch_pda(&pool, 0);
    let ix = env.commit_deposit_ix(&pool, &epoch_acct, &payer, &[1u8; 32], 0);
    env.process(&ix, &[Check::err(ProgramError::InvalidArgument)]);
}

#[test]
fn settle_zk_verifies_fixture_and_transfers_escrow() {
    let mut env = Env::new();
    let authority = Pubkey::new_unique();
    env.fund(authority, SOL); // pays the nullifier PDA rent
    let pool_start = 5 * SOL + ZK_AMOUNT;
    let pool = build_zk_pool(&mut env, &authority, 10, 2, pool_start);

    let recipient = zk_recipient();
    env.fund(recipient, 0);

    // Window for epoch 7 closes at settle_slot(7) = 8 * 10 = 80.
    env.warp(80);

    let nf = fixture::PUBLIC_INPUTS[1]; // nullifierHash
    let nf_pda = env.nf_pda(&pool, ZK_EPOCH, &nf);
    let ix = env.settle_zk_ix(
        &pool,
        &authority,
        &nf_pda,
        &recipient,
        ZK_EPOCH,
        ZK_AMOUNT,
        &fixture::PUBLIC_INPUTS,
    );
    // The committed fixture proof verifies on-chain and the action executes.
    env.process(&ix, &[Check::success()]);

    assert_eq!(
        env.get(&recipient).lamports,
        ZK_AMOUNT,
        "escrow must be transferred to the fresh recipient"
    );
    assert_eq!(
        env.get(&pool).lamports,
        pool_start - ZK_AMOUNT,
        "pool must be debited by exactly the bound amount"
    );
    let nf_acct = env.get(&nf_pda);
    assert_eq!(
        nf_acct.owner, env.program_id,
        "nullifier PDA must be created"
    );
    assert_eq!(nf_acct.data.len(), nullifier::LEN);
    assert_eq!(nf_acct.data[0], nullifier::SPENT);
}

#[test]
fn settle_zk_rejects_mutated_public_input() {
    let mut env = Env::new();
    let authority = Pubkey::new_unique();
    env.fund(authority, SOL);
    let pool_start = 5 * SOL + ZK_AMOUNT;
    let pool = build_zk_pool(&mut env, &authority, 10, 2, pool_start);
    let recipient = zk_recipient();
    env.fund(recipient, 0);
    env.warp(80);

    // Flip one byte of the nullifierHash public input; derive the nf PDA from the
    // mutated value so the PDA and actionHash checks pass and we reach the proof.
    let mut mutated = fixture::PUBLIC_INPUTS;
    mutated[1][31] ^= 0x01;
    let nf_pda = env.nf_pda(&pool, ZK_EPOCH, &mutated[1]);
    let ix = env.settle_zk_ix(
        &pool, &authority, &nf_pda, &recipient, ZK_EPOCH, ZK_AMOUNT, &mutated,
    );
    env.process(
        &ix,
        &[Check::err(custom(MirrorPoolError::ProofVerificationFailed))],
    );

    // Fail-closed: no escrow moved, no recipient funding, no nullifier PDA.
    assert_eq!(env.get(&recipient).lamports, 0);
    assert_eq!(env.get(&pool).lamports, pool_start);
    assert_eq!(
        env.get(&nf_pda).owner,
        Pubkey::default(),
        "nullifier PDA must not be created on a rejected proof"
    );
}

#[test]
fn settle_zk_wrong_recipient_action_hash_mismatch() {
    let mut env = Env::new();
    let authority = Pubkey::new_unique();
    env.fund(authority, SOL);
    let pool_start = 5 * SOL + ZK_AMOUNT;
    let pool = build_zk_pool(&mut env, &authority, 10, 2, pool_start);
    // A recipient that is NOT the one bound into the fixture's actionHash: a
    // relay trying to redirect the escrow. The recompute check must catch it.
    let wrong_recipient = Pubkey::new_unique();
    env.fund(wrong_recipient, 0);
    env.warp(80);

    let nf = fixture::PUBLIC_INPUTS[1];
    let nf_pda = env.nf_pda(&pool, ZK_EPOCH, &nf);
    let ix = env.settle_zk_ix(
        &pool,
        &authority,
        &nf_pda,
        &wrong_recipient,
        ZK_EPOCH,
        ZK_AMOUNT,
        &fixture::PUBLIC_INPUTS,
    );
    env.process(
        &ix,
        &[Check::err(custom(MirrorPoolError::ActionHashMismatch))],
    );
    assert_eq!(env.get(&wrong_recipient).lamports, 0, "no redirect");
    assert_eq!(env.get(&pool).lamports, pool_start);
}

#[test]
fn settle_zk_replay_fails_nullifier_spent() {
    let mut env = Env::new();
    let authority = Pubkey::new_unique();
    env.fund(authority, SOL);
    let pool_start = 5 * SOL + ZK_AMOUNT;
    let pool = build_zk_pool(&mut env, &authority, 10, 2, pool_start);
    let recipient = zk_recipient();
    env.fund(recipient, 0);
    env.warp(80);

    let nf = fixture::PUBLIC_INPUTS[1];
    let nf_pda = env.nf_pda(&pool, ZK_EPOCH, &nf);
    let ix = env.settle_zk_ix(
        &pool,
        &authority,
        &nf_pda,
        &recipient,
        ZK_EPOCH,
        ZK_AMOUNT,
        &fixture::PUBLIC_INPUTS,
    );
    env.process(&ix, &[Check::success()]);

    // Re-submitting the same nullifier fails closed: its PDA already exists.
    let ix2 = env.settle_zk_ix(
        &pool,
        &authority,
        &nf_pda,
        &recipient,
        ZK_EPOCH,
        ZK_AMOUNT,
        &fixture::PUBLIC_INPUTS,
    );
    env.process(&ix2, &[Check::err(custom(MirrorPoolError::NullifierSpent))]);
}

#[test]
fn settle_zk_before_window_closes_fails() {
    let mut env = Env::new();
    let authority = Pubkey::new_unique();
    env.fund(authority, SOL);
    let pool_start = 5 * SOL + ZK_AMOUNT;
    let pool = build_zk_pool(&mut env, &authority, 10, 2, pool_start);
    let recipient = zk_recipient();
    env.fund(recipient, 0);

    // settle_slot(7) = 80; still inside the window at slot 50.
    env.warp(50);
    let nf = fixture::PUBLIC_INPUTS[1];
    let nf_pda = env.nf_pda(&pool, ZK_EPOCH, &nf);
    let ix = env.settle_zk_ix(
        &pool,
        &authority,
        &nf_pda,
        &recipient,
        ZK_EPOCH,
        ZK_AMOUNT,
        &fixture::PUBLIC_INPUTS,
    );
    env.process(&ix, &[Check::err(custom(MirrorPoolError::EpochNotClosed))]);
}

#[test]
fn settle_zk_by_non_authority_fails() {
    let mut env = Env::new();
    let authority = Pubkey::new_unique();
    env.fund(authority, SOL);
    let pool_start = 5 * SOL + ZK_AMOUNT;
    let pool = build_zk_pool(&mut env, &authority, 10, 2, pool_start);
    let recipient = zk_recipient();
    env.fund(recipient, 0);
    env.warp(80);

    let imposter = Pubkey::new_unique();
    env.fund(imposter, SOL);
    let nf = fixture::PUBLIC_INPUTS[1];
    let nf_pda = env.nf_pda(&pool, ZK_EPOCH, &nf);
    let ix = env.settle_zk_ix(
        &pool,
        &imposter,
        &nf_pda,
        &recipient,
        ZK_EPOCH,
        ZK_AMOUNT,
        &fixture::PUBLIC_INPUTS,
    );
    env.process(&ix, &[Check::err(custom(MirrorPoolError::Unauthorized))]);
}

#[test]
fn settle_zk_unknown_root_fails() {
    let mut env = Env::new();
    let authority = Pubkey::new_unique();
    env.fund(authority, SOL);
    let pool_start = 5 * SOL + ZK_AMOUNT;
    // A pool whose ring does NOT contain the fixture root (only the empty root).
    let pool = {
        let pool = env.pool_pda(&authority);
        let (_, bump) =
            Pubkey::find_program_address(&[POOL_SEED, authority.as_ref()], &env.program_id);
        let empty_root = circuit_empty_root();
        let mut data = vec![0u8; pool::LEN];
        pool::init(
            &mut data,
            10,
            2,
            0,
            0,
            ZK_AMOUNT,
            &authority.to_bytes(),
            bump,
            &empty_root,
        )
        .unwrap();
        let mut account = Account::new(pool_start, pool::LEN, &env.program_id);
        account.data = data;
        env.accounts.insert(pool, account);
        pool
    };
    let recipient = zk_recipient();
    env.fund(recipient, 0);
    env.warp(80);

    let nf = fixture::PUBLIC_INPUTS[1];
    let nf_pda = env.nf_pda(&pool, ZK_EPOCH, &nf);
    let ix = env.settle_zk_ix(
        &pool,
        &authority,
        &nf_pda,
        &recipient,
        ZK_EPOCH,
        ZK_AMOUNT,
        &fixture::PUBLIC_INPUTS,
    );
    env.process(&ix, &[Check::err(custom(MirrorPoolError::RootNotKnown))]);
}

// ---------------------------------------------------------------------------
// What SETTLE_ZK does NOT check. The two tests below are deliberate
// LIMITATION tests: they pin behaviour the program has today so the docs can
// describe it exactly (see the `settle_zk` module header and
// `docs/THREAT_MODEL.md` sections 4 and 8). They are expected to pass; if a
// later version adds one of these gates, the test that breaks is the signal to
// update the prose in the same commit.
// ---------------------------------------------------------------------------

/// The fixture's private secret (`circuits/gen_fixture.js`), which fits in a
/// `u128`, so its canonical big-endian BN254 encoding is a zero-padded 16-byte
/// tail. Knowing it lets a test rebuild the fixture's leaf.
const ZK_SECRET: u128 = 111_122_223_333_444_455_556_666_777_788_889_999;

/// The fixture leaf's index in the otherwise-empty depth-20 tree
/// (`LEAF_INDEX` in `circuits/gen_fixture.js`).
const ZK_LEAF_INDEX: u64 = 21;

/// `Poseidon(a, b, c)` in the parameterization the `sol_poseidon` syscall and
/// circomlib both use (Bn254X5, big-endian). Width 3, so this is the leaf
/// hasher `commitment = Poseidon(secret, actionHash, epoch)`.
fn poseidon3(a: &[u8; 32], b: &[u8; 32], c: &[u8; 32]) -> [u8; 32] {
    use light_poseidon::PoseidonBytesHasher;
    let mut hasher =
        light_poseidon::Poseidon::<ark_bn254::Fr>::new_circom(3).expect("circom Poseidon width 3");
    hasher
        .hash_bytes_be(&[a, b, c])
        .expect("canonical BN254 inputs")
}

/// Rebuild the fixture's Merkle leaf: `Poseidon(secret, actionHash, epoch)`,
/// with `actionHash` taken from the fixture's own public inputs.
fn zk_fixture_leaf() -> [u8; 32] {
    let mut secret = [0u8; 32];
    secret[16..].copy_from_slice(&ZK_SECRET.to_be_bytes());
    let mut epoch = [0u8; 32];
    epoch[24..].copy_from_slice(&ZK_EPOCH.to_be_bytes());
    poseidon3(&secret, &fixture::PUBLIC_INPUTS[2], &epoch)
}

/// SETTLE_ZK reads neither `pool.k_floor` nor any Epoch account: there is no
/// on-chain anonymity-set floor on the ZK path, and no per-epoch state is
/// consulted at all.
///
/// The pool below declares `k_floor = 1000` and no Epoch PDA exists for the
/// proof's epoch, yet the settle succeeds. This is deliberate, not an
/// oversight: the ZK escrow can only ever leave the pool through SETTLE_ZK, so
/// a settle-time floor would strand the escrow of any window that never reaches
/// it (the crowd path can roll an under-floor epoch forward at no cost to
/// anyone; the ZK path has no roll-forward and no refund). The floor for this
/// path is enforced client-side at proof time instead, where declining is free
/// and the participant, who alone can produce the proof, has the full window on
/// screen. See `mirror_cli::prove::AnonymitySet`.
#[test]
fn settle_zk_ignores_k_floor_and_needs_no_epoch_account() {
    let mut env = Env::new();
    let authority = Pubkey::new_unique();
    env.fund(authority, SOL);
    let pool_start = 5 * SOL + ZK_AMOUNT;
    // k_floor = 1000, far above anything this pool could ever have committed.
    let pool = build_zk_pool(&mut env, &authority, 10, 1000, pool_start);
    assert_eq!(
        pool::k_floor(&env.get(&pool).data).unwrap(),
        1000,
        "the pool must declare a floor SETTLE_ZK could have consulted"
    );
    // No Epoch PDA exists for the proof's epoch (nothing ever committed here).
    let epoch_acct = env.epoch_pda(&pool, ZK_EPOCH);
    assert_eq!(
        env.get(&epoch_acct).data.len(),
        0,
        "no Epoch account for the settled epoch"
    );

    let recipient = zk_recipient();
    env.fund(recipient, 0);
    env.warp(80);

    let nf = fixture::PUBLIC_INPUTS[1];
    let nf_pda = env.nf_pda(&pool, ZK_EPOCH, &nf);
    let ix = env.settle_zk_ix(
        &pool,
        &authority,
        &nf_pda,
        &recipient,
        ZK_EPOCH,
        ZK_AMOUNT,
        &fixture::PUBLIC_INPUTS,
    );
    env.process(&ix, &[Check::success()]);
    assert_eq!(
        env.get(&recipient).lamports,
        ZK_AMOUNT,
        "the escrow is released with no floor and no epoch account"
    );
}

/// "Fresh recipient" is a CLIENT convention: the recipient here already holds
/// lamports and the settle proceeds, because the only thing checked is that the
/// recipient matches the proof's `actionHash`.
///
/// This is also why no freshness check can be bolted on later without a refund
/// path. The recipient is fixed at deposit time by a hash, so a check for an
/// empty account would let anyone who learned that address strand the escrow
/// permanently by sending it one lamport - and emptiness was never the property
/// that mattered anyway, since an address is unlinkable only until its owner
/// sweeps it.
#[test]
fn settle_zk_accepts_a_recipient_that_is_not_fresh() {
    let mut env = Env::new();
    let authority = Pubkey::new_unique();
    env.fund(authority, SOL);
    let pool_start = 5 * SOL + ZK_AMOUNT;
    let pool = build_zk_pool(&mut env, &authority, 10, 2, pool_start);

    // A recipient with a prior balance: visibly used, not fresh.
    let recipient = zk_recipient();
    let prior = 3 * SOL;
    env.fund(recipient, prior);
    env.warp(80);

    let nf = fixture::PUBLIC_INPUTS[1];
    let nf_pda = env.nf_pda(&pool, ZK_EPOCH, &nf);
    let ix = env.settle_zk_ix(
        &pool,
        &authority,
        &nf_pda,
        &recipient,
        ZK_EPOCH,
        ZK_AMOUNT,
        &fixture::PUBLIC_INPUTS,
    );
    env.process(&ix, &[Check::success()]);
    assert_eq!(
        env.get(&recipient).lamports,
        prior + ZK_AMOUNT,
        "the escrow lands on top of the recipient's existing balance"
    );
}

/// FUND THEFT, REJECTED: a fee-only crowd `COMMIT` cannot produce a leaf the ZK
/// settle path will spend.
///
/// This is the same scenario the pool used to lose money to, run against the
/// fixed program. Mallory pays for crowd commits only - no escrow, entry fee 0 -
/// and replays the exact sequence that used to reproduce the committed fixture's
/// tree: 21 zero leaves, then the fixture leaf at `ZK_LEAF_INDEX`. Bob is the
/// only participant who escrows anything.
///
/// What stops her is the LEAF DOMAIN. `COMMIT` appends
/// `Poseidon(CROWD_LEAF_DOMAIN, commitment)` rather than the posted bytes, so no
/// sequence of crowd commits reproduces a root over ZK deposit leaves, and the
/// membership proof's `root` public input is not a root this pool ever had. The
/// settle dies at the recent-root check with `RootNotKnown`, before a nullifier
/// PDA is created and before a lamport moves. Bob's escrow is untouched.
///
/// Note where the fix has to live. Absorbing a domain tag into the DEPOSIT
/// preimage instead - the obvious reading of "domain-separate the leaves" -
/// would close nothing: the deposit leaf is 32 caller-supplied bytes, so Mallory
/// would simply compute the tagged value herself and post it here for free. The
/// tag has to be applied by the PROGRAM to the FREE path, which is what
/// `merkle::crowd_leaf` does. `crowd_commit_leaf_is_domain_separated_from_the_zk_deposit_leaf`
/// pins that the pre-hashing dodge fails too.
#[test]
fn settle_zk_rejects_a_fee_only_crowd_leaf_spending_a_depositors_escrow() {
    let mut env = Env::new();
    let (authority, _payer, pool) = init_pool(&mut env, 10, 2, 0);

    // Mallory only ever pays for crowd COMMITs: no escrow, entry fee 0.
    let mallory = Pubkey::new_unique();
    env.fund(mallory, SOL);
    env.warp(3);
    let commit_epoch = 0u64;
    let epoch_acct = env.epoch_pda(&pool, commit_epoch);

    // The old attack: reproduce the fixture's tree with free commits - empty
    // leaves at 0..21 and the fixture leaf at ZK_LEAF_INDEX.
    for _ in 0..ZK_LEAF_INDEX {
        let ix = env.commit_ix(&pool, &epoch_acct, &mallory, &[0u8; 32]);
        env.process(&ix, &[Check::success()]);
    }
    let leaf = zk_fixture_leaf();
    let ix = env.commit_ix(&pool, &epoch_acct, &mallory, &leaf);
    env.process(&ix, &[Check::success()]);
    assert_ne!(
        pool::current_root(&env.get(&pool).data).unwrap(),
        fixture::PUBLIC_INPUTS[0],
        "crowd commits must NOT be able to reproduce a root over ZK deposit leaves"
    );
    assert!(
        !pool::is_known_root(&env.get(&pool).data, &fixture::PUBLIC_INPUTS[0]).unwrap(),
        "and the fixture root must not have entered the recent-root ring"
    );

    // Bob is the only participant who escrows anything.
    let bob = Pubkey::new_unique();
    env.fund(bob, 10 * SOL);
    let pool_before_deposit = env.get(&pool).lamports;
    let ix = env.commit_deposit_ix(&pool, &epoch_acct, &bob, &[9u8; 32], ZK_AMOUNT);
    env.process(&ix, &[Check::success()]);
    assert_eq!(
        env.get(&pool).lamports,
        pool_before_deposit + ZK_AMOUNT,
        "Bob's escrow is the only value in the pot"
    );
    let pool_after_deposit = env.get(&pool).lamports;

    // Mallory tries to settle her crowd leaf against Bob's escrow.
    let recipient = zk_recipient();
    env.fund(recipient, 0);
    env.warp(80);
    let nf = fixture::PUBLIC_INPUTS[1];
    let nf_pda = env.nf_pda(&pool, ZK_EPOCH, &nf);
    let ix = env.settle_zk_ix(
        &pool,
        &authority,
        &nf_pda,
        &recipient,
        ZK_EPOCH,
        ZK_AMOUNT,
        &fixture::PUBLIC_INPUTS,
    );
    env.process(&ix, &[Check::err(custom(MirrorPoolError::RootNotKnown))]);

    // Fail closed, all the way: no payout, no drain, no nullifier burnt.
    assert_eq!(
        env.get(&recipient).lamports,
        0,
        "the fee-only crowd leaf must not have been paid anything"
    );
    assert_eq!(
        env.get(&pool).lamports,
        pool_after_deposit,
        "Bob's escrow must still be in the pot"
    );
    assert_ne!(
        env.get(&nf_pda).owner,
        env.program_id,
        "a rejected settle must not create the nullifier PDA"
    );
}

/// The domain separation itself, stated directly against the accumulator: the
/// leaf a crowd `COMMIT` appends is never the leaf a `COMMIT_DEPOSIT` of the same
/// bytes appends, and pre-hashing the domain tag client-side does not change
/// that.
///
/// This is the property `settle_zk_rejects_a_fee_only_crowd_leaf_spending_a_depositors_escrow`
/// depends on, isolated so a regression names itself.
#[test]
fn crowd_commit_leaf_is_domain_separated_from_the_zk_deposit_leaf() {
    let mut env = Env::new();
    let (_authority, payer, pool) = init_pool(&mut env, 1_000, 2, 0);
    env.warp(3);
    let epoch_acct = env.epoch_pda(&pool, 0);

    // A crowd COMMIT of `c` appends crowd_leaf(c), which the host mirror agrees
    // on (this also cross-checks the program's mirrored domain constant against
    // mirror-core's).
    let c = zk_fixture_leaf();
    let ix = env.commit_ix(&pool, &epoch_acct, &payer, &c);
    env.process(&ix, &[Check::success()]);
    let mut host = host::HostFrontier::new();
    assert_eq!(
        pool::current_root(&env.get(&pool).data).unwrap(),
        host.append(&mirror_core::crowd_leaf(&c)),
        "COMMIT must append the domain-wrapped leaf, not the posted commitment"
    );

    // Pre-hashing the tag client-side does not get a caller into the ZK domain:
    // the program wraps whatever it is handed, so the result is wrapped twice.
    let ix = env.commit_ix(&pool, &epoch_acct, &payer, &mirror_core::crowd_leaf(&c));
    env.process(&ix, &[Check::success()]);
    assert_eq!(
        pool::current_root(&env.get(&pool).data).unwrap(),
        host.append(&mirror_core::crowd_leaf(&mirror_core::crowd_leaf(&c))),
        "a pre-wrapped commitment is wrapped again, never unwrapped"
    );

    // A COMMIT_DEPOSIT of the SAME bytes appends them verbatim: a different leaf.
    let mut env2 = Env::new();
    let (_a2, payer2, pool2) = init_pool(&mut env2, 1_000, 2, 0);
    env2.warp(3);
    let epoch2 = env2.epoch_pda(&pool2, 0);
    env2.fund(payer2, 100 * SOL);
    let ix = env2.commit_deposit_ix(&pool2, &epoch2, &payer2, &c, ZK_AMOUNT);
    env2.process(&ix, &[Check::success()]);
    let mut host2 = host::HostFrontier::new();
    assert_eq!(
        pool::current_root(&env2.get(&pool2).data).unwrap(),
        host2.append(&c),
        "COMMIT_DEPOSIT must append the commitment verbatim (the ZK domain)"
    );
    assert_ne!(
        mirror_core::crowd_leaf(&c),
        c,
        "the two domains must not coincide for any commitment"
    );
}

/// The mirrored constants really are mirrors. The program redefines
/// `mirror_core`'s wire layout and crowd leaf-domain tag by hand so the deployed
/// `.so` never links a std host crate; this asserts the two copies agree instead
/// of trusting the comment that says they must.
#[test]
fn mirrored_constants_match_mirror_core() {
    use mirror_core::wire as cw;
    use mirror_pool::wire as pw;

    assert_eq!(
        mirror_pool::state::merkle::CROWD_LEAF_DOMAIN,
        mirror_core::CROWD_LEAF_DOMAIN,
        "the crowd leaf-domain tag must be identical on both sides"
    );
    assert_eq!(pw::INIT_POOL_LEN, cw::INIT_POOL_LEN);
    assert_eq!(pw::COMMIT_LEN, cw::COMMIT_LEN);
    assert_eq!(pw::COMMIT_DEPOSIT_LEN, cw::COMMIT_DEPOSIT_LEN);
    assert_eq!(pw::SETTLE_ZK_LEN, cw::SETTLE_ZK_LEN);
    assert_eq!(pw::SETTLE_ZK_ASSOCIATED_LEN, cw::SETTLE_ZK_ASSOCIATED_LEN);
    assert_eq!(pw::tag::COMMIT, cw::tag::COMMIT);
    assert_eq!(pw::tag::COMMIT_DEPOSIT, cw::tag::COMMIT_DEPOSIT);
    assert_eq!(pw::tag::SETTLE_ZK, cw::tag::SETTLE_ZK);
}

/// The amount half of escrow soundness on the deposit side: a pool takes exactly
/// its `zk_denomination` and nothing else.
///
/// Without this, a depositor could escrow one lamport while binding an
/// `actionHash` over a large amount, then settle for the large amount - the leaf
/// is one opaque field element, so no on-chain check can compare the two.
#[test]
fn commit_deposit_rejects_an_off_denomination_escrow() {
    let mut env = Env::new();
    let (_authority, payer, pool) = init_pool(&mut env, 10, 2, 0);
    let pool_before = env.get(&pool).lamports;
    env.warp(3);
    let epoch_acct = env.epoch_pda(&pool, 0);

    for amount in [1u64, ZK_AMOUNT - 1, ZK_AMOUNT + 1, 10 * ZK_AMOUNT] {
        let ix = env.commit_deposit_ix(&pool, &epoch_acct, &payer, &[3u8; 32], amount);
        env.process(
            &ix,
            &[Check::err(custom(MirrorPoolError::DenominationMismatch))],
        );
    }
    assert_eq!(
        env.get(&pool).lamports,
        pool_before,
        "a rejected deposit must move no lamports"
    );
    assert_eq!(
        pool::commitment_count(&env.get(&pool).data).unwrap(),
        0,
        "and must append no leaf"
    );

    // The pool's own size is accepted.
    let ix = env.commit_deposit_ix(&pool, &epoch_acct, &payer, &[3u8; 32], ZK_AMOUNT);
    env.process(&ix, &[Check::success()]);
}

/// The amount half of escrow soundness on the settle side: a settle pays exactly
/// the pool's `zk_denomination`.
///
/// The pool below is funded far above one denomination (as a live pool with many
/// deposits would be), so the only thing standing between a settle and the rest
/// of the pot is this check. It runs before the proof is verified and before the
/// nullifier PDA is created, so an over-draw attempt leaves no trace.
#[test]
fn settle_zk_rejects_an_off_denomination_amount() {
    let mut env = Env::new();
    let authority = Pubkey::new_unique();
    env.fund(authority, SOL);
    let pool_start = 50 * SOL;
    let pool = build_zk_pool(&mut env, &authority, 10, 2, pool_start);
    let recipient = zk_recipient();
    env.fund(recipient, 0);
    env.warp(80);

    // The proof's actionHash binds (recipient, ZK_AMOUNT), so a settle for a
    // different amount would fail the actionHash check too - but the denomination
    // gate is what fires, and it fires FIRST, before any state is touched.
    let nf = fixture::PUBLIC_INPUTS[1];
    let nf_pda = env.nf_pda(&pool, ZK_EPOCH, &nf);
    for amount in [ZK_AMOUNT + 1, 10 * ZK_AMOUNT, 1] {
        let ix = env.settle_zk_ix(
            &pool,
            &authority,
            &nf_pda,
            &recipient,
            ZK_EPOCH,
            amount,
            &fixture::PUBLIC_INPUTS,
        );
        env.process(
            &ix,
            &[Check::err(custom(MirrorPoolError::DenominationMismatch))],
        );
    }
    assert_eq!(env.get(&recipient).lamports, 0, "nothing may be paid out");
    assert_eq!(
        env.get(&pool).lamports,
        pool_start,
        "the pot must be untouched"
    );
    assert_ne!(
        env.get(&nf_pda).owner,
        env.program_id,
        "no nullifier PDA may be created by a rejected settle"
    );

    // The in-denomination settle still works, so the gate is not just refusing
    // everything.
    let ix = env.settle_zk_ix(
        &pool,
        &authority,
        &nf_pda,
        &recipient,
        ZK_EPOCH,
        ZK_AMOUNT,
        &fixture::PUBLIC_INPUTS,
    );
    env.process(&ix, &[Check::success()]);
    assert_eq!(env.get(&recipient).lamports, ZK_AMOUNT);
}

#[test]
fn settle_duplicate_nullifier_fails() {
    let mut env = Env::new();
    let (authority, payer, pool) = init_pool(&mut env, 10, 2, 0);
    let epoch_id = 0u64;
    let epoch_acct = env.epoch_pda(&pool, epoch_id);

    env.warp(3);
    for c in [[1u8; 32], [2u8; 32]] {
        let ix = env.commit_ix(&pool, &epoch_acct, &payer, &c);
        env.process(&ix, &[Check::success()]);
    }

    env.warp(10);
    // The same nullifier appears twice in one settle: the second create sees an
    // already-spent (program-owned) PDA.
    let nf = [9u8; 32];
    let nf_pda = env.nf_pda(&pool, epoch_id, &nf);
    let ix = env.settle_ix(
        &pool,
        &epoch_acct,
        &authority,
        &[nf_pda, nf_pda],
        &[nf, nf],
        &payer,
        epoch_id,
    );
    env.process(&ix, &[Check::err(custom(MirrorPoolError::NullifierSpent))]);
}

// --- Participation-incentive tests (anti-Sybil reward split + dwell reward). ---

#[test]
fn entry_fee_splits_into_reward_pool() {
    let mut env = Env::new();
    let entry_fee = 10_000u64;
    let reward_bps = 3_000u16; // 30% to rewards, 70% settlement reserve.
    let (_authority, payer, pool) = init_pool_with_reward(&mut env, 10, 2, entry_fee, reward_bps);
    let pool_after_init = env.get(&pool).lamports;

    env.warp(3);
    let e0 = env.epoch_pda(&pool, 0);
    let ix = env.commit_ix(&pool, &e0, &payer, &[1u8; 32]);
    env.process(&ix, &[Check::success()]);

    let pool_acct = env.get(&pool);
    // 30% of 10_000 = 3_000 lamports earmarked for participation rewards.
    assert_eq!(
        pool::reward_pool_lamports(&pool_acct.data).unwrap(),
        3_000,
        "reward pool must hold the reward_bps share of the fee"
    );
    // The full fee still lands in the pool balance; the remaining 7_000 is the
    // (un-earmarked) settlement reserve.
    assert_eq!(
        pool_acct.lamports,
        pool_after_init + entry_fee,
        "the whole entry fee lands in the pool balance"
    );
}

#[test]
fn zero_entry_fee_disables_reward_pool() {
    let mut env = Env::new();
    // reward_bps is non-zero, but a zero entry fee leaves nothing to split.
    let (_authority, payer, pool) = init_pool_with_reward(&mut env, 10, 2, 0, 5_000);
    env.warp(3);
    let e0 = env.epoch_pda(&pool, 0);
    let ix = env.commit_ix(&pool, &e0, &payer, &[1u8; 32]);
    env.process(&ix, &[Check::success()]);
    assert_eq!(
        pool::reward_pool_lamports(&env.get(&pool).data).unwrap(),
        0,
        "a zero entry fee must leave the reward pool empty"
    );
}

#[test]
fn commit_deposit_splits_into_reward_pool() {
    let mut env = Env::new();
    let entry_fee = 20_000u64;
    let reward_bps = 2_500u16; // 25%
    let amount = 400_000_000u64;
    let (_authority, payer, pool) = init_pool_full(&mut env, 10, 2, entry_fee, reward_bps, amount);
    let pool_after_init = env.get(&pool).lamports;

    env.warp(3);
    let e0 = env.epoch_pda(&pool, 0);
    let ix = env.commit_deposit_ix(&pool, &e0, &payer, &[7u8; 32], amount);
    env.process(&ix, &[Check::success()]);

    let pool_acct = env.get(&pool);
    // Both the escrow and the fee land in the pool balance.
    assert_eq!(
        pool_acct.lamports,
        pool_after_init + amount + entry_fee,
        "escrow + entry fee both land in the pool"
    );
    // 25% of 20_000 = 5_000 earmarked for rewards; the escrow is untouched.
    assert_eq!(
        pool::reward_pool_lamports(&pool_acct.data).unwrap(),
        5_000,
        "the ZK path also funds the reward pool from its entry fee"
    );
}

#[test]
fn dwell_increments_once_per_epoch() {
    let mut env = Env::new();
    let (_authority, _payer, pool) = init_pool_with_reward(&mut env, 10, 2, 1_000, 5_000);
    let p = Pubkey::new_unique();
    env.fund(p, 10 * SOL);
    let dwell = env.dwell_pda(&pool, &p);

    // Two commits in the SAME epoch window count dwell exactly once.
    env.warp(3);
    let e0 = env.epoch_pda(&pool, 0);
    let ix = env.commit_with_dwell_ix(&pool, &e0, &p, &dwell, &[1u8; 32]);
    env.process(&ix, &[Check::success()]);
    let ix = env.commit_with_dwell_ix(&pool, &e0, &p, &dwell, &[2u8; 32]);
    env.process(&ix, &[Check::success()]);

    let dwell_acct = env.get(&dwell);
    assert_eq!(
        dwell_acct.owner, env.program_id,
        "dwell PDA must be created"
    );
    assert_eq!(participant::dwell(&dwell_acct.data).unwrap(), 1);
    assert_eq!(participant::last_epoch(&dwell_acct.data).unwrap(), 0);
    assert_eq!(
        pool::total_unclaimed_dwell(&env.get(&pool).data).unwrap(),
        1,
        "the pool denominator advances once per counted epoch"
    );

    // A commit in a new epoch window advances dwell to 2.
    env.warp(13);
    let e1 = env.epoch_pda(&pool, 1);
    let ix = env.commit_with_dwell_ix(&pool, &e1, &p, &dwell, &[3u8; 32]);
    env.process(&ix, &[Check::success()]);
    assert_eq!(participant::dwell(&env.get(&dwell).data).unwrap(), 2);
    assert_eq!(
        pool::total_unclaimed_dwell(&env.get(&pool).data).unwrap(),
        2
    );
}

#[test]
fn claim_reward_pays_proportional_to_dwell() {
    let mut env = Env::new();
    let entry_fee = 1_000_000u64;
    // 100% split so each fee-paying commit adds exactly `entry_fee` to rewards.
    let (_authority, _payer, pool) = init_pool_with_reward(&mut env, 10, 2, entry_fee, 10_000);

    let a = Pubkey::new_unique();
    let b = Pubkey::new_unique();
    env.fund(a, 10 * SOL);
    env.fund(b, 10 * SOL);
    let dwell_a = env.dwell_pda(&pool, &a);
    let dwell_b = env.dwell_pda(&pool, &b);

    // Epoch 0: A and B both commit with dwell.
    env.warp(3);
    let e0 = env.epoch_pda(&pool, 0);
    let ix = env.commit_with_dwell_ix(&pool, &e0, &a, &dwell_a, &[1u8; 32]);
    env.process(&ix, &[Check::success()]);
    let ix = env.commit_with_dwell_ix(&pool, &e0, &b, &dwell_b, &[2u8; 32]);
    env.process(&ix, &[Check::success()]);

    // Epoch 1: only A commits again -> dwell_A = 2, dwell_B = 1.
    env.warp(13);
    let e1 = env.epoch_pda(&pool, 1);
    let ix = env.commit_with_dwell_ix(&pool, &e1, &a, &dwell_a, &[3u8; 32]);
    env.process(&ix, &[Check::success()]);

    // Reward pool = 3 * entry_fee (100% split), total unclaimed dwell = 3.
    let pool_acct = env.get(&pool);
    assert_eq!(
        pool::reward_pool_lamports(&pool_acct.data).unwrap(),
        3 * entry_fee
    );
    assert_eq!(pool::total_unclaimed_dwell(&pool_acct.data).unwrap(), 3);
    assert_eq!(participant::dwell(&env.get(&dwell_a).data).unwrap(), 2);
    assert_eq!(participant::dwell(&env.get(&dwell_b).data).unwrap(), 1);

    // A claims its 2/3 share of the current pool.
    let a_before = env.get(&a).lamports;
    let ix = env.claim_reward_ix(&pool, &a, &dwell_a);
    env.process(&ix, &[Check::success()]);
    assert_eq!(
        env.get(&a).lamports,
        a_before + 2 * entry_fee,
        "A's payout is proportional to its dwell (2 of 3)"
    );
    let pool_acct = env.get(&pool);
    assert_eq!(
        pool::reward_pool_lamports(&pool_acct.data).unwrap(),
        entry_fee
    );
    assert_eq!(pool::total_unclaimed_dwell(&pool_acct.data).unwrap(), 1);
    // A's dwell is now fully claimed.
    assert_eq!(
        participant::unclaimed_dwell(&env.get(&dwell_a).data).unwrap(),
        0
    );

    // B claims the remaining 1/1 share, draining the reward pool exactly.
    let b_before = env.get(&b).lamports;
    let ix = env.claim_reward_ix(&pool, &b, &dwell_b);
    env.process(&ix, &[Check::success()]);
    assert_eq!(env.get(&b).lamports, b_before + entry_fee);
    let pool_acct = env.get(&pool);
    assert_eq!(
        pool::reward_pool_lamports(&pool_acct.data).unwrap(),
        0,
        "the reward pool drains to exactly zero, never negative"
    );
    assert_eq!(pool::total_unclaimed_dwell(&pool_acct.data).unwrap(), 0);
}

#[test]
fn claim_reward_double_claim_rejected_and_drain_safe() {
    let mut env = Env::new();
    let entry_fee = 1_000_000u64;
    let (_authority, _payer, pool) = init_pool_with_reward(&mut env, 10, 2, entry_fee, 10_000);
    let p = Pubkey::new_unique();
    env.fund(p, 10 * SOL);
    let dwell = env.dwell_pda(&pool, &p);

    env.warp(3);
    let e0 = env.epoch_pda(&pool, 0);
    let ix = env.commit_with_dwell_ix(&pool, &e0, &p, &dwell, &[1u8; 32]);
    env.process(&ix, &[Check::success()]);

    // Sole claimant drains exactly the reward pool (never more).
    let p_before = env.get(&p).lamports;
    let ix = env.claim_reward_ix(&pool, &p, &dwell);
    env.process(&ix, &[Check::success()]);
    assert_eq!(
        env.get(&p).lamports,
        p_before + entry_fee,
        "the sole claimant gets the whole pool, exactly"
    );
    assert_eq!(pool::reward_pool_lamports(&env.get(&pool).data).unwrap(), 0);

    // A second claim has no unclaimed dwell left: fail closed, no lamports move.
    let p_before = env.get(&p).lamports;
    let ix = env.claim_reward_ix(&pool, &p, &dwell);
    env.process(&ix, &[Check::err(custom(MirrorPoolError::NothingToClaim))]);
    assert_eq!(
        env.get(&p).lamports,
        p_before,
        "a rejected double-claim moves no lamports"
    );
}

#[test]
fn claim_reward_without_dwell_fails() {
    let mut env = Env::new();
    let (_authority, _payer, pool) = init_pool_with_reward(&mut env, 10, 2, 1_000_000, 10_000);
    let p = Pubkey::new_unique();
    env.fund(p, SOL);
    let dwell = env.dwell_pda(&pool, &p);
    // `p` never committed, so it has no Dwell PDA and nothing to claim.
    let ix = env.claim_reward_ix(&pool, &p, &dwell);
    env.process(&ix, &[Check::err(custom(MirrorPoolError::NothingToClaim))]);
}
