//! Integration tests for the mirror-pool on-chain program.
//!
//! These load the COMPILED SBF program into mollusk's in-process SVM and drive
//! real instructions, so run `cargo build-sbf` first (the DoD build step). The
//! `.so` is located via `SBF_OUT_DIR`, which each test sets to this crate's
//! `target/deploy` so the tests are runnable regardless of the working
//! directory.
//!
//! Coverage:
//!  - INIT_POOL creates a v1 pool; re-init fails (PoolAlreadyInitialized).
//!  - COMMIT bumps the epoch commit count, the pool commitment count, and the
//!    accumulator root; the entry fee lands in the pool.
//!  - SETTLE_EPOCH fails closed before the window closes (EpochNotClosed), below
//!    the k-floor (BelowKFloor), and for a non-authority signer (Unauthorized).
//!  - Happy path: window closed + count >= k_floor settles, creates the
//!    nullifier PDAs, and marks the epoch settled; a second settle fails
//!    (EpochAlreadySettled) and a duplicate nullifier fails (NullifierSpent).

use std::collections::{HashMap, HashSet};

use mollusk_svm::{
    program::keyed_account_for_system_program,
    result::{Check, InstructionResult},
    Mollusk,
};
use solana_account::Account;
use solana_instruction::{AccountMeta, Instruction};
use solana_program_error::ProgramError;
use solana_pubkey::Pubkey;

use mirror_pool::{
    pda::{EPOCH_SEED, NULLIFIER_SEED, POOL_SEED},
    state::{epoch, nullifier, pool},
    wire::tag,
    MirrorPoolError,
};

const SOL: u64 = 1_000_000_000;

/// The committed, known-good membership proof + public inputs (generated by
/// `circuits/build.sh`, validated against groth16-solana 0.2.0). PUBLIC_INPUTS is
/// `[root, nullifierHash, actionHash, epoch]`. Included directly so the ZK tests
/// drive the exact bytes the on-chain verifier consumes.
mod fixture {
    include!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../circuits/artifacts/proof_fixture.rs"
    ));
}

/// The fixture's epoch (public signal [3] = 7).
const ZK_EPOCH: u64 = 7;
/// The escrow amount bound into the fixture's actionHash (see gen_fixture.js).
const ZK_AMOUNT: u64 = 250_000_000;

/// The fresh recipient bound into the fixture's actionHash: bytes 0x01..0x20.
/// `transfer_action_hash(recipient, amount)` over these equals the fixture's
/// actionHash (public signal [2]), which the on-chain SETTLE_ZK recomputes.
fn zk_recipient() -> Pubkey {
    let mut b = [0u8; 32];
    for (i, x) in b.iter_mut().enumerate() {
        *x = (i + 1) as u8;
    }
    Pubkey::new_from_array(b)
}

/// Map a program error code to the `ProgramError` mollusk compares against.
fn custom(e: MirrorPoolError) -> ProgramError {
    ProgramError::Custom(e as u32)
}

/// A tiny stateful harness: owns the Mollusk instance, a persistent account
/// map, and the slot clock. Resulting accounts are written back after every
/// successful instruction so flows (init -> commit -> settle) compose.
struct Env {
    mollusk: Mollusk,
    program_id: Pubkey,
    system_id: Pubkey,
    clock_id: Pubkey,
    accounts: HashMap<Pubkey, Account>,
}

impl Env {
    fn new() -> Self {
        // Point mollusk at the compiled program regardless of cwd.
        std::env::set_var(
            "SBF_OUT_DIR",
            concat!(env!("CARGO_MANIFEST_DIR"), "/target/deploy"),
        );
        let program_id = Pubkey::new_unique();
        let mollusk = Mollusk::new(&program_id, "mirror_pool");
        let system_id = keyed_account_for_system_program().0;
        let clock_id = mollusk.sysvars.keyed_account_for_clock_sysvar().0;
        Env {
            mollusk,
            program_id,
            system_id,
            clock_id,
            accounts: HashMap::new(),
        }
    }

    fn fund(&mut self, key: Pubkey, lamports: u64) {
        self.accounts
            .insert(key, Account::new(lamports, 0, &self.system_id));
    }

    fn get(&self, key: &Pubkey) -> Account {
        self.accounts.get(key).cloned().unwrap_or_default()
    }

    fn warp(&mut self, slot: u64) {
        self.mollusk.warp_to_slot(slot);
    }

    /// Build the deduplicated `(pubkey, account)` list an instruction needs,
    /// sourcing sysvar/builtin accounts fresh and everything else from the map.
    fn accounts_for(&self, ix: &Instruction) -> Vec<(Pubkey, Account)> {
        let mut seen = HashSet::new();
        let mut out = Vec::new();
        for meta in &ix.accounts {
            if !seen.insert(meta.pubkey) {
                continue;
            }
            let account = if meta.pubkey == self.system_id {
                keyed_account_for_system_program().1
            } else if meta.pubkey == self.clock_id {
                self.mollusk.sysvars.keyed_account_for_clock_sysvar().1
            } else {
                self.get(&meta.pubkey)
            };
            out.push((meta.pubkey, account));
        }
        out
    }

    fn process(&mut self, ix: &Instruction, checks: &[Check]) -> InstructionResult {
        let accts = self.accounts_for(ix);
        let result = self
            .mollusk
            .process_and_validate_instruction(ix, &accts, checks);
        for (key, account) in &result.resulting_accounts {
            if *key != self.system_id && *key != self.clock_id {
                self.accounts.insert(*key, account.clone());
            }
        }
        result
    }

    fn pool_pda(&self, authority: &Pubkey) -> Pubkey {
        Pubkey::find_program_address(&[POOL_SEED, authority.as_ref()], &self.program_id).0
    }

    fn epoch_pda(&self, pool: &Pubkey, epoch_id: u64) -> Pubkey {
        Pubkey::find_program_address(
            &[EPOCH_SEED, pool.as_ref(), &epoch_id.to_le_bytes()],
            &self.program_id,
        )
        .0
    }

    fn nf_pda(&self, pool: &Pubkey, epoch_id: u64, nf: &[u8; 32]) -> Pubkey {
        Pubkey::find_program_address(
            &[NULLIFIER_SEED, pool.as_ref(), &epoch_id.to_le_bytes(), nf],
            &self.program_id,
        )
        .0
    }

    fn init_ix(
        &self,
        pool: &Pubkey,
        authority: &Pubkey,
        payer: &Pubkey,
        epoch_slots: u64,
        k_floor: u32,
        entry_fee: u64,
    ) -> Instruction {
        let mut data = Vec::with_capacity(mirror_pool::wire::INIT_POOL_LEN);
        data.push(tag::INIT_POOL);
        data.extend_from_slice(&epoch_slots.to_le_bytes());
        data.extend_from_slice(&k_floor.to_le_bytes());
        data.extend_from_slice(&entry_fee.to_le_bytes());
        Instruction {
            program_id: self.program_id,
            accounts: vec![
                AccountMeta::new(*pool, false),
                AccountMeta::new_readonly(*authority, true),
                AccountMeta::new(*payer, true),
                AccountMeta::new_readonly(self.system_id, false),
            ],
            data,
        }
    }

    fn commit_ix(
        &self,
        pool: &Pubkey,
        epoch_acct: &Pubkey,
        participant: &Pubkey,
        commitment: &[u8; 32],
    ) -> Instruction {
        let mut data = Vec::with_capacity(mirror_pool::wire::COMMIT_LEN);
        data.push(tag::COMMIT);
        data.extend_from_slice(commitment);
        Instruction {
            program_id: self.program_id,
            accounts: vec![
                AccountMeta::new(*pool, false),
                AccountMeta::new(*epoch_acct, false),
                AccountMeta::new(*participant, true),
                AccountMeta::new_readonly(self.system_id, false),
                AccountMeta::new_readonly(self.clock_id, false),
            ],
            data,
        }
    }

    fn commit_deposit_ix(
        &self,
        pool: &Pubkey,
        epoch_acct: &Pubkey,
        depositor: &Pubkey,
        commitment: &[u8; 32],
        amount: u64,
    ) -> Instruction {
        let mut data = Vec::with_capacity(mirror_pool::wire::COMMIT_DEPOSIT_LEN);
        data.push(tag::COMMIT_DEPOSIT);
        data.extend_from_slice(commitment);
        data.extend_from_slice(&amount.to_le_bytes());
        Instruction {
            program_id: self.program_id,
            accounts: vec![
                AccountMeta::new(*pool, false),
                AccountMeta::new(*epoch_acct, false),
                AccountMeta::new(*depositor, true),
                AccountMeta::new_readonly(self.system_id, false),
                AccountMeta::new_readonly(self.clock_id, false),
            ],
            data,
        }
    }

    #[allow(clippy::too_many_arguments)]
    fn settle_zk_ix(
        &self,
        pool: &Pubkey,
        authority: &Pubkey,
        nf_pda: &Pubkey,
        recipient: &Pubkey,
        epoch_id: u64,
        amount: u64,
        public_inputs: &[[u8; 32]; 4],
    ) -> Instruction {
        let mut data = Vec::with_capacity(mirror_pool::wire::SETTLE_ZK_LEN);
        data.push(tag::SETTLE_ZK);
        data.extend_from_slice(&epoch_id.to_le_bytes());
        data.extend_from_slice(&amount.to_le_bytes());
        data.extend_from_slice(&fixture::PROOF_A);
        data.extend_from_slice(&fixture::PROOF_B);
        data.extend_from_slice(&fixture::PROOF_C);
        for pi in public_inputs {
            data.extend_from_slice(pi);
        }
        Instruction {
            program_id: self.program_id,
            accounts: vec![
                AccountMeta::new(*pool, false),
                AccountMeta::new(*authority, true),
                AccountMeta::new(*nf_pda, false),
                AccountMeta::new(*recipient, false),
                AccountMeta::new_readonly(self.system_id, false),
                AccountMeta::new_readonly(self.clock_id, false),
            ],
            data,
        }
    }

    #[allow(clippy::too_many_arguments)]
    fn settle_ix(
        &self,
        pool: &Pubkey,
        epoch_acct: &Pubkey,
        authority: &Pubkey,
        nf_pdas: &[Pubkey],
        nullifiers: &[[u8; 32]],
        payer: &Pubkey,
        epoch_id: u64,
    ) -> Instruction {
        let mut data =
            Vec::with_capacity(mirror_pool::wire::SETTLE_HEADER_LEN + nullifiers.len() * 32);
        data.push(tag::SETTLE_EPOCH);
        data.extend_from_slice(&epoch_id.to_le_bytes());
        data.extend_from_slice(&(nullifiers.len() as u32).to_le_bytes());
        for nf in nullifiers {
            data.extend_from_slice(nf);
        }
        let mut accounts = vec![
            AccountMeta::new(*pool, false),
            AccountMeta::new(*epoch_acct, false),
            AccountMeta::new_readonly(*authority, true),
        ];
        for nf in nf_pdas {
            accounts.push(AccountMeta::new(*nf, false));
        }
        accounts.push(AccountMeta::new(*payer, true));
        accounts.push(AccountMeta::new_readonly(self.system_id, false));
        accounts.push(AccountMeta::new_readonly(self.clock_id, false));
        Instruction {
            program_id: self.program_id,
            accounts,
            data,
        }
    }
}

/// Init a pool and return (authority, payer, pool_pda). `payer` is well funded.
fn init_pool(
    env: &mut Env,
    epoch_slots: u64,
    k_floor: u32,
    entry_fee: u64,
) -> (Pubkey, Pubkey, Pubkey) {
    let authority = Pubkey::new_unique();
    let payer = Pubkey::new_unique();
    env.fund(payer, 100 * SOL);
    // The authority is only a signer here; give it a home account.
    env.fund(authority, SOL);
    let pool = env.pool_pda(&authority);

    let ix = env.init_ix(&pool, &authority, &payer, epoch_slots, k_floor, entry_fee);
    env.process(&ix, &[Check::success()]);
    (authority, payer, pool)
}

#[test]
fn init_pool_creates_v1_and_reinit_fails() {
    let mut env = Env::new();
    let (authority, payer, pool) = init_pool(&mut env, 10, 3, 5_000);

    let acct = env.get(&pool);
    assert_eq!(acct.owner, env.program_id, "pool must be program-owned");
    assert_eq!(acct.data.len(), pool::LEN, "pool must be exactly pool::LEN");
    assert_eq!(pool::version(&acct.data).unwrap(), pool::VERSION_V1);
    assert_eq!(pool::epoch_slots(&acct.data).unwrap(), 10);
    assert_eq!(pool::k_floor(&acct.data).unwrap(), 3);
    assert_eq!(pool::entry_fee(&acct.data).unwrap(), 5_000);
    assert_eq!(pool::commitment_count(&acct.data).unwrap(), 0);
    assert_eq!(&pool::authority(&acct.data).unwrap(), authority.as_ref());
    assert_ne!(
        pool::current_root(&acct.data).unwrap(),
        [0u8; 32],
        "empty-tree root is a non-zero Poseidon zero-ladder"
    );

    // Re-initializing the same pool must fail closed.
    let ix = env.init_ix(&pool, &authority, &payer, 10, 3, 5_000);
    env.process(
        &ix,
        &[Check::err(custom(MirrorPoolError::PoolAlreadyInitialized))],
    );
}

/// The circuit's canonical empty-tree root: `zeros[DEPTH]` where `zeros[0] = 0`
/// and `zeros[i] = Poseidon(zeros[i-1], zeros[i-1])`, computed on the host with
/// `light-poseidon` (the same Poseidon implementation the on-chain
/// `sol_poseidon` syscall is built on) in canonical big-endian bytes.
fn circuit_empty_root() -> [u8; 32] {
    use ark_bn254::Fr;
    use ark_ff::{BigInteger, PrimeField};
    use light_poseidon::{Poseidon, PoseidonHasher};

    let mut z = Fr::from(0u64);
    for _ in 0..mirror_pool::state::merkle::DEPTH {
        let mut h = Poseidon::<Fr>::new_circom(2).unwrap();
        z = h.hash(&[z, z]).unwrap();
    }
    let be = z.into_bigint().to_bytes_be();
    let mut out = [0u8; 32];
    out[32 - be.len()..].copy_from_slice(&be);
    out
}

/// DECISIVE on-chain <-> circuit check: the empty-tree root the program writes
/// at init (via the `sol_poseidon` accumulator) must equal the circuit's
/// `zeros[DEPTH]` reference computed independently with `light-poseidon`. If
/// this passes, the on-chain Merkle hashing is byte-identical to the circuit.
#[test]
fn empty_root_matches_circuit_zero_ladder() {
    let mut env = Env::new();
    let (_authority, _payer, pool) = init_pool(&mut env, 10, 3, 5_000);

    let on_chain = pool::current_root(&env.get(&pool).data).unwrap();
    assert_eq!(
        on_chain,
        circuit_empty_root(),
        "on-chain empty root must equal the circuit's Poseidon zero ladder"
    );
}

#[test]
fn commit_bumps_counts_root_and_collects_fee() {
    let mut env = Env::new();
    let entry_fee = 7_000u64;
    let (_authority, payer, pool) = init_pool(&mut env, 10, 2, entry_fee);

    let pool_lamports_after_init = env.get(&pool).lamports;
    let root0 = pool::current_root(&env.get(&pool).data).unwrap();

    // Commit at slot 3 -> epoch 0.
    env.warp(3);
    let epoch_id = 0u64;
    let epoch_acct = env.epoch_pda(&pool, epoch_id);

    let c1 = [11u8; 32];
    let ix = env.commit_ix(&pool, &epoch_acct, &payer, &c1);
    env.process(&ix, &[Check::success()]);

    let pool_acct = env.get(&pool);
    assert_eq!(pool::commitment_count(&pool_acct.data).unwrap(), 1);
    let root1 = pool::current_root(&pool_acct.data).unwrap();
    assert_ne!(root1, root0, "root must change after the first append");

    let epoch_acct_data = env.get(&epoch_acct);
    assert_eq!(epoch_acct_data.owner, env.program_id);
    assert_eq!(epoch::epoch_id(&epoch_acct_data.data).unwrap(), epoch_id);
    assert_eq!(epoch::commit_count(&epoch_acct_data.data).unwrap(), 1);

    // Second, distinct commit in the same epoch.
    let c2 = [22u8; 32];
    let ix = env.commit_ix(&pool, &epoch_acct, &payer, &c2);
    env.process(&ix, &[Check::success()]);

    let pool_acct = env.get(&pool);
    assert_eq!(pool::commitment_count(&pool_acct.data).unwrap(), 2);
    let root2 = pool::current_root(&pool_acct.data).unwrap();
    assert_ne!(root2, root1, "root must change after the second append");
    assert_eq!(epoch::commit_count(&env.get(&epoch_acct).data).unwrap(), 2);

    // Both entry fees landed in the pool.
    assert_eq!(
        env.get(&pool).lamports,
        pool_lamports_after_init + 2 * entry_fee,
        "entry fees must accumulate in the pool"
    );
}

#[test]
fn settle_before_window_closes_fails() {
    let mut env = Env::new();
    let (authority, payer, pool) = init_pool(&mut env, 10, 2, 0);
    let epoch_id = 0u64;
    let epoch_acct = env.epoch_pda(&pool, epoch_id);

    env.warp(3);
    for c in [[1u8; 32], [2u8; 32]] {
        let ix = env.commit_ix(&pool, &epoch_acct, &payer, &c);
        env.process(&ix, &[Check::success()]);
    }

    // Still inside the window: settle_slot(0) = 10, current slot 5 < 10.
    env.warp(5);
    let nf = [9u8; 32];
    let nf_pda = env.nf_pda(&pool, epoch_id, &nf);
    let ix = env.settle_ix(
        &pool,
        &epoch_acct,
        &authority,
        &[nf_pda],
        &[nf],
        &payer,
        epoch_id,
    );
    env.process(&ix, &[Check::err(custom(MirrorPoolError::EpochNotClosed))]);
}

#[test]
fn settle_below_k_floor_fails() {
    let mut env = Env::new();
    let (authority, payer, pool) = init_pool(&mut env, 10, 3, 0);
    let epoch_id = 0u64;
    let epoch_acct = env.epoch_pda(&pool, epoch_id);

    // Only 2 commits, but k_floor = 3.
    env.warp(3);
    for c in [[1u8; 32], [2u8; 32]] {
        let ix = env.commit_ix(&pool, &epoch_acct, &payer, &c);
        env.process(&ix, &[Check::success()]);
    }

    env.warp(10);
    let nfs = [[9u8; 32], [8u8; 32]];
    let nf_pdas: Vec<Pubkey> = nfs
        .iter()
        .map(|nf| env.nf_pda(&pool, epoch_id, nf))
        .collect();
    let ix = env.settle_ix(
        &pool,
        &epoch_acct,
        &authority,
        &nf_pdas,
        &nfs,
        &payer,
        epoch_id,
    );
    env.process(&ix, &[Check::err(custom(MirrorPoolError::BelowKFloor))]);
}

#[test]
fn settle_by_non_authority_fails() {
    let mut env = Env::new();
    let (_authority, payer, pool) = init_pool(&mut env, 10, 2, 0);
    let epoch_id = 0u64;
    let epoch_acct = env.epoch_pda(&pool, epoch_id);

    env.warp(3);
    for c in [[1u8; 32], [2u8; 32]] {
        let ix = env.commit_ix(&pool, &epoch_acct, &payer, &c);
        env.process(&ix, &[Check::success()]);
    }

    env.warp(10);
    let imposter = Pubkey::new_unique();
    env.fund(imposter, SOL);
    let nf = [9u8; 32];
    let nf_pda = env.nf_pda(&pool, epoch_id, &nf);
    // A different (but validly signing) key must not be able to settle.
    let ix = env.settle_ix(
        &pool,
        &epoch_acct,
        &imposter,
        &[nf_pda],
        &[nf],
        &payer,
        epoch_id,
    );
    env.process(&ix, &[Check::err(custom(MirrorPoolError::Unauthorized))]);
}

#[test]
fn settle_happy_path_then_double_settle_fails() {
    let mut env = Env::new();
    let (authority, payer, pool) = init_pool(&mut env, 10, 2, 0);
    let epoch_id = 0u64;
    let epoch_acct = env.epoch_pda(&pool, epoch_id);

    env.warp(3);
    for c in [[1u8; 32], [2u8; 32]] {
        let ix = env.commit_ix(&pool, &epoch_acct, &payer, &c);
        env.process(&ix, &[Check::success()]);
    }

    // Window closed (>= settle_slot(0) = 10), count (2) >= k_floor (2).
    env.warp(12);
    let nfs = [[9u8; 32], [8u8; 32]];
    let nf_pdas: Vec<Pubkey> = nfs
        .iter()
        .map(|nf| env.nf_pda(&pool, epoch_id, nf))
        .collect();
    let ix = env.settle_ix(
        &pool,
        &epoch_acct,
        &authority,
        &nf_pdas,
        &nfs,
        &payer,
        epoch_id,
    );
    env.process(&ix, &[Check::success()]);

    // Epoch is marked settled and each nullifier PDA now exists (spent).
    assert!(epoch::is_settled(&env.get(&epoch_acct).data).unwrap());
    for nf_pda in &nf_pdas {
        let acct = env.get(nf_pda);
        assert_eq!(acct.owner, env.program_id, "nullifier PDA must be created");
        assert_eq!(acct.data.len(), nullifier::LEN);
        assert_eq!(acct.data[0], nullifier::SPENT);
    }

    // Settling the same epoch again must fail closed.
    let ix = env.settle_ix(
        &pool,
        &epoch_acct,
        &authority,
        &nf_pdas,
        &nfs,
        &payer,
        epoch_id,
    );
    env.process(
        &ix,
        &[Check::err(custom(MirrorPoolError::EpochAlreadySettled))],
    );
}

/// Build a program-owned, initialized Pool account directly (bypassing the
/// frontier build-up) whose recent-root ring already contains the committed
/// fixture's root, and fund it with `lamports`. This is the "set the pool's root
/// history to include the fixture's root" step: a real deposit sequence cannot
/// reproduce the fixture's single-leaf tree, so the test injects the snapshot.
fn build_zk_pool(
    env: &mut Env,
    authority: &Pubkey,
    epoch_slots: u64,
    k_floor: u32,
    lamports: u64,
) -> Pubkey {
    let pool = env.pool_pda(authority);
    let (_, bump) = Pubkey::find_program_address(&[POOL_SEED, authority.as_ref()], &env.program_id);
    let empty_root = circuit_empty_root();
    let mut data = vec![0u8; pool::LEN];
    pool::init(
        &mut data,
        epoch_slots,
        k_floor,
        0,
        &authority.to_bytes(),
        bump,
        &empty_root,
    )
    .unwrap();
    // Inject the fixture's root snapshot (public signal [0]) into the ring.
    pool::record_root_history(&mut data, &fixture::PUBLIC_INPUTS[0]).unwrap();
    assert!(
        pool::is_known_root(&data, &fixture::PUBLIC_INPUTS[0]).unwrap(),
        "fixture root must be a known recent root"
    );
    let mut account = Account::new(lamports, pool::LEN, &env.program_id);
    account.data = data;
    env.accounts.insert(pool, account);
    pool
}

#[test]
fn commit_deposit_escrows_and_appends() {
    let mut env = Env::new();
    let (_authority, payer, pool) = init_pool(&mut env, 10, 2, 0);
    let pool_after_init = env.get(&pool).lamports;
    let root0 = pool::current_root(&env.get(&pool).data).unwrap();

    env.warp(3);
    let epoch_id = 0u64;
    let epoch_acct = env.epoch_pda(&pool, epoch_id);
    let amount = 400_000_000u64;
    let commitment = [7u8; 32];
    let ix = env.commit_deposit_ix(&pool, &epoch_acct, &payer, &commitment, amount);
    env.process(&ix, &[Check::success()]);

    let pool_acct = env.get(&pool);
    assert_eq!(pool::commitment_count(&pool_acct.data).unwrap(), 1);
    let root1 = pool::current_root(&pool_acct.data).unwrap();
    assert_ne!(root1, root0, "root must change after a deposit-commit");
    assert!(
        pool::is_known_root(&pool_acct.data, &root1).unwrap(),
        "the new root must be recorded in the recent-root ring"
    );
    assert_eq!(
        pool_acct.lamports,
        pool_after_init + amount,
        "the escrow must land in the pool"
    );
    assert_eq!(epoch::commit_count(&env.get(&epoch_acct).data).unwrap(), 1);
}

#[test]
fn commit_deposit_zero_amount_fails() {
    let mut env = Env::new();
    let (_authority, payer, pool) = init_pool(&mut env, 10, 2, 0);
    env.warp(3);
    let epoch_acct = env.epoch_pda(&pool, 0);
    let ix = env.commit_deposit_ix(&pool, &epoch_acct, &payer, &[1u8; 32], 0);
    env.process(&ix, &[Check::err(ProgramError::InvalidArgument)]);
}

#[test]
fn settle_zk_verifies_fixture_and_transfers_escrow() {
    let mut env = Env::new();
    let authority = Pubkey::new_unique();
    env.fund(authority, SOL); // pays the nullifier PDA rent
    let pool_start = 5 * SOL + ZK_AMOUNT;
    let pool = build_zk_pool(&mut env, &authority, 10, 2, pool_start);

    let recipient = zk_recipient();
    env.fund(recipient, 0);

    // Window for epoch 7 closes at settle_slot(7) = 8 * 10 = 80.
    env.warp(80);

    let nf = fixture::PUBLIC_INPUTS[1]; // nullifierHash
    let nf_pda = env.nf_pda(&pool, ZK_EPOCH, &nf);
    let ix = env.settle_zk_ix(
        &pool,
        &authority,
        &nf_pda,
        &recipient,
        ZK_EPOCH,
        ZK_AMOUNT,
        &fixture::PUBLIC_INPUTS,
    );
    // The committed fixture proof verifies on-chain and the action executes.
    env.process(&ix, &[Check::success()]);

    assert_eq!(
        env.get(&recipient).lamports,
        ZK_AMOUNT,
        "escrow must be transferred to the fresh recipient"
    );
    assert_eq!(
        env.get(&pool).lamports,
        pool_start - ZK_AMOUNT,
        "pool must be debited by exactly the bound amount"
    );
    let nf_acct = env.get(&nf_pda);
    assert_eq!(
        nf_acct.owner, env.program_id,
        "nullifier PDA must be created"
    );
    assert_eq!(nf_acct.data.len(), nullifier::LEN);
    assert_eq!(nf_acct.data[0], nullifier::SPENT);
}

#[test]
fn settle_zk_rejects_mutated_public_input() {
    let mut env = Env::new();
    let authority = Pubkey::new_unique();
    env.fund(authority, SOL);
    let pool_start = 5 * SOL + ZK_AMOUNT;
    let pool = build_zk_pool(&mut env, &authority, 10, 2, pool_start);
    let recipient = zk_recipient();
    env.fund(recipient, 0);
    env.warp(80);

    // Flip one byte of the nullifierHash public input; derive the nf PDA from the
    // mutated value so the PDA and actionHash checks pass and we reach the proof.
    let mut mutated = fixture::PUBLIC_INPUTS;
    mutated[1][31] ^= 0x01;
    let nf_pda = env.nf_pda(&pool, ZK_EPOCH, &mutated[1]);
    let ix = env.settle_zk_ix(
        &pool, &authority, &nf_pda, &recipient, ZK_EPOCH, ZK_AMOUNT, &mutated,
    );
    env.process(
        &ix,
        &[Check::err(custom(MirrorPoolError::ProofVerificationFailed))],
    );

    // Fail-closed: no escrow moved, no recipient funding, no nullifier PDA.
    assert_eq!(env.get(&recipient).lamports, 0);
    assert_eq!(env.get(&pool).lamports, pool_start);
    assert_eq!(
        env.get(&nf_pda).owner,
        Pubkey::default(),
        "nullifier PDA must not be created on a rejected proof"
    );
}

#[test]
fn settle_zk_wrong_recipient_action_hash_mismatch() {
    let mut env = Env::new();
    let authority = Pubkey::new_unique();
    env.fund(authority, SOL);
    let pool_start = 5 * SOL + ZK_AMOUNT;
    let pool = build_zk_pool(&mut env, &authority, 10, 2, pool_start);
    // A recipient that is NOT the one bound into the fixture's actionHash: a
    // relay trying to redirect the escrow. The recompute check must catch it.
    let wrong_recipient = Pubkey::new_unique();
    env.fund(wrong_recipient, 0);
    env.warp(80);

    let nf = fixture::PUBLIC_INPUTS[1];
    let nf_pda = env.nf_pda(&pool, ZK_EPOCH, &nf);
    let ix = env.settle_zk_ix(
        &pool,
        &authority,
        &nf_pda,
        &wrong_recipient,
        ZK_EPOCH,
        ZK_AMOUNT,
        &fixture::PUBLIC_INPUTS,
    );
    env.process(
        &ix,
        &[Check::err(custom(MirrorPoolError::ActionHashMismatch))],
    );
    assert_eq!(env.get(&wrong_recipient).lamports, 0, "no redirect");
    assert_eq!(env.get(&pool).lamports, pool_start);
}

#[test]
fn settle_zk_replay_fails_nullifier_spent() {
    let mut env = Env::new();
    let authority = Pubkey::new_unique();
    env.fund(authority, SOL);
    let pool_start = 5 * SOL + ZK_AMOUNT;
    let pool = build_zk_pool(&mut env, &authority, 10, 2, pool_start);
    let recipient = zk_recipient();
    env.fund(recipient, 0);
    env.warp(80);

    let nf = fixture::PUBLIC_INPUTS[1];
    let nf_pda = env.nf_pda(&pool, ZK_EPOCH, &nf);
    let ix = env.settle_zk_ix(
        &pool,
        &authority,
        &nf_pda,
        &recipient,
        ZK_EPOCH,
        ZK_AMOUNT,
        &fixture::PUBLIC_INPUTS,
    );
    env.process(&ix, &[Check::success()]);

    // Re-submitting the same nullifier fails closed: its PDA already exists.
    let ix2 = env.settle_zk_ix(
        &pool,
        &authority,
        &nf_pda,
        &recipient,
        ZK_EPOCH,
        ZK_AMOUNT,
        &fixture::PUBLIC_INPUTS,
    );
    env.process(&ix2, &[Check::err(custom(MirrorPoolError::NullifierSpent))]);
}

#[test]
fn settle_zk_before_window_closes_fails() {
    let mut env = Env::new();
    let authority = Pubkey::new_unique();
    env.fund(authority, SOL);
    let pool_start = 5 * SOL + ZK_AMOUNT;
    let pool = build_zk_pool(&mut env, &authority, 10, 2, pool_start);
    let recipient = zk_recipient();
    env.fund(recipient, 0);

    // settle_slot(7) = 80; still inside the window at slot 50.
    env.warp(50);
    let nf = fixture::PUBLIC_INPUTS[1];
    let nf_pda = env.nf_pda(&pool, ZK_EPOCH, &nf);
    let ix = env.settle_zk_ix(
        &pool,
        &authority,
        &nf_pda,
        &recipient,
        ZK_EPOCH,
        ZK_AMOUNT,
        &fixture::PUBLIC_INPUTS,
    );
    env.process(&ix, &[Check::err(custom(MirrorPoolError::EpochNotClosed))]);
}

#[test]
fn settle_zk_by_non_authority_fails() {
    let mut env = Env::new();
    let authority = Pubkey::new_unique();
    env.fund(authority, SOL);
    let pool_start = 5 * SOL + ZK_AMOUNT;
    let pool = build_zk_pool(&mut env, &authority, 10, 2, pool_start);
    let recipient = zk_recipient();
    env.fund(recipient, 0);
    env.warp(80);

    let imposter = Pubkey::new_unique();
    env.fund(imposter, SOL);
    let nf = fixture::PUBLIC_INPUTS[1];
    let nf_pda = env.nf_pda(&pool, ZK_EPOCH, &nf);
    let ix = env.settle_zk_ix(
        &pool,
        &imposter,
        &nf_pda,
        &recipient,
        ZK_EPOCH,
        ZK_AMOUNT,
        &fixture::PUBLIC_INPUTS,
    );
    env.process(&ix, &[Check::err(custom(MirrorPoolError::Unauthorized))]);
}

#[test]
fn settle_zk_unknown_root_fails() {
    let mut env = Env::new();
    let authority = Pubkey::new_unique();
    env.fund(authority, SOL);
    let pool_start = 5 * SOL + ZK_AMOUNT;
    // A pool whose ring does NOT contain the fixture root (only the empty root).
    let pool = {
        let pool = env.pool_pda(&authority);
        let (_, bump) =
            Pubkey::find_program_address(&[POOL_SEED, authority.as_ref()], &env.program_id);
        let empty_root = circuit_empty_root();
        let mut data = vec![0u8; pool::LEN];
        pool::init(
            &mut data,
            10,
            2,
            0,
            &authority.to_bytes(),
            bump,
            &empty_root,
        )
        .unwrap();
        let mut account = Account::new(pool_start, pool::LEN, &env.program_id);
        account.data = data;
        env.accounts.insert(pool, account);
        pool
    };
    let recipient = zk_recipient();
    env.fund(recipient, 0);
    env.warp(80);

    let nf = fixture::PUBLIC_INPUTS[1];
    let nf_pda = env.nf_pda(&pool, ZK_EPOCH, &nf);
    let ix = env.settle_zk_ix(
        &pool,
        &authority,
        &nf_pda,
        &recipient,
        ZK_EPOCH,
        ZK_AMOUNT,
        &fixture::PUBLIC_INPUTS,
    );
    env.process(&ix, &[Check::err(custom(MirrorPoolError::RootNotKnown))]);
}

#[test]
fn settle_duplicate_nullifier_fails() {
    let mut env = Env::new();
    let (authority, payer, pool) = init_pool(&mut env, 10, 2, 0);
    let epoch_id = 0u64;
    let epoch_acct = env.epoch_pda(&pool, epoch_id);

    env.warp(3);
    for c in [[1u8; 32], [2u8; 32]] {
        let ix = env.commit_ix(&pool, &epoch_acct, &payer, &c);
        env.process(&ix, &[Check::success()]);
    }

    env.warp(10);
    // The same nullifier appears twice in one settle: the second create sees an
    // already-spent (program-owned) PDA.
    let nf = [9u8; 32];
    let nf_pda = env.nf_pda(&pool, epoch_id, &nf);
    let ix = env.settle_ix(
        &pool,
        &epoch_acct,
        &authority,
        &[nf_pda, nf_pda],
        &[nf, nf],
        &payer,
        epoch_id,
    );
    env.process(&ix, &[Check::err(custom(MirrorPoolError::NullifierSpent))]);
}
