//! Integration tests for the OPT-IN disclosure layer: on-chain viewing keys and
//! sealed disclosure records.
//!
//! These load the COMPILED SBF program into mollusk's in-process SVM and drive
//! real instructions, so run `cargo build-sbf` first.
//!
//! Coverage:
//!  - REGISTER_VIEWING_KEY creates the PDA, binds the signing authority, and
//!    rotates only for that authority; a body byte, a wrong PDA, a foreign signer
//!    and a degenerate key are all rejected.
//!  - PUBLISH_DISCLOSURE accepts a well-formed record and stores the fields it
//!    recomputed, not the ones it was handed.
//!  - PUBLISH_DISCLOSURE REJECTS the two failure modes the rival design has: an
//!    unauthenticated publisher (no recipient signature) and a SQUAT on another
//!    user's settlement (the slot is derived from the signer, so it is not
//!    reachable), plus an unregistered or forged reader, a structurally invalid
//!    sealed blob, an off-denomination amount, a non-pool account, and a second
//!    write to the same record.
//!  - The whole layer is opt-in: SETTLE_ZK settles the committed fixture with no
//!    viewing key and no record anywhere, and the record published for that same
//!    action reproduces, off-chain, the exact nullifier the settle burned.

use std::collections::{HashMap, HashSet};

use mollusk_svm::{
    program::keyed_account_for_system_program,
    result::{Check, InstructionResult},
    Mollusk,
};
use solana_account::Account;
use solana_instruction::{AccountMeta, Instruction};
use solana_program_error::ProgramError;
use solana_pubkey::Pubkey;

use mirror_pool::{
    pda::{DISCLOSURE_SEED, NULLIFIER_SEED, POOL_SEED, VIEWING_KEY_SEED},
    state::{disclosure, pool, viewing_key},
    wire::tag,
    MirrorPoolError,
};

const SOL: u64 = 1_000_000_000;

/// The committed, known-good MEMBERSHIP proof + public inputs (generated by
/// `circuits/build.sh`). PUBLIC_INPUTS is
/// `[root, nullifierHash, actionHash, epoch]`.
mod fixture {
    include!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../circuits/artifacts/proof_fixture.rs"
    ));
}

/// Shared helpers for the write-once, digest-pinned verifying-key registry.
#[allow(dead_code)]
mod vk_fixture {
    include!("fixtures/vk_install.rs");
}

/// The fixture's epoch (public signal [3] = 7; see gen_fixture.js).
const ZK_EPOCH: u64 = 7;
/// The escrow amount bound into the fixture's actionHash.
const ZK_AMOUNT: u64 = 250_000_000;

/// The fixture's note secret, `111122223333444455556666777788889999` as a
/// canonical big-endian BN254 scalar (see `circuits/gen_fixture.js`). This is
/// what a real user would seal to their auditor, and disclosing it here lets the
/// test check that the auditor recomputes the SAME nullifier the on-chain settle
/// burns two lines later.
const FIXTURE_SECRET: [u8; 32] = [
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x15, 0x66, 0xbf, 0xa4, 0x9d, 0x36, 0x82, 0x8e, 0x17, 0xeb, 0x19, 0xd1, 0x9a, 0x3b, 0x8f,
];

/// The fresh recipient bound into the fixture's actionHash: bytes 0x01..0x20.
fn zk_recipient() -> Pubkey {
    let mut b = [0u8; 32];
    for (i, x) in b.iter_mut().enumerate() {
        *x = (i + 1) as u8;
    }
    Pubkey::new_from_array(b)
}

/// Map a program error code to the `ProgramError` mollusk compares against.
fn custom(e: MirrorPoolError) -> ProgramError {
    ProgramError::Custom(e as u32)
}

/// The circuit's empty-tree root, recomputed on the host with `light-poseidon`.
fn circuit_empty_root() -> [u8; 32] {
    use ark_bn254::Fr;
    use ark_ff::{BigInteger, PrimeField};
    use light_poseidon::{Poseidon, PoseidonHasher};

    let mut z = Fr::from(0u64);
    for _ in 0..mirror_pool::state::merkle::DEPTH {
        let mut h = Poseidon::<Fr>::new_circom(2).unwrap();
        z = h.hash(&[z, z]).unwrap();
    }
    let be = z.into_bigint().to_bytes_be();
    let mut out = [0u8; 32];
    out[32 - be.len()..].copy_from_slice(&be);
    out
}

/// A deterministic 32-byte value from one seed byte (test key material).
fn bytes(seed: u8) -> [u8; 32] {
    let mut b = [0u8; 32];
    for (i, x) in b.iter_mut().enumerate() {
        *x = seed.wrapping_add(i as u8).wrapping_mul(31).wrapping_add(7);
    }
    b
}

/// A real X25519 viewing keypair, built through the host crate the CLI uses.
fn viewing_keypair(seed: u8) -> mirror_core::encrypted_note::ViewingKeypair {
    mirror_core::encrypted_note::ViewingKeypair::from_secret(bytes(seed))
}

/// A tiny stateful harness (the same shape `integration.rs` uses).
struct Env {
    mollusk: Mollusk,
    program_id: Pubkey,
    system_id: Pubkey,
    clock_id: Pubkey,
    accounts: HashMap<Pubkey, Account>,
}

impl Env {
    fn new() -> Self {
        std::env::set_var(
            "SBF_OUT_DIR",
            concat!(env!("CARGO_MANIFEST_DIR"), "/target/deploy"),
        );
        let program_id = Pubkey::new_unique();
        let mollusk = Mollusk::new(&program_id, "mirror_pool");
        let system_id = keyed_account_for_system_program().0;
        let clock_id = mollusk.sysvars.keyed_account_for_clock_sysvar().0;
        Env {
            mollusk,
            program_id,
            system_id,
            clock_id,
            accounts: HashMap::new(),
        }
    }

    fn fund(&mut self, key: Pubkey, lamports: u64) {
        self.accounts
            .insert(key, Account::new(lamports, 0, &self.system_id));
    }

    fn get(&self, key: &Pubkey) -> Account {
        self.accounts.get(key).cloned().unwrap_or_default()
    }

    fn warp(&mut self, slot: u64) {
        self.mollusk.warp_to_slot(slot);
    }

    fn accounts_for(&self, ix: &Instruction) -> Vec<(Pubkey, Account)> {
        let mut seen = HashSet::new();
        let mut out = Vec::new();
        for meta in &ix.accounts {
            if !seen.insert(meta.pubkey) {
                continue;
            }
            let account = if meta.pubkey == self.system_id {
                keyed_account_for_system_program().1
            } else if meta.pubkey == self.clock_id {
                self.mollusk.sysvars.keyed_account_for_clock_sysvar().1
            } else {
                self.get(&meta.pubkey)
            };
            out.push((meta.pubkey, account));
        }
        out
    }

    fn process(&mut self, ix: &Instruction, checks: &[Check]) -> InstructionResult {
        let accts = self.accounts_for(ix);
        let result = self
            .mollusk
            .process_and_validate_instruction(ix, &accts, checks);
        for (key, account) in &result.resulting_accounts {
            if *key != self.system_id && *key != self.clock_id {
                self.accounts.insert(*key, account.clone());
            }
        }
        result
    }

    fn pool_pda(&self, authority: &Pubkey) -> Pubkey {
        Pubkey::find_program_address(&[POOL_SEED, authority.as_ref()], &self.program_id).0
    }

    fn viewkey_pda(&self, authority: &Pubkey) -> Pubkey {
        Pubkey::find_program_address(&[VIEWING_KEY_SEED, authority.as_ref()], &self.program_id).0
    }

    fn disclosure_pda(
        &self,
        pool: &Pubkey,
        action_hash: &[u8; 32],
        view_pub: &[u8; 32],
    ) -> Pubkey {
        Pubkey::find_program_address(
            &[DISCLOSURE_SEED, pool.as_ref(), action_hash, view_pub],
            &self.program_id,
        )
        .0
    }

    fn nf_pda(&self, pool: &Pubkey, epoch_id: u64, nf: &[u8; 32]) -> Pubkey {
        Pubkey::find_program_address(
            &[NULLIFIER_SEED, pool.as_ref(), &epoch_id.to_le_bytes(), nf],
            &self.program_id,
        )
        .0
    }

    fn register_ix(
        &self,
        viewkey: &Pubkey,
        authority: &Pubkey,
        payer: &Pubkey,
        view_pub: &[u8; 32],
    ) -> Instruction {
        let mut data = Vec::with_capacity(mirror_pool::wire::REGISTER_VIEWING_KEY_LEN);
        data.push(tag::REGISTER_VIEWING_KEY);
        data.extend_from_slice(view_pub);
        Instruction {
            program_id: self.program_id,
            accounts: vec![
                AccountMeta::new(*viewkey, false),
                AccountMeta::new_readonly(*authority, true),
                AccountMeta::new(*payer, true),
                AccountMeta::new_readonly(self.system_id, false),
            ],
            data,
        }
    }

    #[allow(clippy::too_many_arguments)]
    fn publish_ix(
        &self,
        record: &Pubkey,
        pool: &Pubkey,
        recipient: &Pubkey,
        recipient_signs: bool,
        auditor_viewkey: &Pubkey,
        payer: &Pubkey,
        amount: u64,
        blob: &[u8],
    ) -> Instruction {
        let mut data = Vec::with_capacity(mirror_pool::wire::PUBLISH_DISCLOSURE_LEN);
        data.push(tag::PUBLISH_DISCLOSURE);
        data.extend_from_slice(&amount.to_le_bytes());
        data.extend_from_slice(blob);
        Instruction {
            program_id: self.program_id,
            accounts: vec![
                AccountMeta::new(*record, false),
                AccountMeta::new_readonly(*pool, false),
                AccountMeta::new_readonly(*recipient, recipient_signs),
                AccountMeta::new_readonly(*auditor_viewkey, false),
                AccountMeta::new(*payer, true),
                AccountMeta::new_readonly(self.system_id, false),
            ],
            data,
        }
    }

    fn settle_zk_ix(
        &self,
        pool: &Pubkey,
        authority: &Pubkey,
        nf_pda: &Pubkey,
        recipient: &Pubkey,
    ) -> Instruction {
        let mut data = Vec::with_capacity(mirror_pool::wire::SETTLE_ZK_LEN);
        data.push(tag::SETTLE_ZK);
        data.extend_from_slice(&ZK_EPOCH.to_le_bytes());
        data.extend_from_slice(&ZK_AMOUNT.to_le_bytes());
        data.extend_from_slice(&fixture::PROOF_A);
        data.extend_from_slice(&fixture::PROOF_B);
        data.extend_from_slice(&fixture::PROOF_C);
        for pi in fixture::PUBLIC_INPUTS.iter() {
            data.extend_from_slice(pi);
        }
        Instruction {
            program_id: self.program_id,
            accounts: vec![
                AccountMeta::new(*pool, false),
                AccountMeta::new(*authority, true),
                AccountMeta::new(*nf_pda, false),
                AccountMeta::new(*recipient, false),
                AccountMeta::new_readonly(self.system_id, false),
                AccountMeta::new_readonly(self.clock_id, false),
                AccountMeta::new_readonly(
                    vk_fixture::vk_registry_pda(&self.program_id, mirror_pool::wire::CIRCUIT_MEMBERSHIP),
                    false,
                ),
            ],
            data,
        }
    }

    /// Install a circuit's pinned verifying key through the REAL `INIT_VK`.
    fn install_vk(&mut self, circuit_id: u8) -> Pubkey {
        let payer = Pubkey::new_unique();
        self.fund(payer, SOL);
        let vk = vk_fixture::canonical_vk(circuit_id);
        let ix = vk_fixture::init_vk_ix(&self.program_id, &self.system_id, &payer, circuit_id, &vk);
        self.process(&ix, &[Check::success()]);
        vk_fixture::vk_registry_pda(&self.program_id, circuit_id)
    }

    /// Register a viewing key for a fresh authority and return
    /// `(authority, viewkey_pda)`.
    fn register_auditor(&mut self, view_pub: &[u8; 32]) -> (Pubkey, Pubkey) {
        let authority = Pubkey::new_unique();
        self.fund(authority, SOL);
        let viewkey = self.viewkey_pda(&authority);
        let ix = self.register_ix(&viewkey, &authority, &authority, view_pub);
        self.process(&ix, &[Check::success()]);
        (authority, viewkey)
    }
}

/// Hand-build an initialized Pool whose recent-root ring already contains the
/// committed fixture's root, and fund it. A real deposit sequence cannot
/// reproduce the fixture's exact tree, so the test injects the snapshot - the
/// same technique `integration.rs` uses for SettleZk.
fn build_zk_pool(env: &mut Env, authority: &Pubkey, epoch_slots: u64, lamports: u64) -> Pubkey {
    let pool = env.pool_pda(authority);
    let (_, bump) = Pubkey::find_program_address(&[POOL_SEED, authority.as_ref()], &env.program_id);
    let mut data = vec![0u8; pool::LEN];
    pool::init(
        &mut data,
        epoch_slots,
        2,
        0,
        0,
        ZK_AMOUNT,
        &authority.to_bytes(),
        bump,
        &circuit_empty_root(),
    )
    .unwrap();
    pool::record_root_history(&mut data, &fixture::PUBLIC_INPUTS[0]).unwrap();
    let mut account = Account::new(lamports, pool::LEN, &env.program_id);
    account.data = data;
    env.accounts.insert(pool, account);
    pool
}

/// The `action_hash` the program will recompute for `(recipient, amount)`,
/// derived here with the HOST implementation so the test also pins that the two
/// agree.
fn host_action_hash(recipient: &Pubkey, amount: u64) -> [u8; 32] {
    mirror_core::transfer_action_hash(&recipient.to_bytes(), amount)
}

// ---------------------------------------------------------------------------
// REGISTER_VIEWING_KEY
// ---------------------------------------------------------------------------

/// The directory works: a signer publishes a key under their own address, and
/// the account records the authority the runtime saw rather than anything the
/// caller could name.
#[test]
fn register_viewing_key_binds_the_signing_authority() {
    let mut env = Env::new();
    let authority = Pubkey::new_unique();
    env.fund(authority, SOL);
    let viewkey = env.viewkey_pda(&authority);
    let view_pub = viewing_keypair(1).public();

    let ix = env.register_ix(&viewkey, &authority, &authority, &view_pub);
    env.process(&ix, &[Check::success()]);

    let data = env.get(&viewkey).data;
    assert_eq!(data.len(), viewing_key::LEN);
    assert!(viewing_key::is_initialized(&data).unwrap());
    assert_eq!(viewing_key::authority(&data).unwrap(), authority.to_bytes());
    assert_eq!(viewing_key::viewing_pub(&data).unwrap(), view_pub);
    assert_eq!(viewing_key::rotation_count(&data).unwrap(), 0);
    assert_eq!(env.get(&viewkey).owner, env.program_id);
}

/// Rotation is allowed for the owner and only the owner. The rotated key lands
/// at the SAME account, so nothing an old record points at is disturbed (records
/// are keyed by the key, not by the authority).
#[test]
fn register_viewing_key_rotates_only_for_its_own_authority() {
    let mut env = Env::new();
    let authority = Pubkey::new_unique();
    let stranger = Pubkey::new_unique();
    env.fund(authority, SOL);
    env.fund(stranger, SOL);
    let viewkey = env.viewkey_pda(&authority);

    let first = viewing_keypair(2).public();
    let ix = env.register_ix(&viewkey, &authority, &authority, &first);
    env.process(&ix, &[Check::success()]);

    // The owner rotates.
    let second = viewing_keypair(3).public();
    let ix = env.register_ix(&viewkey, &authority, &authority, &second);
    env.process(&ix, &[Check::success()]);
    let data = env.get(&viewkey).data;
    assert_eq!(viewing_key::viewing_pub(&data).unwrap(), second);
    assert_eq!(viewing_key::rotation_count(&data).unwrap(), 1);

    // A stranger signing for the SAME account cannot: the account is not the PDA
    // of their address, so the derivation fails before anything is written.
    let hostile = viewing_keypair(4).public();
    let ix = env.register_ix(&viewkey, &stranger, &stranger, &hostile);
    env.process(&ix, &[Check::err(custom(MirrorPoolError::InvalidPda))]);
    let data = env.get(&viewkey).data;
    assert_eq!(
        viewing_key::viewing_pub(&data).unwrap(),
        second,
        "a foreign signer must not overwrite a registration"
    );
}

/// The anti-squat property, stated as a test: a registration can only ever land
/// under the address that signed it, so there is no slot for anyone else to
/// take. The stranger here tries to occupy the victim's directory entry BEFORE
/// the victim ever registers - the first-come-first-served attack the rival
/// design admits - and cannot derive the address.
#[test]
fn register_viewing_key_cannot_squat_another_address() {
    let mut env = Env::new();
    let victim = Pubkey::new_unique();
    let squatter = Pubkey::new_unique();
    env.fund(victim, SOL);
    env.fund(squatter, SOL);
    let victim_slot = env.viewkey_pda(&victim);

    let ix = env.register_ix(&victim_slot, &squatter, &squatter, &viewing_keypair(5).public());
    env.process(&ix, &[Check::err(custom(MirrorPoolError::InvalidPda))]);
    assert!(
        env.get(&victim_slot).data.is_empty(),
        "the victim's slot must still be empty"
    );

    // And the victim can still take their own slot afterwards.
    let mine = viewing_keypair(6).public();
    let ix = env.register_ix(&victim_slot, &victim, &victim, &mine);
    env.process(&ix, &[Check::success()]);
    assert_eq!(
        viewing_key::viewing_pub(&env.get(&victim_slot).data).unwrap(),
        mine
    );
}

/// Degenerate keys are refused: small-order points (whose ECDH output is
/// independent of the peer's secret, so anything sealed to them is public) and
/// non-canonical encodings (which would alias to a second PDA for one key).
#[test]
fn register_viewing_key_rejects_degenerate_keys() {
    let mut env = Env::new();
    let authority = Pubkey::new_unique();
    env.fund(authority, SOL);
    let viewkey = env.viewkey_pda(&authority);

    let mut bad_keys: Vec<[u8; 32]> = vec![
        // The identity / order-1 / order-2 / order-8 points.
        [0u8; 32],
        {
            let mut k = [0u8; 32];
            k[0] = 1;
            k
        },
        {
            let mut k = [0xffu8; 32];
            k[0] = 0xec;
            k[31] = 0x7f;
            k
        },
    ];
    // Non-canonical: high bit set, and p itself.
    let mut high_bit = viewing_keypair(7).public();
    high_bit[31] |= 0x80;
    bad_keys.push(high_bit);
    let mut p = [0xffu8; 32];
    p[0] = 0xed;
    p[31] = 0x7f;
    bad_keys.push(p);

    for key in &bad_keys {
        let ix = env.register_ix(&viewkey, &authority, &authority, key);
        env.process(&ix, &[Check::err(custom(MirrorPoolError::InvalidViewingKey))]);
    }
    assert!(env.get(&viewkey).data.is_empty());

    // A real key from the same generator the CLI uses is accepted.
    let good = viewing_keypair(7).public();
    let ix = env.register_ix(&viewkey, &authority, &authority, &good);
    env.process(&ix, &[Check::success()]);
}

/// Fail closed on shape: this instruction's body is exactly the key.
#[test]
fn register_viewing_key_rejects_a_malformed_body() {
    let mut env = Env::new();
    let authority = Pubkey::new_unique();
    env.fund(authority, SOL);
    let viewkey = env.viewkey_pda(&authority);
    let view_pub = viewing_keypair(8).public();

    for extra in [0usize, 2] {
        let mut ix = env.register_ix(&viewkey, &authority, &authority, &view_pub);
        if extra == 0 {
            ix.data.pop();
        } else {
            ix.data.extend_from_slice(&[0u8; 2]);
        }
        env.process(
            &ix,
            &[Check::err(custom(MirrorPoolError::MalformedInstruction))],
        );
    }
}

// ---------------------------------------------------------------------------
// PUBLISH_DISCLOSURE
// ---------------------------------------------------------------------------

/// A well-formed record lands, and every field the account keeps is one the
/// PROGRAM derived: the action hash it recomputed from the signing recipient,
/// and the auditor identity + key it read out of the registry account.
#[test]
fn publish_disclosure_stores_what_the_program_recomputed() {
    let mut env = Env::new();
    let auditor_kp = viewing_keypair(10);
    let (auditor, auditor_viewkey) = env.register_auditor(&auditor_kp.public());

    let pool_authority = Pubkey::new_unique();
    let pool = build_zk_pool(&mut env, &pool_authority, 10, 50 * SOL);
    let recipient = zk_recipient();
    env.fund(recipient, SOL);

    let blob = mirror_core::disclosure::seal(
        &auditor_kp.public(),
        mirror_core::Epoch(ZK_EPOCH),
        &mirror_core::Secret(FIXTURE_SECRET),
    );
    let action_hash = host_action_hash(&recipient, ZK_AMOUNT);
    let record = env.disclosure_pda(&pool, &action_hash, &auditor_kp.public());

    let ix = env.publish_ix(
        &record,
        &pool,
        &recipient,
        true,
        &auditor_viewkey,
        &recipient,
        ZK_AMOUNT,
        &blob,
    );
    env.process(&ix, &[Check::success()]);

    let data = env.get(&record).data;
    assert_eq!(data.len(), disclosure::LEN);
    assert!(disclosure::is_initialized(&data).unwrap());
    assert_eq!(disclosure::pool(&data).unwrap(), pool.to_bytes());
    assert_eq!(disclosure::recipient(&data).unwrap(), recipient.to_bytes());
    assert_eq!(disclosure::auditor(&data).unwrap(), auditor.to_bytes());
    assert_eq!(
        disclosure::auditor_view_pub(&data).unwrap(),
        auditor_kp.public()
    );
    assert_eq!(disclosure::amount(&data).unwrap(), ZK_AMOUNT);
    assert_eq!(disclosure::blob(&data).unwrap(), &blob[..]);

    // The on-chain Poseidon recomputation agrees with the host's, and with the
    // committed fixture's actionHash public input: this record is about a
    // statement the settle path really can verify.
    assert_eq!(disclosure::action_hash(&data).unwrap(), action_hash);
    assert_eq!(
        disclosure::action_hash(&data).unwrap(),
        fixture::PUBLIC_INPUTS[2],
        "the recomputed action hash must equal the proof's actionHash"
    );

    // And the reader - and only the reader - can open it.
    let opened = mirror_core::disclosure::open(&auditor_kp.to_secret_bytes(), &blob)
        .expect("the auditor must open their own record");
    let stranger = viewing_keypair(11);
    assert!(mirror_core::disclosure::open(&stranger.to_secret_bytes(), &blob).is_none());
    let action = mirror_core::disclosure::derive_action(&opened, &action_hash);
    assert_eq!(
        action.nullifier.0,
        fixture::PUBLIC_INPUTS[1],
        "the disclosure must reproduce the settlement's nullifier hash"
    );
}

/// The publisher must SIGN. Without the recipient's signature there is nothing
/// tying the record to the settlement it claims, which is exactly the hole in a
/// design where any payer may register any commitment.
#[test]
fn publish_disclosure_requires_the_recipient_signature() {
    let mut env = Env::new();
    let auditor_kp = viewing_keypair(12);
    let (_auditor, auditor_viewkey) = env.register_auditor(&auditor_kp.public());
    let pool_authority = Pubkey::new_unique();
    let pool = build_zk_pool(&mut env, &pool_authority, 10, 50 * SOL);
    let recipient = zk_recipient();
    let payer = Pubkey::new_unique();
    env.fund(payer, SOL);

    let blob = mirror_core::disclosure::seal(
        &auditor_kp.public(),
        mirror_core::Epoch(ZK_EPOCH),
        &mirror_core::Secret(FIXTURE_SECRET),
    );
    let action_hash = host_action_hash(&recipient, ZK_AMOUNT);
    let record = env.disclosure_pda(&pool, &action_hash, &auditor_kp.public());

    let ix = env.publish_ix(
        &record,
        &pool,
        &recipient,
        false, // recipient does not sign
        &auditor_viewkey,
        &payer,
        ZK_AMOUNT,
        &blob,
    );
    env.process(
        &ix,
        &[Check::err(ProgramError::MissingRequiredSignature)],
    );
    assert!(env.get(&record).data.is_empty());
}

/// The squat test. An attacker who has read the chain knows the victim's
/// settlement recipient and amount, so they know the record's address - and
/// still cannot write it, because the address is derived from the SIGNER. When
/// they sign for themselves the derivation lands on THEIR slot, not the
/// victim's, so the victim's record is untouched and still available.
#[test]
fn publish_disclosure_cannot_squat_another_recipients_settlement() {
    let mut env = Env::new();
    let auditor_kp = viewing_keypair(13);
    let (_auditor, auditor_viewkey) = env.register_auditor(&auditor_kp.public());
    let pool_authority = Pubkey::new_unique();
    let pool = build_zk_pool(&mut env, &pool_authority, 10, 50 * SOL);

    let victim = zk_recipient();
    env.fund(victim, SOL);
    let attacker = Pubkey::new_unique();
    env.fund(attacker, SOL);

    let victim_action = host_action_hash(&victim, ZK_AMOUNT);
    let victim_record = env.disclosure_pda(&pool, &victim_action, &auditor_kp.public());
    let junk = mirror_core::disclosure::seal(
        &auditor_kp.public(),
        mirror_core::Epoch(ZK_EPOCH),
        &mirror_core::Secret([9u8; 32]),
    );

    // (a) The attacker signs for themselves and aims at the victim's slot.
    let ix = env.publish_ix(
        &victim_record,
        &pool,
        &attacker,
        true,
        &auditor_viewkey,
        &attacker,
        ZK_AMOUNT,
        &junk,
    );
    env.process(&ix, &[Check::err(custom(MirrorPoolError::InvalidPda))]);

    // (b) The attacker names the victim as recipient without their signature.
    let ix = env.publish_ix(
        &victim_record,
        &pool,
        &victim,
        false,
        &auditor_viewkey,
        &attacker,
        ZK_AMOUNT,
        &junk,
    );
    env.process(
        &ix,
        &[Check::err(ProgramError::MissingRequiredSignature)],
    );
    assert!(
        env.get(&victim_record).data.is_empty(),
        "the victim's slot must still be free"
    );

    // (c) The attacker CAN publish under their own address. That record is about
    // a settlement to themselves and occupies nobody else's slot.
    let attacker_action = host_action_hash(&attacker, ZK_AMOUNT);
    let attacker_record = env.disclosure_pda(&pool, &attacker_action, &auditor_kp.public());
    let ix = env.publish_ix(
        &attacker_record,
        &pool,
        &attacker,
        true,
        &auditor_viewkey,
        &attacker,
        ZK_AMOUNT,
        &junk,
    );
    env.process(&ix, &[Check::success()]);
    assert_ne!(attacker_record, victim_record);

    // (d) And the victim can still publish theirs.
    let blob = mirror_core::disclosure::seal(
        &auditor_kp.public(),
        mirror_core::Epoch(ZK_EPOCH),
        &mirror_core::Secret(FIXTURE_SECRET),
    );
    let ix = env.publish_ix(
        &victim_record,
        &pool,
        &victim,
        true,
        &auditor_viewkey,
        &victim,
        ZK_AMOUNT,
        &blob,
    );
    env.process(&ix, &[Check::success()]);
    assert_eq!(
        disclosure::recipient(&env.get(&victim_record).data).unwrap(),
        victim.to_bytes()
    );
}

/// The record's address is a function of the AMOUNT too, so a caller cannot get
/// a record for one action into the slot of another by changing the number.
#[test]
fn publish_disclosure_binds_the_amount_into_the_address() {
    let mut env = Env::new();
    let auditor_kp = viewing_keypair(14);
    let (_auditor, auditor_viewkey) = env.register_auditor(&auditor_kp.public());
    let pool_authority = Pubkey::new_unique();
    let pool = build_zk_pool(&mut env, &pool_authority, 10, 50 * SOL);
    let recipient = zk_recipient();
    env.fund(recipient, SOL);

    let blob = mirror_core::disclosure::seal(
        &auditor_kp.public(),
        mirror_core::Epoch(ZK_EPOCH),
        &mirror_core::Secret(FIXTURE_SECRET),
    );
    // The PDA for a DIFFERENT amount, published with the pool's denomination.
    let wrong_slot = env.disclosure_pda(
        &pool,
        &host_action_hash(&recipient, ZK_AMOUNT + 1),
        &auditor_kp.public(),
    );
    let ix = env.publish_ix(
        &wrong_slot,
        &pool,
        &recipient,
        true,
        &auditor_viewkey,
        &recipient,
        ZK_AMOUNT,
        &blob,
    );
    env.process(&ix, &[Check::err(custom(MirrorPoolError::InvalidPda))]);
}

/// A record about an amount this pool can never settle is about nothing, and is
/// refused before the address is even derived.
#[test]
fn publish_disclosure_rejects_an_off_denomination_amount() {
    let mut env = Env::new();
    let auditor_kp = viewing_keypair(15);
    let (_auditor, auditor_viewkey) = env.register_auditor(&auditor_kp.public());
    let pool_authority = Pubkey::new_unique();
    let pool = build_zk_pool(&mut env, &pool_authority, 10, 50 * SOL);
    let recipient = zk_recipient();
    env.fund(recipient, SOL);
    let blob = mirror_core::disclosure::seal(
        &auditor_kp.public(),
        mirror_core::Epoch(ZK_EPOCH),
        &mirror_core::Secret(FIXTURE_SECRET),
    );

    for amount in [1u64, ZK_AMOUNT - 1, ZK_AMOUNT + 1] {
        let record = env.disclosure_pda(&pool, &host_action_hash(&recipient, amount), &auditor_kp.public());
        let ix = env.publish_ix(
            &record,
            &pool,
            &recipient,
            true,
            &auditor_viewkey,
            &recipient,
            amount,
            &blob,
        );
        env.process(
            &ix,
            &[Check::err(custom(MirrorPoolError::DenominationMismatch))],
        );
    }
}

/// The reader must be a real, registered viewing key sitting at its own PDA. A
/// record that named an unregistered key would be a disclosure to nobody, and a
/// record that trusted a caller-supplied key would let anyone claim any reader.
#[test]
fn publish_disclosure_rejects_an_unregistered_or_forged_reader() {
    let mut env = Env::new();
    let auditor_kp = viewing_keypair(16);
    let (auditor, auditor_viewkey) = env.register_auditor(&auditor_kp.public());
    let pool_authority = Pubkey::new_unique();
    let pool = build_zk_pool(&mut env, &pool_authority, 10, 50 * SOL);
    let recipient = zk_recipient();
    env.fund(recipient, SOL);
    let blob = mirror_core::disclosure::seal(
        &auditor_kp.public(),
        mirror_core::Epoch(ZK_EPOCH),
        &mirror_core::Secret(FIXTURE_SECRET),
    );
    let action_hash = host_action_hash(&recipient, ZK_AMOUNT);
    let record = env.disclosure_pda(&pool, &action_hash, &auditor_kp.public());

    // (a) A never-registered authority: the PDA exists as an address but holds
    // nothing.
    let unregistered = env.viewkey_pda(&Pubkey::new_unique());
    let ix = env.publish_ix(
        &record,
        &pool,
        &recipient,
        true,
        &unregistered,
        &recipient,
        ZK_AMOUNT,
        &blob,
    );
    env.process(
        &ix,
        &[Check::err(custom(MirrorPoolError::ViewingKeyNotInitialized))],
    );

    // (b) A forged, program-owned account that PARSES as a registration but does
    // not sit at the PDA of the authority it names.
    let forged = Pubkey::new_unique();
    let mut data = vec![0u8; viewing_key::LEN];
    viewing_key::init(&mut data, &auditor.to_bytes(), &auditor_kp.public(), 255).unwrap();
    let mut account = Account::new(SOL, viewing_key::LEN, &env.program_id);
    account.data = data;
    env.accounts.insert(forged, account);
    let ix = env.publish_ix(
        &record,
        &pool,
        &recipient,
        true,
        &forged,
        &recipient,
        ZK_AMOUNT,
        &blob,
    );
    env.process(&ix, &[Check::err(custom(MirrorPoolError::InvalidPda))]);

    // (c) The real registration works.
    let ix = env.publish_ix(
        &record,
        &pool,
        &recipient,
        true,
        &auditor_viewkey,
        &recipient,
        ZK_AMOUNT,
        &blob,
    );
    env.process(&ix, &[Check::success()]);
}

/// The stored blob is structurally validated, not accepted as an opaque byte
/// string: its length is fixed by the layout and its ephemeral X25519 key must be
/// canonical and not small-order. The small-order case is the one that matters -
/// it is where a user believes they sealed to one reader and in fact sealed to
/// everybody.
#[test]
fn publish_disclosure_rejects_a_structurally_invalid_blob() {
    let mut env = Env::new();
    let auditor_kp = viewing_keypair(17);
    let (_auditor, auditor_viewkey) = env.register_auditor(&auditor_kp.public());
    let pool_authority = Pubkey::new_unique();
    let pool = build_zk_pool(&mut env, &pool_authority, 10, 50 * SOL);
    let recipient = zk_recipient();
    env.fund(recipient, SOL);
    let good = mirror_core::disclosure::seal(
        &auditor_kp.public(),
        mirror_core::Epoch(ZK_EPOCH),
        &mirror_core::Secret(FIXTURE_SECRET),
    );
    let action_hash = host_action_hash(&recipient, ZK_AMOUNT);
    let record = env.disclosure_pda(&pool, &action_hash, &auditor_kp.public());

    // (a) An all-zero (order-4) ephemeral key: the ECDH output would not depend
    // on the reader's secret at all.
    let mut degenerate = good.clone();
    degenerate[..32].copy_from_slice(&[0u8; 32]);
    let ix = env.publish_ix(
        &record,
        &pool,
        &recipient,
        true,
        &auditor_viewkey,
        &recipient,
        ZK_AMOUNT,
        &degenerate,
    );
    env.process(
        &ix,
        &[Check::err(custom(MirrorPoolError::InvalidDisclosureBlob))],
    );

    // (b) A non-canonical ephemeral encoding (high bit set).
    let mut aliased = good.clone();
    aliased[31] |= 0x80;
    let ix = env.publish_ix(
        &record,
        &pool,
        &recipient,
        true,
        &auditor_viewkey,
        &recipient,
        ZK_AMOUNT,
        &aliased,
    );
    env.process(
        &ix,
        &[Check::err(custom(MirrorPoolError::InvalidDisclosureBlob))],
    );

    // (c) A short and a long blob are malformed on shape alone.
    for body in [&good[..99], &good[..]] {
        let mut ix = env.publish_ix(
            &record,
            &pool,
            &recipient,
            true,
            &auditor_viewkey,
            &recipient,
            ZK_AMOUNT,
            body,
        );
        if body.len() == good.len() {
            ix.data.push(0);
        }
        env.process(
            &ix,
            &[Check::err(custom(MirrorPoolError::MalformedInstruction))],
        );
    }
    assert!(env.get(&record).data.is_empty());
}

/// A record is write-once: its publisher cannot come back and rewrite the
/// evidence.
#[test]
fn publish_disclosure_is_write_once() {
    let mut env = Env::new();
    let auditor_kp = viewing_keypair(18);
    let (_auditor, auditor_viewkey) = env.register_auditor(&auditor_kp.public());
    let pool_authority = Pubkey::new_unique();
    let pool = build_zk_pool(&mut env, &pool_authority, 10, 50 * SOL);
    let recipient = zk_recipient();
    env.fund(recipient, SOL);
    let first = mirror_core::disclosure::seal(
        &auditor_kp.public(),
        mirror_core::Epoch(ZK_EPOCH),
        &mirror_core::Secret(FIXTURE_SECRET),
    );
    let action_hash = host_action_hash(&recipient, ZK_AMOUNT);
    let record = env.disclosure_pda(&pool, &action_hash, &auditor_kp.public());

    let ix = env.publish_ix(
        &record,
        &pool,
        &recipient,
        true,
        &auditor_viewkey,
        &recipient,
        ZK_AMOUNT,
        &first,
    );
    env.process(&ix, &[Check::success()]);

    let second = mirror_core::disclosure::seal(
        &auditor_kp.public(),
        mirror_core::Epoch(ZK_EPOCH),
        &mirror_core::Secret([7u8; 32]),
    );
    let ix = env.publish_ix(
        &record,
        &pool,
        &recipient,
        true,
        &auditor_viewkey,
        &recipient,
        ZK_AMOUNT,
        &second,
    );
    env.process(
        &ix,
        &[Check::err(custom(
            MirrorPoolError::DisclosureAlreadyInitialized,
        ))],
    );
    assert_eq!(
        disclosure::blob(&env.get(&record).data).unwrap(),
        &first[..],
        "the original record must survive"
    );
}

/// A disclosure is scoped to a real pool: an account that is not one cannot be
/// disclosed about, or the record would look on-chain-verified while referencing
/// nothing.
#[test]
fn publish_disclosure_rejects_a_non_pool_account() {
    let mut env = Env::new();
    let auditor_kp = viewing_keypair(19);
    let (_auditor, auditor_viewkey) = env.register_auditor(&auditor_kp.public());
    let recipient = zk_recipient();
    env.fund(recipient, SOL);
    let blob = mirror_core::disclosure::seal(
        &auditor_kp.public(),
        mirror_core::Epoch(ZK_EPOCH),
        &mirror_core::Secret(FIXTURE_SECRET),
    );

    // A system-owned account, and a program-owned account of the wrong shape.
    let not_a_pool = Pubkey::new_unique();
    env.fund(not_a_pool, SOL);
    let wrong_shape = Pubkey::new_unique();
    env.accounts
        .insert(wrong_shape, Account::new(SOL, 16, &env.program_id));

    for candidate in [not_a_pool, wrong_shape] {
        let record = env.disclosure_pda(
            &candidate,
            &host_action_hash(&recipient, ZK_AMOUNT),
            &auditor_kp.public(),
        );
        let ix = env.publish_ix(
            &record,
            &candidate,
            &recipient,
            true,
            &auditor_viewkey,
            &recipient,
            ZK_AMOUNT,
            &blob,
        );
        env.process(
            &ix,
            &[Check::err(custom(MirrorPoolError::PoolNotInitialized))],
        );
    }
}

// ---------------------------------------------------------------------------
// Opt-in: the layer changes nothing for anyone who ignores it
// ---------------------------------------------------------------------------

/// The whole point of "opt-in". A settlement runs to completion with no viewing
/// key registered anywhere and no disclosure record in existence: SETTLE_ZK never
/// reads either account. The second half of the test then publishes the record
/// for that same action and shows the reader recomputes exactly the nullifier the
/// settle burned - the disclosure is true, and it was never required.
#[test]
fn settling_needs_no_viewing_key_and_no_record() {
    let mut env = Env::new();
    env.install_vk(mirror_pool::wire::CIRCUIT_MEMBERSHIP);

    let authority = Pubkey::new_unique();
    env.fund(authority, SOL);
    let pool = build_zk_pool(&mut env, &authority, 10, 50 * SOL);
    let recipient = zk_recipient();
    env.fund(recipient, 0);
    env.warp(((ZK_EPOCH + 1) * 10) + 1);

    let nf = env.nf_pda(&pool, ZK_EPOCH, &fixture::PUBLIC_INPUTS[1]);
    let ix = env.settle_zk_ix(&pool, &authority, &nf, &recipient);
    env.process(&ix, &[Check::success()]);
    assert_eq!(
        env.get(&recipient).lamports,
        ZK_AMOUNT,
        "the settle must pay the bound recipient with no disclosure anywhere"
    );

    // Now the user discloses that same action to an auditor they chose.
    let auditor_kp = viewing_keypair(20);
    let (_auditor, auditor_viewkey) = env.register_auditor(&auditor_kp.public());
    let blob = mirror_core::disclosure::seal(
        &auditor_kp.public(),
        mirror_core::Epoch(ZK_EPOCH),
        &mirror_core::Secret(FIXTURE_SECRET),
    );
    let action_hash = host_action_hash(&recipient, ZK_AMOUNT);
    let record = env.disclosure_pda(&pool, &action_hash, &auditor_kp.public());
    let payer = Pubkey::new_unique();
    env.fund(payer, SOL);
    let ix = env.publish_ix(
        &record,
        &pool,
        &recipient,
        true,
        &auditor_viewkey,
        &payer,
        ZK_AMOUNT,
        &blob,
    );
    env.process(&ix, &[Check::success()]);

    // The reader opens it and lands on the settlement that just happened.
    let stored = env.get(&record).data;
    let opened = mirror_core::disclosure::open(
        &auditor_kp.to_secret_bytes(),
        disclosure::blob(&stored).unwrap(),
    )
    .expect("the auditor must open the record");
    let action =
        mirror_core::disclosure::derive_action(&opened, &disclosure::action_hash(&stored).unwrap());
    assert_eq!(action.nullifier.0, fixture::PUBLIC_INPUTS[1]);
    let disclosed_nf = env.nf_pda(&pool, action.epoch.0, &action.nullifier.0);
    assert_eq!(
        disclosed_nf, nf,
        "the disclosed nullifier must derive the PDA the settle created"
    );
    assert!(
        !env.get(&disclosed_nf).data.is_empty(),
        "and that PDA must exist on-chain, which is how the reader confirms it settled"
    );
}

/// The mirrored X25519 structural test really is a mirror: the program's copy and
/// `mirror_core`'s agree on every vector that matters, so the CLI can refuse
/// locally exactly what the chain would refuse.
#[test]
fn viewing_key_validation_mirrors_mirror_core() {
    let mut vectors: Vec<[u8; 32]> = Vec::new();
    for seed in 0..8u8 {
        vectors.push(viewing_keypair(seed).public());
        vectors.push(bytes(seed));
    }
    // Degenerate cases.
    vectors.push([0u8; 32]);
    let mut one = [0u8; 32];
    one[0] = 1;
    vectors.push(one);
    let mut p = [0xffu8; 32];
    p[0] = 0xed;
    p[31] = 0x7f;
    vectors.push(p);
    let mut p_minus_1 = p;
    p_minus_1[0] = 0xec;
    vectors.push(p_minus_1);
    let mut p_plus_1 = p;
    p_plus_1[0] = 0xee;
    vectors.push(p_plus_1);
    let mut high = viewing_keypair(1).public();
    high[31] |= 0x80;
    vectors.push(high);

    for v in &vectors {
        assert_eq!(
            viewing_key::is_acceptable_viewing_pub(v),
            mirror_core::encrypted_note::is_acceptable_x25519_pubkey(v),
            "the program and mirror-core must agree on {v:?}"
        );
    }

    // And the disclosure wire sizes are mirrors too.
    assert_eq!(
        mirror_pool::wire::REGISTER_VIEWING_KEY_LEN,
        mirror_core::wire::REGISTER_VIEWING_KEY_LEN
    );
    assert_eq!(
        mirror_pool::wire::PUBLISH_DISCLOSURE_LEN,
        mirror_core::wire::PUBLISH_DISCLOSURE_LEN
    );
    assert_eq!(
        mirror_pool::wire::DISCLOSURE_BLOB_LEN,
        mirror_core::wire::DISCLOSURE_BLOB_LEN
    );
    assert_eq!(tag::REGISTER_VIEWING_KEY, mirror_core::wire::tag::REGISTER_VIEWING_KEY);
    assert_eq!(tag::PUBLISH_DISCLOSURE, mirror_core::wire::tag::PUBLISH_DISCLOSURE);
    assert_eq!(VIEWING_KEY_SEED, mirror_core::wire::VIEWING_KEY_SEED);
    assert_eq!(DISCLOSURE_SEED, mirror_core::wire::DISCLOSURE_SEED);
}
