//! Export a ceremony-produced verifying key in the two shapes this repo already
//! consumes.
//!
//! - [`snarkjs_json`] writes the `verification_key.json` shape, so a ceremony
//!   output can be checked with `snarkjs groth16 verify` and dropped into
//!   `circuits/artifacts/` unchanged.
//! - [`solana_bytes`] and [`rust_source`] write the big-endian, uncompressed
//!   `groth16-solana` layout the on-chain program embeds
//!   (`programs/mirror-pool/src/vk.rs`), which is the same layout
//!   `circuits/convert_to_rust.js` emits.
//!
//! Deploying a ceremony key therefore means: run the ceremony, export, replace the
//! generated `vk.rs`, rebuild the program, and redeploy.

use ark_bn254::{Bn254, Fq, G1Affine, G2Affine};
use ark_ec::AffineRepr;
use ark_groth16::VerifyingKey;

use crate::points;

/// The verifying key in the on-chain byte layout.
pub struct SolanaVerifyingKey {
    /// Number of public inputs (`gamma_abc_g1.len() - 1`).
    pub nr_pubinputs: usize,
    pub alpha_g1: [u8; 64],
    pub beta_g2: [u8; 128],
    pub gamma_g2: [u8; 128],
    pub delta_g2: [u8; 128],
    /// `nr_pubinputs + 1` entries; `ic[0]` is the constant term.
    pub ic: Vec<[u8; 64]>,
}

/// Convert a verifying key into the `groth16-solana` byte layout.
pub fn solana_bytes(vk: &VerifyingKey<Bn254>) -> SolanaVerifyingKey {
    SolanaVerifyingKey {
        nr_pubinputs: vk.gamma_abc_g1.len().saturating_sub(1),
        alpha_g1: points::g1_bytes(&vk.alpha_g1),
        beta_g2: points::g2_bytes(&vk.beta_g2),
        gamma_g2: points::g2_bytes(&vk.gamma_g2),
        delta_g2: points::g2_bytes(&vk.delta_g2),
        ic: vk.gamma_abc_g1.iter().map(points::g1_bytes).collect(),
    }
}

/// The snarkjs `verification_key.json` shape.
///
/// `vk_alphabeta_12` (a precomputed target-group element snarkjs stores for its
/// Solidity exporter) is deliberately not emitted: `snarkjs groth16 verify` does
/// not read it, and recomputing it here would add a target-group dependency for a
/// field nothing in this repo consumes.
pub fn snarkjs_json(vk: &VerifyingKey<Bn254>) -> String {
    let n_public = vk.gamma_abc_g1.len().saturating_sub(1);
    let ic: Vec<String> = vk
        .gamma_abc_g1
        .iter()
        .map(|p| indent_g1(p, 8))
        .collect::<Vec<_>>();
    format!(
        "{{\n \"protocol\": \"groth16\",\n \"curve\": \"bn128\",\n \"nPublic\": {n_public},\n \
         \"vk_alpha_1\": {alpha},\n \"vk_beta_2\": {beta},\n \"vk_gamma_2\": {gamma},\n \
         \"vk_delta_2\": {delta},\n \"IC\": [\n{ic}\n ]\n}}\n",
        alpha = g1_json(&vk.alpha_g1),
        beta = g2_json(&vk.beta_g2),
        gamma = g2_json(&vk.gamma_g2),
        delta = g2_json(&vk.delta_g2),
        ic = ic.join(",\n"),
    )
}

fn indent_g1(p: &G1Affine, spaces: usize) -> String {
    format!("{:width$}{}", "", g1_json(p), width = spaces)
}

fn g1_json(p: &G1Affine) -> String {
    let Some((x, y)) = p.xy() else {
        return "[\"0\", \"1\", \"0\"]".to_string();
    };
    format!("[\"{}\", \"{}\", \"1\"]", fq(&x), fq(&y))
}

fn g2_json(p: &G2Affine) -> String {
    let Some((x, y)) = p.xy() else {
        return "[[\"0\", \"0\"], [\"1\", \"0\"], [\"0\", \"0\"]]".to_string();
    };
    format!(
        "[[\"{}\", \"{}\"], [\"{}\", \"{}\"], [\"1\", \"0\"]]",
        fq(&x.c0),
        fq(&x.c1),
        fq(&y.c0),
        fq(&y.c1)
    )
}

/// A base-field element as a decimal string, matching snarkjs's JSON.
fn fq(x: &Fq) -> String {
    x.to_string()
}

/// Emit the `groth16-solana` Rust constant, in the same shape
/// `circuits/convert_to_rust.js` produces.
///
/// `provenance` is a one-line description of where the key came from; it is written
/// into the header comment so a generated `vk.rs` always says which ceremony (or
/// which dev setup) it belongs to.
pub fn rust_source(
    vk: &VerifyingKey<Bn254>,
    label: &str,
    public_input_order: &[&str],
    provenance: &str,
) -> String {
    let b = solana_bytes(vk);
    let mut s = String::new();
    s.push_str("// @generated by `mirror-cli ceremony export-vk` - DO NOT EDIT BY HAND.\n");
    s.push_str(&format!(
        "// {label} verifying key, groth16-solana v0.2.0 layout.\n"
    ));
    s.push_str(
        "// All big-endian, uncompressed. G1 = x||y (64B). G2 = x_c1||x_c0||y_c1||y_c0 (128B).\n",
    );
    s.push_str(&format!("// {provenance}\n"));
    s.push_str(&format!(
        "// Public inputs ({}), in order: {}.\n",
        b.nr_pubinputs,
        public_input_order.join(", ")
    ));
    s.push_str(&format!(
        "// vk_ic has nPublic + 1 = {} entries (IC[0] is the constant term).\n",
        b.ic.len()
    ));
    s.push_str("use groth16_solana::groth16::Groth16Verifyingkey;\n\n");
    s.push_str("pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {\n");
    s.push_str(&format!("    nr_pubinputs: {},\n\n", b.nr_pubinputs));
    s.push_str(&field("vk_alpha_g1", &b.alpha_g1));
    s.push_str(&field("vk_beta_g2", &b.beta_g2));
    // The `vk_gamme_g2` spelling matches the (typo'd) field name in
    // groth16-solana 0.2.0.
    s.push_str(&field("vk_gamme_g2", &b.gamma_g2));
    s.push_str(&field("vk_delta_g2", &b.delta_g2));
    s.push_str("    vk_ic: &[\n");
    for entry in &b.ic {
        s.push_str("        [\n");
        s.push_str(&bytes_block(entry, "            "));
        s.push_str("        ],\n");
    }
    s.push_str("    ],\n};\n");
    s
}

fn field(name: &str, bytes: &[u8]) -> String {
    format!(
        "    {name}: [\n{}    ],\n\n",
        bytes_block(bytes, "        ")
    )
}

fn bytes_block(bytes: &[u8], indent: &str) -> String {
    let mut out = String::new();
    for chunk in bytes.chunks(12) {
        out.push_str(indent);
        let parts: Vec<String> = chunk.iter().map(|b| b.to_string()).collect();
        out.push_str(&parts.join(", "));
        out.push_str(",\n");
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use ark_bn254::Fr;
    use ark_ec::CurveGroup;

    fn sample_vk() -> VerifyingKey<Bn254> {
        VerifyingKey {
            alpha_g1: (G1Affine::generator() * Fr::from(2u64)).into_affine(),
            beta_g2: (G2Affine::generator() * Fr::from(3u64)).into_affine(),
            gamma_g2: (G2Affine::generator() * Fr::from(5u64)).into_affine(),
            delta_g2: (G2Affine::generator() * Fr::from(7u64)).into_affine(),
            gamma_abc_g1: vec![
                G1Affine::generator(),
                (G1Affine::generator() * Fr::from(11u64)).into_affine(),
            ],
        }
    }

    #[test]
    fn json_is_parseable_and_has_the_snarkjs_shape() {
        let vk = sample_vk();
        let value: serde_json::Value = serde_json::from_str(&snarkjs_json(&vk)).unwrap();
        assert_eq!(value["protocol"], "groth16");
        assert_eq!(value["curve"], "bn128");
        assert_eq!(value["nPublic"], 1);
        assert_eq!(value["IC"].as_array().unwrap().len(), 2);
        assert_eq!(value["vk_alpha_1"].as_array().unwrap().len(), 3);
        assert_eq!(value["vk_beta_2"].as_array().unwrap().len(), 3);
    }

    #[test]
    fn solana_bytes_match_the_documented_layout() {
        let vk = sample_vk();
        let b = solana_bytes(&vk);
        assert_eq!(b.nr_pubinputs, 1);
        assert_eq!(b.ic.len(), 2);
        // G2 is imaginary-part-first, so the first 32 bytes are x.c1.
        let x = vk.beta_g2.x().unwrap();
        assert_eq!(&b.beta_g2[..32], &fq_be(&x.c1)[..]);
        assert_eq!(&b.beta_g2[32..64], &fq_be(&x.c0)[..]);
        // G1 is plain x || y.
        let (ax, ay) = vk.alpha_g1.xy().unwrap();
        assert_eq!(&b.alpha_g1[..32], &fq_be(&ax)[..]);
        assert_eq!(&b.alpha_g1[32..], &fq_be(&ay)[..]);
    }

    fn fq_be(x: &Fq) -> Vec<u8> {
        use ark_ff::{BigInteger, PrimeField};
        let be = x.into_bigint().to_bytes_be();
        let mut out = vec![0u8; 32 - be.len()];
        out.extend_from_slice(&be);
        out
    }

    #[test]
    fn rust_source_compiles_shape() {
        let src = rust_source(&sample_vk(), "test", &["a"], "test provenance");
        assert!(src.contains("pub const VERIFYINGKEY: Groth16Verifyingkey"));
        assert!(src.contains("nr_pubinputs: 1,"));
        assert!(src.contains("vk_gamme_g2"));
        assert!(src.contains("test provenance"));
    }
}
